### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by juagargi**
GetFreeID fix.
Set correct IPs after editing a connection.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/180)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 427 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180#-L78bmr2Z2xGWjD-21lW:-L78bmr3GnrFS4Pft08s:bl7lna5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/models/scion_lab.go#L427)):*
> ```Go
> 	if respondAS.ID == as.ID {
> 		if !cn.IsVPN {
> 			cn.RespondIP = as.PublicIP
> ```

What is the purpose of PublicIP if it is no longer user for non-VPN connections?
Isn't the actual bug the fact that cn.IsVPN is only set after the two conditionals?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 427 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180#-L78bmr2Z2xGWjD-21lW:-L79-B2cp37VTXxpkuQI:b7j0vl5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/models/scion_lab.go#L427)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

What is the purpose of PublicIP if it is no longer user for non-VPN connections?
Isn't the actual bug the fact that cn.IsVPN is only set after the two conditionals?
</blockquote></details>

The `cnInfo.LocalIP` is already set correctly in `api/scion_lab.go` (via `asInfo.IP`) such that we can simply use that here.
The `PublicIP` field is currently used, e.g., to show the correct information in the UI. Also, it is important for APs to configure connections properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180#-:-L79-kk9GC2-tJ6djF2H:bnfp4nl)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 427 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180#-L78bmr2Z2xGWjD-21lW:-L7L5pq-Lc6i-FUTnWNC:b-gbhrjk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/models/scion_lab.go#L427)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

The `cnInfo.LocalIP` is already set correctly in `api/scion_lab.go` (via `asInfo.IP`) such that we can simply use that here.
The `PublicIP` field is currently used, e.g., to show the correct information in the UI. Also, it is important for APs to configure connections properly.
</blockquote></details>

I still don't have a well understanding on the intentions of the code in the coordinator, but we can always make suggestions on a redesign if we find the current state not easy to follow.
For know I'm trying to leave the smallest footprint with these fixes. I don't intent to redesign any part if I can avoid to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180)*

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/180#-:-L7Ome4mraStmvemUoPt:bnfp4nl)*

**Pull request merged**
