### PR TITLE
Modify README.md to reflect renaming of "scion" repository

### PR DESCRIPTION
**Pull request by mlegner**
This PR is a temporary fix for #141.
In the long run, we should add scion-web libraries as a submodule as discussed in #116.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/143)

### CODE REVIEW

**Comment by hausheer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143#-L0dCL1LA-TOW60PICZd:-L0dCL1LA-TOW60PICZe:b-nkdscs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/7699d82f01ac8d3aa094ea361154461814638f9a/README.md#L27)):*
> ```Markdown
> mkdir -p "$GOPATH/src/github.com/netsec-ethz"
> cd "$GOPATH/src/github.com/netsec-ethz"
> git clone --recursive -b scionlab git@github.com:netsec-ethz/scion scion
> ```

I think it should be 
git clone --recursive -b scionlab git@github.com:netsec-ethz/netsec-scion scion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143)*

**Comment by mlegner** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143#-L0dCL1LA-TOW60PICZd:-L0dF0vafMbqvCC649_A:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/7699d82f01ac8d3aa094ea361154461814638f9a/README.md#L27)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

I think it should be 
git clone --recursive -b scionlab git@github.com:netsec-ethz/netsec-scion scion
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143)*

**Comment by hausheer** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143#-:-L0dXrSwhLz8gSTgdAcg:bnfp4nl)*

**Comment by hausheer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/143)*

**Pull request merged**
