### PR TITLE
Include affected AS ID in email notification

### PR DESCRIPTION
**Pull request by FR4NK-W**
Solves issue #212

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/213)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
You are right, that was an ugly PR, updated it

**Comment by chaehni** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213#-:-L9tAlS3-eiYt0rmomKm:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/api/scion_lab_ap.go, line 223 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213#-L9p7kmv04gf2B5uqhTQ:-L9uK7igDwqfDNTG0bAA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff4a59647ffed98b138b12673da70f27af0663e8/controllers/api/scion_lab_ap.go#L223)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We could directly use `string` here instead of `IA`, this is also what the function `as.IA()` provides.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab_ap.go, line 319 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213#-L9p7uo_4g0gRr4h5eLX:-L9uK8L9-mJ9Jca160J5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff4a59647ffed98b138b12673da70f27af0663e8/controllers/api/scion_lab_ap.go#L319)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This line is not necessary if we change the type of IA. We can directly use IA below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213)*

**Comment by mlegner** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213#-:-L9uTOQuA3Pm2agck2uc:bnfp4nl)*

**Comment by juagargi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/213#-:-L9y24N3BzZJ0gRKwuug:bg7igk9)*

**Pull request merged**
