### PR TITLE
Adjust code to use new database structure and naming conventions

### PR DESCRIPTION
**Pull request by mlegner**
This is a major refactoring commit that addresses issues #97 and #119 by finishing what PR #110 started
Many of the API functions are changed to work with the new database structure
In addition, a large number of variable names and strings in comments and literals is changed to conform to the new naming conventions
Some names were adjusted to conform to golang coding conventions, in particular initialisms
Some tests and database entries were slightly modified

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/133)

### CODE REVIEW

**Comment by philippmao** [comment]
Reviewed 16 of 37 files at r1.
Review status: 16 of 36 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[main.go, line 54 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-pCjvgIUZXvn02u7Pu:-L-pCjvgIUZXvn02u7Pv:b-bcr5rz) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6766a8a3eb71f819652488360b365303d9d9b1d7/main.go#L54)):*
> ```Go
> 
> func main() {
> 	if !checkCredentials() {
> ```

In the future this should be expanded to check something like:   credentials/ISD1/,  credentials/ISD2 and so on. (for all ISDs part of the SCIONLab network)

---

*[models/scion_lab.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-pE6MiwWO0DRhqadBZ:-L-pE6MiwWO0DRhqadB_:b-pxhygj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6766a8a3eb71f819652488360b365303d9d9b1d7/models/scion_lab.go#L107)):*
> ```Go
> 		return "127.0.0.1"
> 	}
> 	// TODO(mlegner): Do we need specific rules for BOX?
> ```

No the Box Controller takes care of that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133)*

**Comment by philippmao** [comment]
Reviewed 14 of 37 files at r1, 9 of 12 files at r2.
Review status: 31 of 34 files reviewed at latest revision, 4 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 199 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-poeMB3s4EoDzPyrgU:-L-poeMB3s4EoDzPyrgV:b-8sal7n) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d76133bb85f9e1057409bd6d4f524b7731fde412/controllers/api/scion_lab.go#L199)):*
> ```Go
> 	var cn models.ConnectionInfo
> 	// See if this user already has an AS
> 	slas, err := models.FindOneSCIONLabASByUserEmail(userEmail)
> ```

add a TODO to replace this function once users are able to generate different ASes. 
Also if we have this temporary solution we should probably use FindSCIONLabASbyUserEmailType since that way we can avoid conflicts with the Boxes.

---

*[models/scion_lab.go, line 178 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-py8FXfJCv8nC6iSuC:-L-py8FXfJCv8nC6iSuD:b-kzkgge) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d76133bb85f9e1057409bd6d4f524b7731fde412/models/scion_lab.go#L178)):*
> ```Go
> }
> 
> func (as *SCIONLabAS) GetFreeBRID() (int, error) {
> ```

sometimes as is used other times slas is used. I think you should choose one and make sure all are the same. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133)*

**Comment by mlegner** [comment]
Review status: 31 of 34 files reviewed at latest revision, 4 unresolved discussions.

---

*[main.go, line 54 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-pCjvgIUZXvn02u7Pu:-L-pzWE5h8HdgF6TPIbA:b58vmga) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6766a8a3eb71f819652488360b365303d9d9b1d7/main.go#L54)):*
<details><summary><i>Previously, philippmao wrote…</i></summary><blockquote>

In the future this should be expanded to check something like:   credentials/ISD1/,  credentials/ISD2 and so on. (for all ISDs part of the SCIONLab network)
</blockquote></details>

This will be done in the follow-up PR supporting multiple APs.

---

*[controllers/api/scion_lab.go, line 199 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-poeMB3s4EoDzPyrgU:-L-pzgSaNJSeKDCZDGSl:b-dfsuzm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d76133bb85f9e1057409bd6d4f524b7731fde412/controllers/api/scion_lab.go#L199)):*
<details><summary><i>Previously, philippmao wrote…</i></summary><blockquote>

add a TODO to replace this function once users are able to generate different ASes. 
Also if we have this temporary solution we should probably use FindSCIONLabASbyUserEmailType since that way we can avoid conflicts with the Boxes.
</blockquote></details>

This is fixed in the follow-up PR.

---

*[models/scion_lab.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-pE6MiwWO0DRhqadBZ:-L-q0XkwpHfEJIamXZ-v:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6766a8a3eb71f819652488360b365303d9d9b1d7/models/scion_lab.go#L107)):*
<details><summary><i>Previously, philippmao wrote…</i></summary><blockquote>

No the Box Controller takes care of that. 
</blockquote></details>

Done.

---

*[models/scion_lab.go, line 178 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-L-py8FXfJCv8nC6iSuC:-L-q0ZCoN9nkyuu5snu-:b-dfsuzm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d76133bb85f9e1057409bd6d4f524b7731fde412/models/scion_lab.go#L178)):*
<details><summary><i>Previously, philippmao wrote…</i></summary><blockquote>

sometimes as is used other times slas is used. I think you should choose one and make sure all are the same. 
</blockquote></details>

This is fixed in the follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133)*

**Comment by hausheer** [comment]
I think I overlooked this PR last week, which seems to be one of the major ones, too. @philippmao  @chaehni thank you for reviewing this PR. Github shows that some checks and (new) conflicts (after merging #131) are still open. @mlegner did you have a chance to take a look?

**Comment by mlegner** [comment]
@hausheer I just rebased the PR and resolved the conflicts. In order to be able to merge it, the discussions on Reviewable would have to be resolved (@philippmao).

**Comment by mlegner** [comment]
@philippmao Could you please resolve the open discussions?

**Comment by chaehni** [comment]
Reviewed 10 of 15 files at r3.
Review status: 36 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: 36 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133#-:-L4HiUrAI8ok0wBNAatn:bnfp4nl)*

**Comment by chaehni** [comment]
Reviewed 1 of 37 files at r1, 5 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/133)*

**Pull request merged**
