### PR TITLE
Improved README in tarball

### PR DESCRIPTION
**Pull request by mlegner**
This PR fixes some minor problems in the README file and adds a small troubleshooting section.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/107)

### CODE REVIEW

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/107#-:-Kyz4iUSoLounl7nrJwR:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/107)*

**Comment by mlegner** [comment]
@ercanucan: I added a small additional change such that the code segments are properly formatted on github.

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/107#-:-Kz4VDc9CeYBJgWgiF0w:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/107)*

**Pull request merged**
