### PR TITLE
Adapt code to work with new SCION dependencies

### PR DESCRIPTION
**Pull request by chaehni**
This fixes https://github.com/netsec-ethz/scion-coord/issues/39

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/40)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vendor/vendor.json, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40#-KrVeLoeXkz0IxhGB4R-:-KrVeLofDJVqVDjQVM9y:b88xf05) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/a774f8d26931d47b61a5b3bd0c4405ecd3e9d04f/vendor/vendor.json#L1)):*
> ```JSON
> {
> ```

@chaehni this is fine, but were all the dependency updates necessary in `vendor.json` to make scion-coord work with CircleCI? Also, please rebase the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40)*

**Comment by chaehni** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vendor/vendor.json, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40#-KrVeLoeXkz0IxhGB4R-:-Kr_CKM09QStvOzxe_E3:b1nngdo) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/a774f8d26931d47b61a5b3bd0c4405ecd3e9d04f/vendor/vendor.json#L1)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

@chaehni this is fine, but were all the dependency updates necessary in `vendor.json` to make scion-coord work with CircleCI? Also, please rebase the PR.
</blockquote></details>

Actually no dependency update was necessary as scion-coord works with the old dependencies. Are all these outdated revisions used deliberately?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40)*

**Comment by ercanucan** [comment]
@chaehni Please rebase

**Comment by chaehni** [comment]
@ercanucan Did the rebasing.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40#-:-KrpmSBtjTfuhgR6duuQ:bh4z05c)*

**Comment by ercanucan** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/40#-:-Krq7eT9Q1NI8Ye_HfLA:bnfp4nl)*

**Pull request merged**
