### PR TITLE
Fix for some errors introduced in PR #72

### PR DESCRIPTION
**Pull request by mlegner**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/76)

### CODE REVIEW

**Comment by ercanucan** [comment]
:lgtm: only one minor comment.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/config.go, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76#-Kv82rMDEn7CLLOPL348:-Kv82rMDEn7CLLOPL349:b-n81ll1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/eed269be1cf811cedbe0b48202bb615d8b763924/config/config.go#L56)):*
> ```Go
> 	SERVER_VPN_START_IP      = goconf.AppConf.String("server.vpn.start_ip")
> 	SERVER_VPN_END_IP        = goconf.AppConf.String("server.vpn.end_ip")
> 	VM_LOCAL_IP              = "10.0.2.15" // Local IP address in VM
> ```

It might be a good idea to put a comment here saying that this is the IP address which comes as default with the Vagrantfile; and that if the configuration inside Vagrantfile changes, this field should also be updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76#-:-Kv83uWA7N9yW8hwUNxK:b-ct5qxz)*

**Comment by ercanucan** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76)*

**Comment by mlegner** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/config.go, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76#-Kv82rMDEn7CLLOPL348:-Kv84Z3zphhk2GwVFOu8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/eed269be1cf811cedbe0b48202bb615d8b763924/config/config.go#L56)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

It might be a good idea to put a comment here saying that this is the IP address which comes as default with the Vagrantfile; and that if the configuration inside Vagrantfile changes, this field should also be updated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/76)*

**Pull request merged**
