### PR TITLE
Unique account for each user

### PR DESCRIPTION
**Pull request by mlegner**
This commit removes the mandatory Organization Account from the registration; 
instead, a new unique account is created for each new user, based on their email address. 
The field Organization is not mandatary any more.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/59)

### CODE REVIEW

**Comment by chaehni** [comment]
@mlegner  Thanks for the work. I have multiple remarks/questions:
- The idea behind an organizational account is to bind users of the same organization together. This might be useful if, for example, all users of an organization need to be revoked. What is, in your opinion,  the benefit of assigning each user an individual account?
- If every user has its own account, aren't the two concepts then basically the same? Shouldn't they be merged in that case?
- The `RegisterUser `function would need to be cleaned up
- The `RegisterPost function `is the wrong place to make these changes as it is dead code that will be removed
- Capitalizing the 'u' in `user ` makes this struct exported. While this might be beneficial, I don't think this should be done just for consistency reasons.

**Comment by mlegner** [comment]
Thanks for the feedback @chaehni! Some explanations:
* I should have described the rationale behind this commit as you were not in the loop when this was discussed with @ercanucan and @hausheer. The problem with the current implementation is that users can assign themselves to any organization account without any checks and obtain the respective account_id and secret. As a temporary fix to this security issue, we discussed to simply create unique accounts for each user.
* Indeed, for the time being, users and accounts would be somewhat redundand. However, in order to allow for the originally intended functionality at a later point (when we implement a more sophisticated authentification system) I left the two models separate for now.
* For the same reason, I left the RegisterUser function unchanged.
* Sorry, this was indeed a mistake from my side; I'm still new to golang and did not think about this behavior when I made the change. I will revert this change.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/59#-:-Ksn78dOgYYsTlBYQC3e:b-2zxgz0)*

**Comment by chaehni** [comment]
@mlegner Thanks for clarifying. As a temporary fix this makes sense to me now.

**Comment by chaehni** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/59)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/59#-:-KsxCU-oPOOXVSQjYCiQ:bnfp4nl)*

**Comment by ercanucan** [comment]
@chaehni can you please close the open "discussions" on Reviewable?

**Comment by chaehni** [comment]
:lgtm: 

---

Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/59#-:-KsxHWIuIaL1K04I7B1L:bg7igkv)*

**Pull request merged**
