### PR TITLE
Fixbrid reconfigure

### PR DESCRIPTION
**Pull request by juagargi**
Merge after PR #186 
Issue #187

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/188)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 310 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L78jqzxKkqW1g95jDbp:-L78jqzyn8XkTSpT7Ufg:b-f6mugy) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L310)):*
> Old
See comments on PR #186

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by mlegner** [comment]
Maybe I'm doing something wrong, but I don't see the difference to #186.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L797wgDM8hFWamyC_G5:b-niej52)*

**Comment by mlegner** [comment]
In my opinion it would be nicer to add a field `NeighborBRID` to `ConnectionInfo` instead of this relatively complicated workaround.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L79bS-19PRqfTrxNrUL:b-7cdhyw)*

**Comment by mlegner** [comment]
Also, we don't actually need `RemoteBRID` if `newConnection == false`. We only need to know `RemotePort` (in line 535), which we already get in the `ConnectionInfo`.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L79dJ0dqN29Treo_Qag:bag9h53)*

**Comment by juagargi** [comment]
Simplified now.

---

Reviewed 2 of 3 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 310 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L78jqzxKkqW1g95jDbp:-L7Q6Rq6MH1JkWCtzoNS:b-y9up1s) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L310)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> Old
See comments on PR #186
</blockquote></details>

Yup. Because the PR was made on top of another PR, this was shown as a change from this PR. It was not, and it was indeed fixed in PR 186, as you pointed out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L7Q6DsaArRQK5FUemNB:blgg2e3)*

**Comment by juagargi** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 310 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L78jqzxKkqW1g95jDbp:-L7Q7Q5FEjYIFzvX2GD4:b-e8u081) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L310)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Yup. Because the PR was made on top of another PR, this was shown as a change from this PR. It was not, and it was indeed fixed in PR 186, as you pointed out.
</blockquote></details>

I don't know why reviewable still asks me for another comment here! :P 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/scion_lab.go, line 310 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L78jqzxKkqW1g95jDbp:-L7Q7wTw6v9puWIT06cb:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L310)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I don't know why reviewable still asks me for another comment here! :P 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by FR4NK-W** [comment]
:lgtm: One minor point about cns

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[controllers/api/scion_lab.go, line 335 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7Tx7LJCPuEovq08ntd:-L7Tx7LJCPuEovq08nte:b-yux572) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5631fe9e2420082be5fefd544b5aef9b6b7e4470/controllers/api/scion_lab.go#L335)):*
> ```Go
> 		if oldAP == slReq.ServerIA { // oldAP is e.g. 1-17
> 			newConnection = false
> 			cn = cns[0]
> ```

Is there any guarantee on the order of the cns returned by GetJoinConnectionInfo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L7TxKEwCFX87eGDuLKQ:b-79uljj)*

**Comment by juagargi** [comment]
From that minor point I've found we need to get rid of one design decision: more than one connection (1 active, n inactive) will be possible for any given AS.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/scion_lab.go, line 335 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7Tx7LJCPuEovq08ntd:-L7U0qSLWC1mXzvtZicD:bz2ag63) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5631fe9e2420082be5fefd544b5aef9b6b7e4470/controllers/api/scion_lab.go#L335)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Is there any guarantee on the order of the cns returned by GetJoinConnectionInfo?
</blockquote></details>

Nope. Worse than that, I've noticed we have the assumption of only one connection is possible for any given AS. 
I'm reviewing the code in general to get rid of such assumption.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L7U12pUBc7auZLiHhV2:b79xvcs)*

**Comment by FR4NK-W** [comment]
Reviewed 4 of 5 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/api/user.go, line 127 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7UfRqKPy4zdrhp35lr:-L7UfRqLFgDAg-A-Htgd:bckhjum) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/72ff6641178f31194fded880e2d8e602610afca0/controllers/api/user.go#L127)):*
> ```Go
> 		}
> 
> 		cns, err := as.GetJoinConnectionInfo()
> ```

What is that query used for now that active queries are queried 3 lines below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by FR4NK-W** [comment]
Reviewed 1 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/user.go, line 127 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7UfRqKPy4zdrhp35lr:-L7UggrzAOk4wqS7qv58:bc050ct) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/72ff6641178f31194fded880e2d8e602610afca0/controllers/api/user.go#L127)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

What is that query used for now that active queries are queried 3 lines below?
</blockquote></details>

Or to put it differently, OnlyCurrentlyActiveConnections is filtering the connections. For clarity, could it also do the query itself and the associated error handling?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/user.go, line 127 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7UfRqKPy4zdrhp35lr:-L7UgsxsEYs9HkGWrm90:b-q4q7bz) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/72ff6641178f31194fded880e2d8e602610afca0/controllers/api/user.go#L127)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

What is that query used for now that active queries are queried 3 lines below?
</blockquote></details>

cns are returned, including active and inactive connections. The query three lines below filters cns to keep only active ones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/user.go, line 127 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7UfRqKPy4zdrhp35lr:-L7UhANdDYPzdZMFHDCI:bgh0nee) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/72ff6641178f31194fded880e2d8e602610afca0/controllers/api/user.go#L127)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

cns are returned, including active and inactive connections. The query three lines below filters cns to keep only active ones.
</blockquote></details>

The code is going to look much more verbose if we remove the filter function in favor for one that would return the active ones directly from the AS, because we have join and respond methods. Being active or not can be seen as a variable, and when we will decide to add another one, like updated or not (or sorted, or....) we will need to add again all these methods again. That's why I'm more in favor of the filter functions.
Buuut, if we don't plan to add more variables to filter connections, we can do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by juagargi** [comment]
Latest changes include some refactoring and fixes for confirming the changes from the APs.
Essentially, we can now have from a user AS 0 or 1 "current" connections and 0 to N not current connections to APs. E.g. 1001 has not current (former) connections to 1-17 and 3-33 and a current connection to 3-33. Yup, 3-33 and 1001 can have a former connection and a current connection, but that's the highest number of connections we can have between an AP and an AS.

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-:-L7VMZdpBHZLpDKSZwN7:b-bf99ux)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/user.go, line 127 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188#-L7UfRqKPy4zdrhp35lr:-L7VOAsw66_pEFAIRpWy:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/72ff6641178f31194fded880e2d8e602610afca0/controllers/api/user.go#L127)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

The code is going to look much more verbose if we remove the filter function in favor for one that would return the active ones directly from the AS, because we have join and respond methods. Being active or not can be seen as a variable, and when we will decide to add another one, like updated or not (or sorted, or....) we will need to add again all these methods again. That's why I'm more in favor of the filter functions.
Buuut, if we don't plan to add more variables to filter connections, we can do it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/188)*

**Comment by FR4NK-W** [comment]
Reviewed 5 of 5 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/188)*

**Pull request merged**
