### PR TITLE
Comment OpenVPN client.conf

### PR DESCRIPTION
**Pull request by FR4NK-W**
Added some comments to the OpenVPN client.conf template.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/93)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
We might want to also use the pinned dependencies in CI.
https://github.com/didip/tollbooth/commit/49a474e4248186bbc2db5cb28391ed23e7764007#diff-007503cfdd6314e37d40f96773bf2e05

**Comment by ercanucan** [comment]
:lgtm: @mlegner can you also have a look?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/93#-:-KxHlQ7eFserZyPFDbgU:b-3k4yx2)*

**Comment by mlegner** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/93#-:-KxI8zPD1KsupIQ-K3qC:bnfp4nl)*

**Comment by mlegner** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/93)*

**Pull request merged**
