### PR TITLE
Upgrade the machine to packages and nothing more

### PR DESCRIPTION
**Pull request by juagargi**
And remove the current upgrade mechanism.
This will be the last time to use scion-coord for the upgrade mechanism. In few weeks after the SCIONLab upgrade we will retire (archive) scion-coord.
Pending:
- [x] Remove remaining code in the `scion_upgrade_script.sh` once it's expressed somewhere else (Vagrantfile, etc).

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[scion_upgrade_script.sh, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LnmZbTj37VQzcT1fIzV:-LnmZbTk52FNyeuogdXe:becvf58) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L30)):*
> ```Shell
> 
> sudo systemctl disable scionupgrade.timer
> sudo systemctl disable scionupgrade.timer
> ```

The second line of this block should probably be `scionupgrade.service`.

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[scion_upgrade_script.sh, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LnmZbTj37VQzcT1fIzV:-Lnwr4xe4wzPiByYm-PK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L30)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The second line of this block should probably be `scionupgrade.service`.
</blockquote></details>

Done.

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scion_upgrade_script.sh, line 10 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogBYdK-If3zckzCLOA:-LogBYdK-If3zckzCLOB:b-ndut1l) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/8f8bf990f975a931e8b9813ab40796f57d4fb935/scion_upgrade_script.sh#L10)):*
> ```Shell
> # the first and only thing we do is install the packaging system and remove the old upgrade mechanism
> sudo apt-get install -y apt-transport-https
> echo "deb [trusted=yes] https://packages.netsec.inf.ethz.ch/debian all main" | sudo tee /etc/apt/sources.list
> ```

Doing `tee /etc/apt/sources.list` will fundamentally break existing OS as it will remove any other repository this file contains. Please consider the following `tee /etc/apt/sources.list.d/scionlab.list` - this way we will install additional repo without modifying the already existing file in the user's filesystem.

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scion_upgrade_script.sh, line 21 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogCa-q1zAN_dyx5cHZ:-LogCa-q1zAN_dyx5cH_:b-8b7d96) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/8f8bf990f975a931e8b9813ab40796f57d4fb935/scion_upgrade_script.sh#L21)):*
> ```Shell
> 
> sudo systemctl disable scion.service
> sudo systemctl stop scion.service
> ```

NIT: `systemctl disable --now` does the both in one call

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scion_upgrade_script.sh, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LnmZbTj37VQzcT1fIzV:-LogCuU-1GNlG9nFW_jk:b-s2jw0g) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L30)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For me there is still two times `scionupgrade.timer`? Glitch?

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scion_upgrade_script.sh, line 37 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogD9BIC72CeFGeym99:-LogD9BIC72CeFGeym9A:byw6sqw) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L37)):*
> ```Shell
> sudo systemctl stop scionupgrade.timer
> # and this will also kill this very process, so it's the last thing we do:
> sudo systemctl stop scionupgrade.service
> ```

One block above `rm ... .service` has been executed and here `systemctl stop ... .service` happens. Shouldn't the order be reversed?

**Review by mkowalski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @juagargi, @matzf, and @mkowalski)

___
*[scion_upgrade_script.sh, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LnmZbTj37VQzcT1fIzV:-LogE_wmDnk6O09BKURt:b-fnlxsu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L30)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

For me there is still two times `scionupgrade.timer`? Glitch?
</blockquote></details>

Yes glitch, at reviewable UI. LGTM
___
*[scion_upgrade_script.sh, line 25 at r7](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogEFRX6NgZAM9PowdJ:-LogEFRX6NgZAM9PowdK:b98vuhx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4135c98c67d56294500fa5912b8a377d1f9b1a92/scion_upgrade_script.sh#L25)):*
> ```Shell
> 
> sudo apt-get install -y apt-transport-https
> echo "deb [trusted=yes] https://packages.netsec.inf.ethz.ch/debian all main" | sudo tee -a /etc/apt/sources.list
> ```

The above is bullshit because reviewable showed me version without "tee -a". However the latter about writing to `/etc/apt/sources.list.d/scionlab.list/` instead the OS' default one is still something to consider.

**Review by mkowalski — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: all files reviewed, 3 unresolved discussions (waiting on @juagargi and @matzf)

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: all files reviewed, 3 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scion_upgrade_script.sh, line 37 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogD9BIC72CeFGeym99:-LogdznxEewRdnOiXbnK:bfsbgqp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L37)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

One block above `rm ... .service` has been executed and here `systemctl stop ... .service` happens. Shouldn't the order be reversed?
</blockquote></details>

which one?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matzf and @mkowalski)

___
*[scion_upgrade_script.sh, line 25 at r7](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LogEFRX6NgZAM9PowdJ:-LotX_K8DX_wNo4KczrR:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4135c98c67d56294500fa5912b8a377d1f9b1a92/scion_upgrade_script.sh#L25)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

The above is bullshit because reviewable showed me version without "tee -a". However the latter about writing to `/etc/apt/sources.list.d/scionlab.list/` instead the OS' default one is still something to consider.
</blockquote></details>

Done.

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @juagargi, @matzf, and @mkowalski)

___
*[scion_upgrade_script.sh, line 26 at r9](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LotrbIU23TrxRpmEcuS:-LotrbIU23TrxRpmEcuT:bedsuzc) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/02d9572df4618a3cc88b209b77a33cbcf8756bb4/scion_upgrade_script.sh#L26)):*
> ```Shell
> sudo apt-get install -y apt-transport-https
> echo "deb [trusted=yes] https://packages.netsec.inf.ethz.ch/debian all main" | sudo tee /etc/apt/sources.list.d/scionlab.list
> echo -e "`sudo  crontab -l`""\n`date -d '07:00 UTC' '+%M %H'` * * * apt-get update; apt-get install -y --only-upgrade scionlab" |sudo crontab
> ```

I'd consider here doing the following (https://serverfault.com/a/38645/147673)
* create a file `/etc/cron.daily/scionlab` (chmod 755)
* inside the file we do `#!/bin/sh \n apt-get install -y --only-upgrade scionlab`

In this way we
1) have an easy way to modify the script in the future whenever needed
2) do not touch system-wide user-editable files so we are sure we will never break an already existing user setup

We gain
* a unique time seed so we avoid peaks where all the clients in the network try to download the packages at exactly the same moment
* possibility for a user to control system-wide when his daily jobs are run

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matzf and @mkowalski)

___
*[scion_upgrade_script.sh, line 26 at r9](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LotrbIU23TrxRpmEcuS:-Lou90xH9kEU0BiZTDuQ:bw3k0wh) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/02d9572df4618a3cc88b209b77a33cbcf8756bb4/scion_upgrade_script.sh#L26)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

I'd consider here doing the following (https://serverfault.com/a/38645/147673)
* create a file `/etc/cron.daily/scionlab` (chmod 755)
* inside the file we do `#!/bin/sh \n apt-get install -y --only-upgrade scionlab`

In this way we
1) have an easy way to modify the script in the future whenever needed
2) do not touch system-wide user-editable files so we are sure we will never break an already existing user setup

We gain
* a unique time seed so we avoid peaks where all the clients in the network try to download the packages at exactly the same moment
* possibility for a user to control system-wide when his daily jobs are run
</blockquote></details>

When/if we remove the requirement of updating at 7:00UTC, I would go for `unattended-upgrades` instead. It is also based on cron daily, and seems to be the standard way to request packages updates.
For now we still need to update at 07:00UTC

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @juagargi, @matzf, and @mkowalski)

___
*[scion_upgrade_script.sh, line 26 at r9](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LotrbIU23TrxRpmEcuS:-LouCBM41J7Na9lVoreg:blt1vf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/02d9572df4618a3cc88b209b77a33cbcf8756bb4/scion_upgrade_script.sh#L26)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

When/if we remove the requirement of updating at 7:00UTC, I would go for `unattended-upgrades` instead. It is also based on cron daily, and seems to be the standard way to request packages updates.
For now we still need to update at 07:00UTC
</blockquote></details>

Agree. Done

**Review by mkowalski — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matzf and @mkowalski)

**Review by mkowalski — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matzf and @mkowalski)

___
*[scion_upgrade_script.sh, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-coord/322#-LnmZbTj37VQzcT1fIzV:-LoxqONQ8bVYH6Wyvtph:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4559becafb9a764406a6f01c0fa644a7f144fde8/scion_upgrade_script.sh#L30)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

Yes glitch, at reviewable UI. LGTM
</blockquote></details>

Done.

**Review by mkowalski — APPROVED** [review]
> Reviewed 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/322)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Pull request merged**
