### PR TITLE
Fixed vulnerability allowing users to access and modify other user's VMs

### PR DESCRIPTION
**Pull request by mlegner**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/98)

### CODE REVIEW

**Comment by ercanucan** [comment]
@mlegner made a pass. only minor comments.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/scion_lab.go, line 661 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98#-KxrVgIru3evDmvsZydA:-KxrVgIspXv_w9UpXKie:bh6l5vs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0955834344de39126968b4a3642de4d42dc0041f/controllers/api/scion_lab.go#L661)):*
> ```Go
> 	if err != nil {
> 		log.Printf("Error getting the user session: %v", err)
> 		s.Error500(err, w, r)
> ```

minor: should this be 500? or maybe 403? also, did you remove the return statement on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98#-:-KxrWkat4ugQzSZsk1jX:bc54uo7)*

**Comment by mlegner** [comment]
I fixed the issue you raised and also added an additional check.
I already squashed the commits, the PR is therefore ready to merge.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/scion_lab.go, line 661 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98#-KxrVgIru3evDmvsZydA:-KxryB9rLnP6CqMLkdrO:b2qeba3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0955834344de39126968b4a3642de4d42dc0041f/controllers/api/scion_lab.go#L661)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: should this be 500? or maybe 403? also, did you remove the return statement on purpose?
</blockquote></details>

Done. I changed this to a 403 and added another test checking whether the user has an active configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98#-:-KxryJ4gUvQbFRQFWjVJ:b-p9pjy6)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98#-:-KxxKFA3ShQzbHKDRzSv:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/98)*

**Comment by mlegner** [comment]
merged #98

**Pull request merged**
