### PR TITLE
Link to Grafana

### PR DESCRIPTION
**Pull request by juagargi**
Issue #198

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/200)

### CODE REVIEW

**Comment by hausheer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/200#-L8CUboakDyN6ipcAm1Y:-L8CUbobRgEraNFToFhJ:b-lhv03j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/49f9ea9e66e0200a525aa4d17c323e362dac06f5/public/partials/user.html#L6)):*
> ```HTML
>   <h3>Welcome to SCIONLab!</h3>
>   <h4>
>   <a target="_blank" href="https://prometheus.scionlab.org/d/UcSvf4giz/scionlab?orgId=1">Grafana Monitor</a>
> ```

looks good to me in principle, though I suggest to specify the URL in `development.conf.default` and only include the link here if it is specified in the config file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/200)*

**Comment by juagargi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/200#-L8CUboakDyN6ipcAm1Y:-L8CY_iIv7NGWS2rBOGs:b-cmsfoh) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/49f9ea9e66e0200a525aa4d17c323e362dac06f5/public/partials/user.html#L6)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

looks good to me in principle, though I suggest to specify the URL in `development.conf.default` and only include the link here if it is specified in the config file.
</blockquote></details>

Yes, it sounds better to be able to configure it. I don't know how to do it though. I'm going to ask Markus, he probably knows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/200)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/200#-:-L9p1SG-ATswl2AL9sXG:bnfp4nl)*

**Comment by juagargi** [comment]
Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 6 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/200#-L8CUboakDyN6ipcAm1Y:-L9pUBbm3V5brGLTQ6YU:bjwj6cf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/49f9ea9e66e0200a525aa4d17c323e362dac06f5/public/partials/user.html#L6)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Yes, it sounds better to be able to configure it. I don't know how to do it though. I'm going to ask Markus, he probably knows.
</blockquote></details>

I followed Markus' instructions and now we read the URL from the config file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/200)*

**Comment by mlegner** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 6 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/200#-L8CUboakDyN6ipcAm1Y:-L9pfTpXCHtrTR_i1uZf:b2nhktp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/49f9ea9e66e0200a525aa4d17c323e362dac06f5/public/partials/user.html#L6)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I followed Markus' instructions and now we read the URL from the config file.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/200)*

**Pull request merged**
