### PR TITLE
Fixes to upgrade user ASes

### PR DESCRIPTION
**Pull request by juagargi**
I tested my AS 1001 upgrading from scionlab to master, and I needed these fixes for it to work.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/194)

### CODE REVIEW

**Comment by juagargi** [comment]
Note: these are just fixes for the upgrade to complete successfully to master. They do not modify the systemd service out of its 24 hours.

**Comment by juagargi** [comment]
Now we have changed the systemd service. It runs every 12 hours, and also every day at 07:00 UTC. This allows us to synchronize a rollout for the whole scionlab.

**Comment by mlegner** [comment]
@juagargi Made a pass, only minor comments below.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[vagrant/scionupgrade.timer, line 5 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/194#-L86HdTA6iveLJDkaA5F:-L86HdTA6iveLJDkaA5G:bc754vg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9eade4ef896a3742a28e0dacdc47c7dbb1d20b82/vagrant/scionupgrade.timer#L5)):*
> ```
> 
> [Timer]
> OnCalendar=07:00:00 UTC   # activate timer every day at 07:00 UTC
> ```

What is the rationale behind 7am UTC? I would expect the impact to be smallest during the night, say 3am.

---

*[vagrant/scionupgrade.timer, line 6 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/194#-L86HpgW34IaXRExFwcW:-L86HpgW34IaXRExFwcX:b-pss0ly) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9eade4ef896a3742a28e0dacdc47c7dbb1d20b82/vagrant/scionupgrade.timer#L6)):*
> ```
> [Timer]
> OnCalendar=07:00:00 UTC   # activate timer every day at 07:00 UTC
> OnActiveSec=12h           # every 12 hours from the timer activation
> ```

If we already have the daily update, couldn't we remove this line?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/194#-:-L86IDWx9-ALkPt3p6c5:b-669ync)*

**Comment by juagargi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vagrant/scionupgrade.timer, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/194#-L86HdTA6iveLJDkaA5F:-L88F7frlAqOkq7fJNIV:btdgbcr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9eade4ef896a3742a28e0dacdc47c7dbb1d20b82/vagrant/scionupgrade.timer#L5)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

What is the rationale behind 7am UTC? I would expect the impact to be smallest during the night, say 3am.
</blockquote></details>

We would update during night time in Europe and the Americas. It would be morning time in Asia though.

---

*[vagrant/scionupgrade.timer, line 6 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/194#-L86HpgW34IaXRExFwcW:-L88FM8E7nfjIamYOB7t:b-h083ov) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9eade4ef896a3742a28e0dacdc47c7dbb1d20b82/vagrant/scionupgrade.timer#L6)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

If we already have the daily update, couldn't we remove this line?
</blockquote></details>

We would in fact have another timer which would run much more frequently, e.g. OnActiveSec=1h . We don't have it because checking for updates is a bit expensive right now.
We want to support frequent checking in case we need to roll back to a previous version. Since we don't want scionlab to be "broken" for a whole day, we would get the new version sooner this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/194)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/194)*

**Pull request merged**
