### PR TITLE
Upgrade infrastructure AS script

### PR DESCRIPTION
**Pull request by juagargi**
We'll run this script in every AS from our infrastructure, using ansible or similar client that issues commands via ssh.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/205)

### CODE REVIEW

**Comment by jonghoonkwon** [comment]
@juagargi, I reviewed the script and took a dry run. I made some comments below.
In overall, :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[upgrade_infrastructure.sh, line 6 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSao609DA75Nsm_u_:-LACSao609DA75Nsm_ua:b-5as4qt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L6)):*
> ```Shell
> 
> GITREPO="juan"
> GITBRANCH="stable_scionproto"
> ```

The `GITREPO` and `GITBRANCH` should be changed to the actual repo/branch name.
For all the infrastructure ASes, `GITREPO=origin` and `GITBRANCH=scionlab` should work.

---

*[upgrade_infrastructure.sh, line 23 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSvyu4FnMiBTOjFKv:-LACSvyu4FnMiBTOjFKw:b-c4jufm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L23)):*
> ```Shell
> 
> # check we can sudo. We have -e, will exit if not
> echo sci0nLab | sudo -S -v &>/dev/null && success=1 || success=0
> ```

We're not going to write down the sudo pw into the script.
Furthermore, I think we don't need a sudo privilege check to restart Scion.

---

*[upgrade_infrastructure.sh, line 74 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACbXLU9bnF5q1ieomq:-LACbXLU9bnF5q1ieomr:b-8003qy) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L74)):*
> ```Shell
>     # exit 1
> fi
> output=$(./supervisor/supervisor.sh reload 2>&1) && success=1 || success=0
> ```

Do we actually need to reload supervisor?
Running Scion after shutting down supervisor would do same thing here.

I would like to recommend to run zookeeper clean command instead reloading supervisor.
To do so, you can run the following command.
`tools/zkcleanslate --zk 127.0.0.1:2181`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-:-LACdgKG9vsrTpgmfyhZ:bd5zl8b)*

**Comment by jonghoonkwon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[upgrade_infrastructure.sh, line 53 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACkQX166ZcMEoGj_Qi:-LACkQX166ZcMEoGj_Qj:b-t6pzr7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L53)):*
> ```Shell
>     exit 1
> fi
> # git pull
> ```

As we discussed, we'd better to have a plan B for a case that the upgrade procedure fails.
One suggestion is to checkout a `scionlab_local_backup` branch before rebasing the `scionlab` branch,
so that we can simply rollback to current branch if something goes wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[upgrade_infrastructure.sh, line 6 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSao609DA75Nsm_u_:-LACoeox24kxNXDT36uJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L6)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

And also, it would be nice we can specify the branch name by giving an argument when we run the script, so that we can have more flexibility for the upgrade procedure.
</blockquote></details>

Done.

---

*[upgrade_infrastructure.sh, line 23 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSvyu4FnMiBTOjFKv:-LACpYai87kY0MBQlXc2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L23)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

We're not going to write down the sudo pw into the script.
Furthermore, I think we don't need a sudo privilege check to restart Scion.
</blockquote></details>

Done.

---

*[upgrade_infrastructure.sh, line 35 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACh_bg7HG0W4Q6G4sa:-LACu_r-Cd57bgFse0mA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L35)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

This line only checks if there is a conflict caused by the changes from user side while rebasing.
Even if the changes do not cause any conflict, it could be a potential error for the future Scion operation.
I think we need to run `git status` to check whether any of the tracked files is changed,
and should abort the upgrade in that event.
</blockquote></details>

Done.

---

*[upgrade_infrastructure.sh, line 53 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACkQX166ZcMEoGj_Qi:-LACrxZa8YgZhADzs6Y5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L53)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

As we discussed, we'd better to have a plan B for a case that the upgrade procedure fails.
One suggestion is to checkout a `scionlab_local_backup` branch before rebasing the `scionlab` branch,
so that we can simply rollback to current branch if something goes wrong.
</blockquote></details>

Done.

---

*[upgrade_infrastructure.sh, line 74 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACbXLU9bnF5q1ieomq:-LACsOMHDF0dXF6YAryS:b-xzcez5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L74)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Do we actually need to reload supervisor?
Running Scion after shutting down supervisor would do same thing here.

I would like to recommend to run zookeeper clean command instead reloading supervisor.
To do so, you can run the following command.
`tools/zkcleanslate --zk 127.0.0.1:2181`
</blockquote></details>

Done. We run now the zkcleanslate instead of the supervisor reload

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205)*

**Comment by jonghoonkwon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[upgrade_infrastructure.sh, line 23 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSvyu4FnMiBTOjFKv:-LADgW6f8LH9udR3qwuo:b5v68ur) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L23)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We need to get rid of this sudo check

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205)*

**Comment by juagargi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[upgrade_infrastructure.sh, line 23 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205#-LACSvyu4FnMiBTOjFKv:-LADk3wq9iXhgWoM65au:b-ikwynl) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f5d074daad652cbf885ce1d01913f1b5156f43/upgrade_infrastructure.sh#L23)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

We need to get rid of this sudo check
</blockquote></details>

I've fixed to not use -v and it seems to work now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/205)*

**Pull request merged**
