### PR TITLE
Add simple API to be called by an update script in SCIONLabASes

### PR DESCRIPTION
**Pull request by mlegner**
This PR adds two API endpoints to be queried by SCIONLabASes:
`queryUpdateBranch` provides the git branch that the AS should follow
`confirmUpdate` is called after a successful update of the code in the AS

This PR builds on PRs #159 and #161.
It also requires the AccountID and Secret to be provided to the AS in the update script.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/162)

### CODE REVIEW

**Comment by juagargi** [comment]
Reviewed 11 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/162)*

**Comment by juagargi** [comment]
LGTM. We would have to wait for PR #161 to be merged first.

**Comment by hausheer** [comment]
@xabarass Could you maybe help us with a review of this PR related to the update script?

**Comment by xabarass** [comment]
I've tested new API calls and they work as expected. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/162#-:-L5tr1mhq5RSzLqDj3jK:b-y0alrm)*

**Comment by mlegner** [comment]
Thank you for the reviews. I will merge the PR directly after #161.

**Pull request merged**
