### PR TITLE
Pre-approved registration and email invitations

### PR DESCRIPTION
**Pull request by mlegner**
This PR addresses issue #61, building onto PR #79.
It adds front- and backend to enable admins to send email invitations to other people.
Users receiving the invitations are already preapproved and do not need to go
through captcha or enter their personal information.
Implemented admin interface for sending email invitations.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/75)

### CODE REVIEW

**Comment by ercanucan** [comment]
@mlegner This is relatively large PR. Would it be possible to divide this PR into 2 or 3 separate PRs (separated into coherent topics such as refactoring, admin-page, implementation of invitations etc)?

**Comment by mlegner** [comment]
Yes, that makes sense. I will prepare two PRs: One setting up the back-end and models for the admin page and another one for the email invitations. The refactoring could be moved to the refactoring PR that you suggested anyway.

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-:-KvfO0sHrBKMoDHFiA1X:b-mgrikl)*

**Comment by mlegner** [comment]
@ercanucan I now split the commit into two and added a secont PR.

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-:-KvfX4tqDpLXWRG2YY98:b3ww41i)*

**Comment by ercanucan** [comment]
Review status: 0 of 27 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[controllers/api/admin.go, line 126 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwipXsphHURyt84Bxxt:-KwipXsphHURyt84Bxxu:b-imw93e) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/controllers/api/admin.go#L126)):*
> ```Go
> 	}
> 
> 	errorEmails := []string{}
> ```

Maybe this section could be a separate function.

---

*[controllers/api/register.go, line 57 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwipFqFHIhF2fpgj2C8:-KwipFqGEelFn0UKUjFG:be9rz1o) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/controllers/api/register.go#L57)):*
> ```Go
> func passwordsAreValid(password, passwordConfirmation string) error {
> 	if len(password) < 8 {
> ```

unnecessary white-space?

---

*[email/templates/invitation.html, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwiiqKbxptpk1kWF6Uf:-KwiiqKchw10I2UiPyCS:b-ve2qcu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/email/templates/invitation.html#L5)):*
> ```HTML
> SCION [1] is a revolutionary new architecture for the internet, which is designed to replace the existing architecture in the future.
> 
> {{.InvitorFirstName}} {{.InvitorLastName}} invites you to join the network and discover its numerous exciting features by signing up for your very own SCIONLab AS.
> ```

`Inviter`

---

*[public/js/controllers/admin.js, line 3 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-Kwio4vl4S3y6yV3wKdI:-Kwio4vmWU7uHLs-A1EW:b-as81u) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/public/js/controllers/admin.js#L3)):*
> ```JavaScript
> angular.module('scionApp')
>     .controller('adminCtrl', ['$rootScope', '$scope', 'adminService', '$location', '$window', '$http',
>         function ($rootScope, $scope, adminService, $location, $window, $http) {
> ```

Hmm, I have a feeling that this function is getting a bit too large now.  Would it be possible to divide it into smaller functions?

---

*[public/partials/admin.html, line 69 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-Kwinr8k9AGDhsfyQC4R:-Kwinr8k9AGDhsfyQC4S:b2cj8g9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/public/partials/admin.html#L69)):*
> ```HTML
>       </div>
>     </div>
>     
> ```

Do we need to have this commented code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75)*

**Comment by mlegner** [comment]
Review status: 0 of 27 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[controllers/api/admin.go, line 126 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwipXsphHURyt84Bxxt:-KwoX4yZ3MGmnok3QUSJ:b-komn9i) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/controllers/api/admin.go#L126)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Maybe this section could be a separate function.
</blockquote></details>

What would be the use to split this function? It does not seem very long to me anyway.

---

*[controllers/api/register.go, line 57 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwipFqFHIhF2fpgj2C8:-KwoWHpGTe53dhD0cYDp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/controllers/api/register.go#L57)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

unnecessary white-space?
</blockquote></details>

Done.

---

*[email/templates/invitation.html, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-KwiiqKbxptpk1kWF6Uf:-KwoWM-teN-PtEHAOF0q:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/email/templates/invitation.html#L5)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`Inviter`
</blockquote></details>

Done.

---

*[public/js/controllers/admin.js, line 3 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-Kwio4vl4S3y6yV3wKdI:-KwoWaHkI-g8Uh2B4IZv:bydgj4c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/public/js/controllers/admin.js#L3)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Hmm, I have a feeling that this function is getting a bit too large now.  Would it be possible to divide it into smaller functions?
</blockquote></details>

Do you mean to split the `adminCtrl` into multiple controllers? I don't think the controller is too large, as it is split into reasonably-sized parts.

---

*[public/partials/admin.html, line 69 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-Kwinr8k9AGDhsfyQC4R:-KwoX26mNsdeh7VrrLxR:b-g300zy) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c3c71e36d1b3d4640f0b251140689c3fec251d80/public/partials/admin.html#L69)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Do we need to have this commented code?
</blockquote></details>

No, I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 27 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75#-:-KxHmdaFR6p9TGVK6Gzo:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 12 of 21 files at r1, 11 of 15 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/75)*

**Pull request merged**
