### PR TITLE
Reflect changes to `Vagrantfile` in `README` and `run.sh`

### PR DESCRIPTION
**Pull request by mlegner**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/82)

### CODE REVIEW

**Comment by ercanucan** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vagrant/run.sh, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82#-KwiiJlibvKz03a_XtbL:-KwiiJlibvKz03a_XtbM:b-8oqb01) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b58d14273967ae918cfa5235d40df429aff3a21/vagrant/run.sh#L11)):*
> ```Shell
> run_vagrant() {
>     echo "[SCIONLabVM] run vagrant"
>     vagrant box add scion/ubuntu-16.04-64-scion
> ```

did you have a chance to test it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82#-:-Kwii7NlF1v00a80qwJF:bg7igkv)*

**Comment by ercanucan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82)*

**Comment by mlegner** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vagrant/run.sh, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82#-KwiiJlibvKz03a_XtbL:-KwnYEdTtfH6XkjPioZr:bveizct) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b58d14273967ae918cfa5235d40df429aff3a21/vagrant/run.sh#L11)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

did you have a chance to test it?
</blockquote></details>

Yes, I tested the commands on my system and everything worked well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/82#-:-KxHfE_yXuCPdnL7-PKU:bnfp4nl)*

**Comment by ercanucan** [comment]
please rebase

**Pull request merged**
