### PR TITLE
Debug mode for controlled error message verbosity

### PR DESCRIPTION
**Pull request by chaehni**
This PR introduces a new mechanism for controlling error output verbosity:

- A control function takes an error and a more generic error description as input and returns an error message based on a "debug mode" flag.
- Functions for error handling are adapted to make use of this in a way, such that new error handling automatically uses this mechanism as well.
- A problem with respect to error handling that lead to nil pointer exceptions in the past is resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/120)

### CODE REVIEW

**Comment by mlegner** [comment]
This implements issue #84.

**Comment by mlegner** [comment]
@chaehni I made a pass over the code, did not have time to test it yet, however.
I like the simple but effective setup. Some small comments are below.
One more general idea: In almost all ocurrences of these functions we also log the error. Would it maybe make sense to include this into the functions somehow?

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[config/config.go, line 42 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KzitZNNG4N6AqR01aHO:-KzitZNOxfGyrYgFrBMf:b-me2e2h) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/config/config.go#L42)):*
> ```Go
> 	SESSION_VERIFICATION_KEY = goconf.AppConf.String("session.verification_key")
> 	LOG_FILE                 = goconf.AppConf.String("log.file")
> 	LOG_DEBUG_MODE, _        = goconf.AppConf.Bool("log.debug_mode")
> ```

Could you also add this configuration option to the `development.conf.default`?

---

*[controllers/controller.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KziueT8ypa9w-xNn0z5:-KziueT8ypa9w-xNn0z6:bx6dvap) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/controller.go#L107)):*
> ```Go
> }
> 
> func (c HTTPController) Error500(w http.ResponseWriter, err error, desc string, a ...interface{}) {
> ```

We have quite some code duplication here. Would it maybe make sense to write a more generic function creating Error500, BadRequest, NotFound, and Forbidden?

---

*[controllers/api/as.go, line 155 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KzivLTSuWxgu6QwLM7N:-KzivLTSuWxgu6QwLM7O:b-xckvl0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/api/as.go#L155)):*
> ```Go
> 	if err := decoder.Decode(&request); err != nil {
> 		log.Printf("Error decoding JSON: %v, %v", r.Body, err)
> 		c.BadRequest(w, err, "Error decoding Json")
> ```

JSON would be more consistent with the rest. We could even think about defining a variable or a special BadRequest function for this as it is used in multiple different places.

---

*[controllers/api/as.go, line 317 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kzivwoh9-_ZAc1qWcSu:-Kzivwoh9-_ZAc1qWcSv:b-q8zk2n) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/api/as.go#L317)):*
> ```Go
> 		log.Printf("Error marshaling JSON for account: %v request: %v new AS: %v, %v",
> 			account, request.RequestId, joinReply.JoiningIA, err)
> 		c.Error500(w, err, "Error marshaling JSON")
> ```

Inconsistent with other marshaling errors

---

*[controllers/api/as.go, line 543 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw-bPODEpw82jpHd1:-Kziw-bPODEpw82jpHd2:b-skhwaf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/api/as.go#L543)):*
> ```Go
> 		log.Printf("Error during JSON Marshaling. Account: %v, ISD-AS: %v, %v", account, isdas,
> 			err)
> 		c.Error500(w, err, "Error during JSON Marshaling")
> ```

marshaling

---

*[controllers/api/as.go, line 596 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw0te1Sw5BlXt8_9p:-Kziw0te1Sw5BlXt8_9q:b-skhwaf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/api/as.go#L596)):*
> ```Go
> 		log.Printf("Error during JSON Marshaling. Account: %v, ISD-AS: %v, %v", account, req.IsdAs,
> 			err)
> 		c.Error500(w, err, "Error during JSON Marshaling")
> ```

marshaling

---

*[controllers/api/login.go, line 171 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw9Ncfegbl2472Yk6:-Kziw9Ncfegbl2472Yk7:bhgt8n6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d019b257d45e733a6dbb275ba3552edd620fd5ad/controllers/api/login.go#L171)):*
> ```Go
> 	} else {
> 		log.Println("Auth error")
> 		c.Forbidden(w, nil, "Auth error")
> ```

Authentication?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-KziwGkv9ZHySXemaM4a:bb55qms)*

**Comment by chaehni** [comment]
@mlegner Thank you very much for your feedback. This is a good idea. It would reduce logging and error output to a single line. Still, there are some ocurrences where we are not (currently) logging the error forwarded to the web interface. We might want to change this. I think it would not hurt to log HTTP errors in any case.
The drawbacks are that we can't have different error messages for logging and forwarding anymore and that we lose the ability to not log errors in specific places. Also, it might become not so obvious where errors are logged.

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[controllers/controller.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KziueT8ypa9w-xNn0z5:-KzxM51co8ZhvtnG_Ts5:b-ou9oj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/controller.go#L107)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We have quite some code duplication here. Would it maybe make sense to write a more generic function creating Error500, BadRequest, NotFound, and Forbidden?
</blockquote></details>

We could certainly have this. I think it's not enough code to move parts of it to a separate function. However, we could decide on the type of error based on a flag. But that adds another argument to the parameter list. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-KzxMrvdNJq77KJvKU8H:b-1lkjem)*

**Comment by chaehni** [comment]
I updated the PR, addressing the feedback.
It now contains a proposal of a generic HTTP error function which can be used with different error status codes and additionally logs the error.
The code is not yet updated to make use of this new function.

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[config/config.go, line 42 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KzitZNNG4N6AqR01aHO:-Kzy-RFr5h8SMhS4gIYG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/config/config.go#L42)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Could you also add this configuration option to the `development.conf.default`?
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 155 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KzivLTSuWxgu6QwLM7N:-Kzy-b-hSg9TlafoQx5M:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/api/as.go#L155)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

JSON would be more consistent with the rest. We could even think about defining a variable or a special BadRequest function for this as it is used in multiple different places.
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 317 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kzivwoh9-_ZAc1qWcSu:-Kzy0tTYwhXhtDWPDxTu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/api/as.go#L317)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Inconsistent with other marshaling errors
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 543 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw-bPODEpw82jpHd1:-Kzy01L9ktkUI8EmmG4N:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/api/as.go#L543)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

marshaling
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 596 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw0te1Sw5BlXt8_9p:-Kzy0iaA0CYY1HBFpxlS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/api/as.go#L596)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

marshaling
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 171 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-Kziw9Ncfegbl2472Yk6:-Kzy1516FA9itHCED1Ox:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/api/login.go#L171)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Authentication?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-Kzy88NJy0vasRttymIE:b-cwhiuk)*

**Comment by mlegner** [comment]
Thanks for the changes. I like the added function but we could keep all the code as it is for now. Maybe you could add a todo such that we don't forget thinking about if and where to use that function.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/controller.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KziueT8ypa9w-xNn0z5:-KzyDb9PMQHbcAM3lxdM:bi3sc6f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/controller.go#L107)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

We could certainly have this. I think it's not enough code to move parts of it to a separate function. However, we could decide on the type of error based on a flag. But that adds another argument to the parameter list. What do you think?
</blockquote></details>

I had in mind a function generator that can be called to create the four different functions like `BadRequest := MyFunctionGenerator(http.StatusBadRequest)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-KzyEErumqlHJBCehikm:be2ybby)*

**Comment by chaehni** [comment]
I added the TODO. If we are going to use this function throughout, we can get rid of the dedicated error functions.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/controller.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KziueT8ypa9w-xNn0z5:-L-89T9qssLs1xGmez3s:b-ljq9vr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/controller.go#L107)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I had in mind a function generator that can be called to create the four different functions like `BadRequest := MyFunctionGenerator(http.StatusBadRequest)`.
</blockquote></details>

Ah, I see. Do you think we still need this?
I'm not sure how this can be added, such that it is part of the output interface and without duplicating code again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-89ArcsPrjld2YDxUD:b-j6ojim)*

**Comment by chaehni** [comment]
I noticed a problem we have with this approach. There are cases where the web interface requires a specific error message to function properly. If we are in debug mode where the error is appended to the response date, the behaviour of the web interface changes.

**Comment by mlegner** [comment]
Hmm... You are right of course. 
As far as I remember the code, this is only relevant for the login. Maybe we could send an error code in addition to the message? Then we could even have the same message but different behavior depending on the error.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/controller.go, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-KziueT8ypa9w-xNn0z5:-L-VQJVNzgBG0G_cIGuh:b-6jgsch) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54990d53d176ccc7e31458f739410ffd5d18a79e/controllers/controller.go#L107)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Ah, I see. Do you think we still need this?
I'm not sure how this can be added, such that it is part of the output interface and without duplicating code again.
</blockquote></details>

OK. I don't think this is very important anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-VQ00rq9tuKzuAgGhf:bykr6q5)*

**Comment by chaehni** [comment]
Yes, this is only the case for the login.  This would work but the error code would need to be encoded in the response data. Alternatively we could use custom HTTP status codes. 

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-esL5LOB-bbS0uvekK:b-3ukz2y)*

**Comment by mlegner** [comment]
Both options sound reasonable to me with a slight preference for embedding the code into the response data.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-f4_tR9BxTBYGKwm2t:br1gd5)*

**Comment by chaehni** [comment]
I tried out different approaches:
- Using custom HTTP status code
- Writing additional  error information into a custom header
- Prepending a custom code in the response body
- Sending a JSON formatted error response containing a custom error code and the error message

The first two approaches break the HTTP principles by misusing status codes/headers for transporting the error when it should really be in the response body.
The last approach was not possible with the current error handling framework because the http.Error() function formats the output to plain text.
I now updated the Login function to simply prepend an custom code to the error description.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-hGnbFxPj1sUbjsMhO:b2kp3xn)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 4 of 10 files at r1, 2 of 3 files at r2, 2 of 4 files at r3, 1 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/120#-:-L-k1iox6ZeCszsn2oPO:bnfp4nl)*

**Pull request merged**
