### PR TITLE
Confirmation emails

### PR DESCRIPTION
**Pull request by mlegner**
This PR adds a mechanism to the Coordination Service which sends a confirmation email to users after their configuration has been updated.
On the admin page, the current state of the VM is displayed.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/65)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[controllers/api/login.go, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCILe17MIFFGYQKQJj:-KtCILe17MIFFGYQKQJk:bq7st9x) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L49)):*
> ```Go
> 	Secret       string
> 	VMStatus     string
> 	VMIp         string
> ```

I would follow the convention for initialisms: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
At the moment, not all our code is compliant with GoLang guidelines, but it would be good to follow the guidelines as much as we can.

---

*[controllers/api/login.go, line 50 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCIeM4miO_ckdkLNwZ:-KtCIeM4miO_ckdkLNw_:biz83g2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L50)):*
> ```Go
> 	VMStatus     string
> 	VMIp         string
> 	ShowIp       bool
> ```

Same here regarding initialisms.

---

*[controllers/api/login.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCJeAgZA4e5KddEkGX:-KtCJeAgZA4e5KddEkGY:b-y4vsw2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L73)):*
> ```Go
> 	vm, err := models.FindSCIONLabVMByUserEmail(userSession.Email)
> 
> 	var vmStatus string
> ```

Minor: Would it make sense to separate this out into a function, such as `populateVMStatus`?

---

*[controllers/api/scion_lab.go, line 575 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLCP_V2u7dKDnTEBb:-KtCLCP_V2u7dKDnTEBc:b-lg3cl2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L575)):*
> ```Go
> // Helper function which creates the email and server objects used to send
> // confirmation emails to users
> func sendConfirmationEmail(userEmail, action string) error {
> ```

I do not have strong feeling about this but maybe we could move this function into email library (`email.go`)?

---

*[controllers/api/scion_lab.go, line 581 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLOsgi6g8uDFfRQGw:-KtCLOsgi6g8uDFfRQGx:b-rnlpbs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L581)):*
> ```Go
> 	}
> 
> 	tmpl, err := template.ParseFiles("email/templates/status.html")
> ```

We can rename this file `vm_status.html`

---

*[controllers/api/scion_lab.go, line 612 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCMc_glwthBXmqqImX:-KtCMc_hy-qGlpWpNZYB:b-g8jo9b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L612)):*
> ```Go
> 	mail.From = config.EMAIL_FROM
> 	mail.To = []string{userEmail}
> 	mail.Subject = "[SCIONLab] Status update"
> ```

I think it would be nice if the email subject was a bit more informative regarding the action performed. It can have a text similar to the message.

---

*[email/templates/status.html, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLhl2_qHDNmj5Shan:-KtCLhl2_qHDNmj5Shao:bxzddzk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/email/templates/status.html#L6)):*
> ```HTML
> Please visit http://{{.HostAddress}}/#/admin for further details on the current status of your VM.
> 
> Best regards
> ```

I would put a comma after this line

---

*[email/templates/status.html, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLonkkE90omht7Vz9:-KtCLonkkE90omht7VzA:bt7uv9l) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/email/templates/status.html#L7)):*
> ```HTML
> 
> Best regards
> Your SCION Coordination Service
> ```

We can drop the word `Your` and just say `SCIONLab Coordination Service`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by chaehni** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 575 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLCP_V2u7dKDnTEBb:-KtCQqznpHIWdX4xNdjO:b-5k8ai9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L575)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I do not have strong feeling about this but maybe we could move this function into email library (`email.go`)?
</blockquote></details>

This might beneficial since the code is replicated in every place we send emails. I already implemented a somewhat generic function in the 'User Activation' PR. Maybe making it even more generic would be enough to make it work for your use case: https://github.com/chaehni/scion-coord/blob/user_activation/email/email.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[public/partials/admin.html, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCeRauWYSbRaX_ApzV:-KtCeRav-i1kdRfeo8fz:b-1h67lr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/public/partials/admin.html#L11)):*
> ```HTML
>   <p><b>Secret:</b> {{user.Secret}}</p>
>   <p></p>
>   <p>{{user.VMStatus}} <span ng-if="user.ShowIp">Your registered IP address is <b>{{user.VMIp}}</b>.</span></p>
> ```

I would make this status information stand out a little more. Currently it gets a little lost among the other text. For instance, it could be colored blue, possibly in a div element, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 567 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCg1LFFNLHH8OfNvMv:-KtCg1LFFNLHH8OfNvMw:b4l7giq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L567)):*
> ```Go
> 			if err := sendConfirmationEmail(vm_db.UserEmail, action); err != nil {
> 				log.Printf("Error sending email confirmation to user %v: %v", vm_db.UserEmail, err)
> 			}
> ```

Here we could have a log entry saying something like "Confirmation email was sent to user <user>".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by mlegner** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[controllers/api/login.go, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCILe17MIFFGYQKQJj:-KtFqzgvxEVN6diKG85N:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L49)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would follow the convention for initialisms: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
At the moment, not all our code is compliant with GoLang guidelines, but it would be good to follow the guidelines as much as we can.
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 50 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCIeM4miO_ckdkLNwZ:-KtFr-KrEZJaZniiActT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L50)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Same here regarding initialisms.
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCJeAgZA4e5KddEkGX:-KtFx_63ZWxPCWjsGVpf:b2o2po0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/login.go#L73)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Minor: Would it make sense to separate this out into a function, such as `populateVMStatus`?
</blockquote></details>

Done. Also separated the struct into user and vm information.

---

*[controllers/api/scion_lab.go, line 567 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCg1LFFNLHH8OfNvMv:-KtFzrsK9-ODiHg54TaQ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L567)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Here we could have a log entry saying something like "Confirmation email was sent to user <user>".
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 575 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLCP_V2u7dKDnTEBb:-KtFxdnnKLCJR1Iihs9m:b3xw7kj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L575)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

This might beneficial since the code is replicated in every place we send emails. I already implemented a somewhat generic function in the 'User Activation' PR. Maybe making it even more generic would be enough to make it work for your use case: https://github.com/chaehni/scion-coord/blob/user_activation/email/email.go
</blockquote></details>

I implemented a function based on the one by Claude. It accepts a single email and a interface to be used to fill the template. I adjusted both the confirmation and verification emails accordingly.

---

*[controllers/api/scion_lab.go, line 581 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLOsgi6g8uDFfRQGw:-KtFyhzOvR9SzUwfQajx:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L581)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

We can rename this file `vm_status.html`
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 612 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCMc_glwthBXmqqImX:-KtFzNTeL75NaEqg6yYG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/controllers/api/scion_lab.go#L612)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I think it would be nice if the email subject was a bit more informative regarding the action performed. It can have a text similar to the message.
</blockquote></details>

Done.

---

*[email/templates/status.html, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLhl2_qHDNmj5Shan:-KtFzzD8on8hjWNtMcMT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/email/templates/status.html#L6)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would put a comma after this line
</blockquote></details>

Done.

---

*[email/templates/status.html, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCLonkkE90omht7Vz9:-KtFzzWzivYUL2dGioOj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/email/templates/status.html#L7)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

We can drop the word `Your` and just say `SCIONLab Coordination Service`.
</blockquote></details>

Done.

---

*[public/partials/admin.html, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtCeRauWYSbRaX_ApzV:-KtG-0ZcY5TxJI6i8W0x:b-jb5n30) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/aa9bf2b5670c330f08a564eedfa03113785a5fd1/public/partials/admin.html#L11)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would make this status information stand out a little more. Currently it gets a little lost among the other text. For instance, it could be colored blue, possibly in a div element, etc.
</blockquote></details>

I added some "alert" classes, which makes important parts stand out more. I moved the "success" and "error" messages again below the buttons as it may become confusing with all the blocks otherwise.
Maybe it is a bit too colorful now, let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[controllers/api/login.go, line 67 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM-hW15BNnUHS_svNk:-KtM-hW15BNnUHS_svNl:b5qg0gg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/controllers/api/login.go#L67)):*
> ```Go
> 	vmInfo := vmInfo{}
> 
> 	vmInfo.ShowIP = false
> ```

Minor: You can declare and initialize this variable in one single line instead of two.

---

*[controllers/api/login.go, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM-XWvKpU6Nf4JYEhe:-KtM-XWw9-FY8v-RH2Kn:b-4fvxdm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/controllers/api/login.go#L68)):*
> ```Go
> 
> 	vmInfo.ShowIP = false
> 	if err != nil {
> ```

minor: I would put the error handling code right after the call is made.

---

*[email/email.go, line 63 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM1Cyb0vAvLQwFMCAU:-KtM1By5qPbBd-Jb0nNU:bed83rf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/email/email.go#L63)):*
> ```Go
> // their userEmail by filling in the specified template with the given subject
> // and information in the data object
> func ConstructAndSend(emailTemplate string, subject string, data interface{}, tag string, userEmail string) (err error) {
> ```

This line is too long. Our convention is to have max 100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[public/partials/admin.html, line 12 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM9Il-5GPBtvHteEuC:-KtM9Il-5GPBtvHteEuD:blrcgx3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/public/partials/admin.html#L12)):*
> ```HTML
>   <div class="alert alert-info"><p>{{vmInfo.VMText}} <span ng-if="vmInfo.ShowIP">Your registered IP address is <b>{{vmInfo.VMIP}}</b>.</span></p></div>
> 
>   <div class="alert alert-warning">
> ```

This looks good in general. The only thing which a bit distracting (and taking too much attention) is the orange box around this text. I think we should not make this an alert but rather normal text similar as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[public/js/controllers/admin.js, line 29 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM9qdJxD4yOB3VYZpa:-KtM9qdJxD4yOB3VYZpb:badaxkg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/public/js/controllers/admin.js#L29)):*
> ```JavaScript
>                     function(data) {
>                         console.log(data);
>                         window.location.assign('/api/as/downloads?filename=' + data["filename"]);
> ```

These changes requires that our existing users have to re-load the relevant JS files. Currently it's not a big problem, but in a next PR we may add some mechanism to force users' browsers' to re-load the JS files. This may be useful:
https://stackoverflow.com/questions/32414/how-can-i-force-clients-to-refresh-javascript-files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
@mlegner I gave some comments. I have tested it locally and the features worked fine.

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-:-KtMCzk_JaNuAZqdQuOA:b-t59gp9)*

**Comment by mlegner** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/login.go, line 67 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM-hW15BNnUHS_svNk:-KtMSALqBipfGsX5M7uk:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/controllers/api/login.go#L67)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Minor: You can declare and initialize this variable in one single line instead of two.
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM-XWvKpU6Nf4JYEhe:-KtMSBWc-V36nL5gtrSX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/controllers/api/login.go#L68)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: I would put the error handling code right after the call is made.
</blockquote></details>

Done.

---

*[email/email.go, line 63 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM1Cyb0vAvLQwFMCAU:-KtMSM9srp1RKFzVsV8W:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/email/email.go#L63)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

This line is too long. Our convention is to have max 100 chars.
</blockquote></details>

Done.

---

*[public/js/controllers/admin.js, line 29 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM9qdJxD4yOB3VYZpa:-KtMTePUux-48-tLTAvC:bmzwrl3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/public/js/controllers/admin.js#L29)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

These changes requires that our existing users have to re-load the relevant JS files. Currently it's not a big problem, but in a next PR we may add some mechanism to force users' browsers' to re-load the JS files. This may be useful:
https://stackoverflow.com/questions/32414/how-can-i-force-clients-to-refresh-javascript-files
</blockquote></details>

Good point, I will keep this in mind and put it onto my TODO-list.

---

*[public/partials/admin.html, line 12 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-KtM9Il-5GPBtvHteEuC:-KtMTbZ4EXA7Kee0a9Rl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6a68aecfa0572c2537d58ec29bb9a95231fd996f/public/partials/admin.html#L12)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

This looks good in general. The only thing which a bit distracting (and taking too much attention) is the orange box around this text. I think we should not make this an alert but rather normal text similar as before.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Comment by ercanucan** [comment]
:lgtm:

---

Reviewed 6 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65#-:-KtQSW4FGdp8P9mFb8kM:bnfp4nl)*

**Comment by ercanucan** [comment]
@chaehni Please resolve the "open discussions" on this PR if you agree that your comments are addressed.

**Comment by chaehni** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/65)*

**Pull request merged**
