### PR TITLE
API end-point to list available ASes.

### PR DESCRIPTION
**Pull request by ercanucan**
This PR adds a simple API end-point to list the available ASes to connect to. It
returns a list of ASes in the ISD which the querying AS belongs to. This
API end-point will be used by scion-web's simple installation mechanism to
display a drop-down menu containing available ASes.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/29)

### CODE REVIEW

**Comment by ercanucan** [comment]
@kormat @klausman

**Comment by klausman** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/as.go, line 576 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KidSImeKvAya4HP-Ldv:-KidSImeKvAya4HP-Ldw:b-xn789o) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f09a13a65a8831195656d899db4517762e14f626/controllers/api/as.go#L576)):*
> ```Go
> 	account, err := c.findAndValidateAccount(w, r, isdas)
> 	if err != nil {
> 		return
> ```

This should log that an error happened (and the error). Also, should it call something like `c.Error403()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29)*

**Comment by ercanucan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/as.go, line 576 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KidSImeKvAya4HP-Ldv:-Kij2THJqRbvEpKA_tEy:b55u3td) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f09a13a65a8831195656d899db4517762e14f626/controllers/api/as.go#L576)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should log that an error happened (and the error). Also, should it call something like `c.Error403()`?
</blockquote></details>

The logging and sending back the response takes place in the `findAndValidateAccount()` function. We had decided to abstract those out into this function as it get's called in a few places throughout the code. I added a comment to the code to reflect that. I have also tweaked the error code to 403 inside this function in case the validation was not successful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29)*

**Comment by ercanucan** [comment]
Thanks for the comments @klausman . Addressed.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-:-KijB1Fz4zyxH2yVzDzD:b-cypgcb)*

**Comment by ercanucan** [comment]
@klausman ping

**Comment by klausman** [comment]
:lgtm: from, please also poke @kormat 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-:-KjItAr0vNueNxSrN7kT:bl6x8th)*

**Comment by ercanucan** [comment]
@kormat ping

**Comment by kormat** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[controllers/api/as.go, line 550 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN5GBeFczjHLYZ5bYH:-KjN5GBeFczjHLYZ5bYI:b-3qzi5o) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L550)):*
> ```Go
> 
> // Converts the list of DB AS objects into a list of strings.
> // Adds all the ASes to the response except from the requesting AS itself.
> ```

I'm not convinced by filtering out the requesting AS. "List ASes" is a general function. It's trivial for a requester to do the filtering itself in any case, and if the requester's scion-web is running multiple ASes, then it will want to do more filtering than we can do here anyway.

---

*[controllers/api/as.go, line 552 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN4xYBYhJkPT8Q-OR2:-KjN4xYBYhJkPT8Q-OR3:b-ssfgmx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L552)):*
> ```Go
> // Adds all the ASes to the response except from the requesting AS itself.
> func (c *ASController) prepASListResponse(in []models.As, ownIA *addr.ISD_AS) []string {
> 	out := make([]string, 0)
> ```

Can be simplified to `var out []string`.

---

*[controllers/api/as.go, line 553 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN51x8KPfvbq94zBOE:-KjN51x9raMRbE00b-QR:b-6zhysr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L553)):*
> ```Go
> func (c *ASController) prepASListResponse(in []models.As, ownIA *addr.ISD_AS) []string {
> 	out := make([]string, 0)
> 	if in == nil || len(in) <= 1 {
> ```

`in` is a slice, even if it's nil, `len()` is defined to work on it (and return `0`), so the first test is redundant.

---

*[controllers/api/as.go, line 576 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN642OjWwG1DERKI3l:-KjN642OjWwG1DERKI3m:b17vtkt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L576)):*
> ```Go
> 		return
> 	}
> 	isdas := req.IsdAs
> ```

Why create a new variable for this? It looks like its never modified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29)*

**Comment by ercanucan** [comment]
@kormat addressed your feedback.

---

Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[controllers/api/as.go, line 550 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN5GBeFczjHLYZ5bYH:-KjbIoAgoYi8MBDKckOD:br2f38f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L550)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm not convinced by filtering out the requesting AS. "List ASes" is a general function. It's trivial for a requester to do the filtering itself in any case, and if the requester's scion-web is running multiple ASes, then it will want to do more filtering than we can do here anyway.
</blockquote></details>

Okay, done.

---

*[controllers/api/as.go, line 552 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN4xYBYhJkPT8Q-OR2:-KjbIoU-qvNA6veLYTQE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L552)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be simplified to `var out []string`.
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 553 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN51x8KPfvbq94zBOE:-KjbIoxCz_Gf-9CehCCf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L553)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`in` is a slice, even if it's nil, `len()` is defined to work on it (and return `0`), so the first test is redundant.
</blockquote></details>

Done.

---

*[controllers/api/as.go, line 576 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-KjN642OjWwG1DERKI3l:-KjbJrDE2fZ4ETheU0JZ:bp449bj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5ef584f27882ab78aa81640626b802d7bbd1a61f/controllers/api/as.go#L576)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why create a new variable for this? It looks like its never modified.
</blockquote></details>

Done. It was just to avoid doing `req.IsdAs` in a few places in the function. Got rid of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-:-KjbNvFEKI9DA9YHT2lL:biymtb0)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/29#-:-KjqWkfrpM2Y4uGEVMzf:bnfp4nl)*

**Comment by ercanucan** [comment]
thx! merging.

**Pull request merged**
