### PR TITLE
Image building service

### PR DESCRIPTION
**Pull request by xabarass**
Integrated service for generating IoT images to scion-coord.
This PR replaces #147 
Access token that is in commit is temporarily valid. I will reset it as soon as we finish testing and merge PR.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/204)

### CODE REVIEW

**Comment by chaehni** [comment]
Had a look at this.
Only minor/formatting comments.
Is the build server code available too?

---

Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---

*[conf/development.conf.default, line 99 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fp_O16wsMh2LDRLCm:-L9Fp_O16wsMh2LDRLCn:b-u0au5i) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/conf/development.conf.default#L99)):*
> ```
> img_builder.address = "https://vmtest.serber.club"
> img_builder.secret_token = "qSq9xa89F5V4BbqpRjBW7jvKSuVfrDfuQHGpLZRTE2eLRgun"
> img_builder.build_delay = 5
> ```

Missing newline at EOF

---

*[controllers/api/image_build.go, line 51 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GDZ_a7ogUS9s3Hepi:-L9GDZ_a7ogUS9s3Hepj:bpzk2qr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L51)):*
> ```Go
> 
> type jobStatus struct {
>     Exists bool   `json:"job_exists"`
> ```

How long does an image exist on the build server?

---

*[controllers/api/image_build.go, line 216 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G0hxh3vBFEf2A-vDp:-L9G0hxh3vBFEf2A-vDq:bm3v7c9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L216)):*
> ```Go
>     }
> 
>     // Start build job build job
> ```

"build job build job"

---

*[controllers/api/image_build.go, line 225 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G5kZ87oLhBviFG8SS:-L9G5kZ87oLhBviFG8ST:b-6ew5ky) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L225)):*
> ```Go
>     if err := startBuildJob(fileName, filePath, bRequest, buildJobs); err!=nil{
>         log.Println(err)
>         //TODO: Reset last build job time, rate limiting should not apply here
> ```

startBuildJob() never returns an error after updating the last build time. So this shouldn't be an issue.

---

*[controllers/api/image_build.go, line 230 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G0ytC0-7FfGzLLCEP:-L9G0ytC0-7FfGzLLCEQ:bqpxgf3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L230)):*
> ```Go
>     }
> 
>     message := "We started configuring image for your IoT device." +
> ```

I wouldn't omit the articles here since this is going out to the user:
".. **an** image for your IoT device."
"Please wait **a** few minutes for **the** build to finish."

---

*[controllers/api/image_build.go, line 261 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9FqogB0n0s3bM1CZRe:-L9FqogC4BSMS31mK8TA:bcnz9io) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L261)):*
> ```Go
> 
>     resp, err := httpClient.Do(req)
>     
> ```

Formatting issue. Please remove the superfluous spaces.

---

*[controllers/api/image_build.go, line 298 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fr-bi5qJqoxv-0T8p:-L9Fr-bi5qJqoxv-0T8q:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L298)):*
> ```Go
>         return
>     }
>     
> ```

Please remove the superfluous spaces.

---

*[controllers/api/image_build.go, line 312 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fr2aH3ZU9JcXIcz4M:-L9Fr2aH3ZU9JcXIcz4N:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L312)):*
> ```Go
>         }
>     }
>     
> ```

Please remove the superfluous spaces.

---

*[controllers/api/image_build.go, line 335 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fr5Gz89VtKYBj0a-K:-L9Fr5Gz89VtKYBj0a-L:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L335)):*
> ```Go
>         return false, false, err
>     }
>     
> ```

Please remove the superfluous spaces.

---

*[controllers/api/image_build.go, line 337 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fr87I33MsJOV3Yr5Y:-L9Fr87I33MsJOV3Yr5Z:brwi7y2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L337)):*
> ```Go
>     
>     return status.Exists, status.Finished, nil
> }
> ```

missing newline at EOF

---

*[public/js/controllers/user.js, line 59 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GGYtCC4bNypV94QdT:-L9GGYtCC4bNypV94QdU:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L59)):*
> ```JavaScript
>                             }
>                         }
>                     });  
> ```

Please remove the superfluous spaces.

---

*[public/js/controllers/user.js, line 69 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GBJSTC0K6mFv5RuoO:-L9GBJSTC0K6mFv5RuoP:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L69)):*
> ```JavaScript
>                         $scope.availableImages=data;
>                         $scope.imageNames={}
>                         
> ```

Please remove the superfluous spaces.

---

*[public/js/controllers/user.js, line 86 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GGiS65QK4WsgFzGln:-L9GGiS65QK4WsgFzGlo:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L86)):*
> ```JavaScript
>                             $location.path('/login');
>                         }
>                     });  
> ```

Please remove the superfluous spaces.

---

*[public/js/controllers/user.js, line 158 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GBMA28b2gqb1in74O:-L9GBMA28b2gqb1in74P:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L158)):*
> ```JavaScript
>                 $scope.error2 = "";
>                 $scope.message2 = "";
>                 
> ```

Please remove the superfluous spaces.

---

*[public/partials/user.html, line 142 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GGu6s-4A354F6BVuC:-L9GGu6s-4A354F6BVuD:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L142)):*
> ```HTML
>       <p>
>         This option allows you to generate prebuilt images for some of the most popular IoT devices that contains preinstalled SCION AS.
>         For this option to be enabled you must select option <strong>"Install on a dedicated SCION system"</strong>. 
> ```

Please remove the superfluous spaces.

---

*[public/partials/user.html, line 154 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GBSN-EJTxKai2-3lO:-L9GBSN-EJTxKai2-3lP:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L154)):*
> ```HTML
>         </select>
>       </div>
>       
> ```

Please remove the superfluous spaces.

---

*[public/partials/user.html, line 171 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GBVFr6NKjPpXLSGMQ:-L9GBVFr6NKjPpXLSGMR:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L171)):*
> ```HTML
>             <div id="buttongroup" ng-class="{true:'btn-group-vertical btn-block',
>               false:'btn-group btn-group-justified'}[isSmall]">
>       
> ```

Please remove the superfluous spaces.

---

*[public/partials/user.html, line 173 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GH3mX43TH1m2NdMPC:-L9GH3mX43TH1m2NdMPD:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L173)):*
> ```HTML
>       
>               <div ng-repeat="userImg in userImages" class="btn-group" role="group">
>                 <button ng-click="downloadImage(userImg)" class="btn btn-default" data-toggle="tooltip" 
> ```

Please remove the superfluous spaces.

---

*[public/partials/user.html, line 178 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GBXah213KXiVle4_Y:-L9GBXah213KXiVle4_Z:ba8028w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L178)):*
> ```HTML
>                 </button>
>               </div>
>       
> ```

Please remove the superfluous spaces.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9FrOSm9uGyVGldffVm:b-skzznt)*

**Comment by chaehni** [comment]
Review status: 4 of 7 files reviewed at latest revision, 19 unresolved discussions.

---

*[public/partials/user.html, line 141 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GIg705OlWsexTgVU8:-L9GIg705OlWsexTgVU9:bu1qhi6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L141)):*
> ```HTML
>       <h3>Create SCION image for IoT device</h3>
>       <p>
>         This option allows you to generate prebuilt images for some of the most popular IoT devices that contains preinstalled SCION AS.
> ```

"...that contain **a** preinstalled SCION AS.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by juagargi** [comment]
Some minor things plus two questions: 
- it seems that we can query the image creator using https://vmtest.serber.club/status , but once we restart the coordinator we loose the id and we don't have any way to recover the created images. Are there any plans for a future PR to change this?
- when testing, I never saw my image created. Using https://vmtest.serber.club/status I got:
[{"job_id":"zUJkCTuzfQRnzxUGq0vPouLJsKO3e0YdEGnvJxGVoEDQtZMAafC1JGUHALV7nQCT","job_exists":true,"build_finished":false},{"job_id":"a1cbezISwtMOBhRJ2rrNmoBkZBeZrIPYH3K0n0z6pzkCKrjbeISyhiCcsINWOHUe","job_exists":true,"build_finished":false}]
And I don't know which one was mine. I gave up checking after 1 hour. Is this expected? what's the waiting time?

---

Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[conf/development.conf.default, line 97 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Jor875bBAArydp5TQ:-L9Jor875bBAArydp5TR:b-8egnh4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/conf/development.conf.default#L97)):*
> ```
> 
> # For image service
> img_builder.address = "https://vmtest.serber.club"
> ```

What are we running as the image creator? is it part of our repos?

---

*[public/js/controllers/user.js, line 10 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9JxLBH6OB_uTemfF9n:-L9JxLBH6OB_uTemfF9o:b7qomp1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L10)):*
> ```JavaScript
>             $scope.message2 = "";
> 
>             $scope.isVmReady=true
> ```

Where is it used?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9KCEVY5l9GPx3mBxnu:b-ebdc9n)*

**Comment by xabarass** [comment]
Yes, for now all the data is lost when scion-coord is restarted. For now I haven't planned persisting that data on disk mainly for 2 reasons:
1. scion-coord shouldn't be restarted so often
2. Images on build server are kept for 10 minutes and deleted afterwords. Worst thing that can happen in case of `scion-coord` reboot is that user requests build of another image. For now I don't feel like it would be an issue, but if there is need, adding that functionality shouldn't be a problem :)

Second issue is interesting, I ran out of disk storage and I didn't implement error handling properly. I will create new issue for that. Also I cleaned up stuff from disk so it should be working now. 

Thanks for catching this :)

Build server source code is hosted in two projects: https://github.com/xabarass/rpi-img-builder and https://github.com/xabarass/image-builder 
If you have time we can have a short chat over weekend (this or any other) so I can explain how everything works together. For now it requires few manual steps, but I want to automate it, when I find time for that.

---

Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[controllers/api/image_build.go, line 51 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GDZ_a7ogUS9s3Hepi:-L9MDR07BD10r7i0PJHd:b-4kb76u) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L51)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

How long does an image exist on the build server?
</blockquote></details>

Currently, build service keeps image for 10 minutes. 

---

*[controllers/api/image_build.go, line 225 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G5kZ87oLhBviFG8SS:-L9MGA586gUTlt7hiZHJ:b3zmk4j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L225)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

startBuildJob() never returns an error after updating the last build time. So this shouldn't be an issue.
</blockquote></details>

Comment was out of date, I updated it. Basically problem is when `GenerateImage` function gets invoked concurrently (I think they can be executed in separate threads by framework?). 
Now lets say one user invokes service 10 times and execution of `GenerateImage` function for every thread checks `isRateLimited()` before any other thread has started executing `startBuildJob()` This will allow all functions to pass `isRateLimited()` and start 10 build jobs, which is not what we want. Basically there is potential race condition, but for now I don't think it will be a problem. I will fix it as follow up.

---

*[public/js/controllers/user.js, line 10 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9JxLBH6OB_uTemfF9n:-L9MJU92ELJi4QJ04ZO2:b-lkmz02) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/js/controllers/user.js#L10)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Where is it used?
</blockquote></details>

Nowhere, removed it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9M7GyPDN5B2xgOG8bx:b-vky69z)*

**Comment by xabarass** [comment]
Everything should be covered. 

---

Review status: 3 of 7 files reviewed at latest revision, 22 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9MLKt5-5w-SCw9u93d:b-r86qz4)*

**Comment by xabarass** [comment]
Review status: 3 of 7 files reviewed at latest revision, 22 unresolved discussions.

---

*[conf/development.conf.default, line 97 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Jor875bBAArydp5TQ:-L9MLtky7IwawIvXrzQQ:bvoc1s8) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/conf/development.conf.default#L97)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

What are we running as the image creator? is it part of our repos?
</blockquote></details>

Ye, I added answer in comments above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by chaehni** [comment]
Thanks for addressing the feedback. I'm looking forward to this being merged. 

---

Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[controllers/api/image_build.go, line 225 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G5kZ87oLhBviFG8SS:-L9U931c9ARRlVhC7lDA:b-5mhp7h) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L225)):*
<details><summary><i>Previously, xabarass (Milan Pandurov) wrote…</i></summary><blockquote>

Comment was out of date, I updated it. Basically problem is when `GenerateImage` function gets invoked concurrently (I think they can be executed in separate threads by framework?). 
Now lets say one user invokes service 10 times and execution of `GenerateImage` function for every thread checks `isRateLimited()` before any other thread has started executing `startBuildJob()` This will allow all functions to pass `isRateLimited()` and start 10 build jobs, which is not what we want. Basically there is potential race condition, but for now I don't think it will be a problem. I will fix it as follow up.
</blockquote></details>

I see. However, if we update the time in `isRateLimited()` then the old comment will apply again. We need to roll back the updated time in case `startBuildJob()` fails.

---

*[public/js/controllers/user.js, line 157 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9U2GvzDZCKAgHmuY0A:-L9U2GvzDZCKAgHmuY0B:b-treadf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/98b4d6e29b0d684569892fd031d3b0a6d0bfb125/public/js/controllers/user.js#L157)):*
> ```JavaScript
>                 $scope.message2 = "";
> 
>                 window.location.assign(userImage.download_link);                  
> ```

Some more spaces.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9UAGf73haYjg554r_Y:bgll7ro)*

**Comment by xabarass** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/image_build.go, line 225 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9G5kZ87oLhBviFG8SS:-L9UN8mTCZRkjHz0QitW:b-5c2nyl) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/controllers/api/image_build.go#L225)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I see. However, if we update the time in `isRateLimited()` then the old comment will apply again. We need to roll back the updated time in case `startBuildJob()` fails.
</blockquote></details>

Yes, also I will have to change `isRateLimited()` name to something more descriptive in that case

---

*[public/js/controllers/user.js, line 157 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9U2GvzDZCKAgHmuY0A:-L9UhAzV9tj481TNELJ6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/98b4d6e29b0d684569892fd031d3b0a6d0bfb125/public/js/controllers/user.js#L157)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Some more spaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by chaehni** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by juagargi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9eyt86AF7AU7d5SMhs:bnfp4nl)*

**Comment by juagargi** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by xabarass** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[conf/development.conf.default, line 99 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9Fp_O16wsMh2LDRLCm:-L9flKI4BttZdjgPVoW9:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/conf/development.conf.default#L99)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Missing newline at EOF
</blockquote></details>

Done.

---

*[public/partials/user.html, line 141 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-L9GIg705OlWsexTgVU8:-L9flgQpBczjvdOwQZrW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/3ee679b03aa36d6e85f926094be8f89bef67a8ee/public/partials/user.html#L141)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

"...that contain **a** preinstalled SCION AS.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Comment by juagargi** [comment]
Okay, I'm going to test the Odroid and maybe the Pi3 images at home.
Also, we should wait until we have done the first upgrade to merge this PR to master, because this way we can upgrade without caring about existing Arm devices automatically updating already.
For the second upgrade we will have to take them into account.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9u8iUGEexOTv82jCyY:b-taojt3)*

**Comment by juagargi** [comment]
Alright, finally finished the tests. Everything seems to be fine after the initial reboots the machine needs.
Burning the image itself became a bit complicated because of issues with the card and my reader. We might want to provide some info in the tutorials.
Just waiting until we upgrade our boxes and we should be good to merge the PR. Thanks!!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/204#-:-L9yEea91K5dbJo0Rc8a:b8d5kn6)*

**Comment by juagargi** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/204)*

**Pull request merged**
