### PR TITLE
WIP vagrant configuration for SCIONLabVM

### PR DESCRIPTION
**Pull request by jonghoonkwon**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/35)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[vagrant/README, line 10 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHqKDr3elSYivKVLP:-KqbHqKDr3elSYivKVLQ:bga7ows) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L10)):*
> ```
> ### For Ubuntu, OS X Users:
> 
> The shell script 'run.sh' will automatically check your system and install all the
> ```

we can drop the `all`

---

*[vagrant/README, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHjfKsXAF-XcWEymn:-KqbHjfKsXAF-XcWEymo:b-vx7wgi) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L16)):*
> ```
> Please Note: SCIONLabVM requires 'vagrant 1.9.7', 'virtualbox 5.0.4' or above.
> SCIONLabVM also requires that your host machine has a public IP address and can
> receive UDP traffic at port 50000.
> ```

`on port 50000` instead of `at port 50000`

---

*[vagrant/README, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHwnqxmk_iPZ89byV:-KqbHwnqxmk_iPZ89byW:bumrap) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L23)):*
> ```
> 
> If you agree with these requirements, you can then simply setup your SCIONLabVM via:
> './run.sh' inside the downloaded folder.
> ```

`from inside the downloaded folder`

---

*[vagrant/README, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbI12g9jGjtPnRseCH:-KqbI12g9jGjtPnRseCI:b-wptehp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L25)):*
> ```
> './run.sh' inside the downloaded folder.
> 
> Once the setup is finished, you will automatically be inside the SCIONLabVM via
> ```

let's use `through` instead of `via`

---

*[vagrant/README, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbI7Yo33kbRHNY9U7d:-KqbI7Yo33kbRHNY9U7e:bejyenr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L26)):*
> ```
> 
> Once the setup is finished, you will automatically be inside the SCIONLabVM via
> SSH. After this step, you are ready to run SCION as follows:
> ```

`you will be ready` instead of `you are ready`

---

*[vagrant/README, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbID4QBy9aGrehQ11d:-KqbID4QBy9aGrehQ11e:b-c1pbfi) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L38)):*
> ```
> 
> SCIONLabVM requires 'virtualbox' and 'vagrant'.
> First, You need to download and install the 'virtualbox' from:
> ```

The word `you` should start with lower-case.

---

*[vagrant/README, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIOy-7entuA4rBWcq:-KqbIOy-7entuA4rBWcr:b-nyzbyx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L45)):*
> ```
> 
> Afterwards, open a terminal window and go to the SCIONLabVM folder where the
> 'Vagrantfile' is located in. Now, you can run `vagrant up`. The command will
> ```

drop `in`

---

*[vagrant/README, line 62 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIXWZFhgniuguRPpf:-KqbIXW_YLsuJ_ZPl6HA:b451zhs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L62)):*
> ```
> ## Stopping and Restarting the VM
> 
> You can stop and restart 'SCIONLabVM' via 'vagrant' commands.
> ```

`using` instead of `via`

---

*[vagrant/run.sh, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIqHtjzrWTWYDiRcI:-KqbIqHuyhpY70PZR_3y:b-h9unn7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/run.sh#L13)):*
> ```Shell
> 	vagrant box update
> 	vagrant up
> 	vagrant ssh
> ```

Please be consistent with using white-spaces throughout the file. Either tabs or spaces. I would prefer spaces. Right now it is a mixture of both. 

---

*[vagrant/Vagrantfile, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbJkSGlyWh3XfZKNsB:-KqbJkSHAJ6JZqZHeOUI:b-vxy46o) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/Vagrantfile#L6)):*
> ```Ruby
> 
> Vagrant.configure(2) do |config|
> 	$setup_scion = <<-SCRIPT
> ```

Please use spaces. Also, looking at the main scion code-base, the Vagrant files seems to be indented by 2 spaces (not 4). Would be good to be consistent with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35)*

**Comment by jonghoonkwon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[vagrant/README, line 10 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHqKDr3elSYivKVLP:-Kqc4u7ctmT2l-sESzR5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L10)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

we can drop the `all`
</blockquote></details>

Done.

---

*[vagrant/README, line 16 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHjfKsXAF-XcWEymn:-Kqc4uZEOzIUj4rnYW0-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`on port 50000` instead of `at port 50000`
</blockquote></details>

Done.

---

*[vagrant/README, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbHwnqxmk_iPZ89byV:-Kqc53_888v0c3VjAs-V:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L23)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`from inside the downloaded folder`
</blockquote></details>

Done.

---

*[vagrant/README, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbI12g9jGjtPnRseCH:-Kqc59pw3L4FwBobxfWF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L25)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

let's use `through` instead of `via`
</blockquote></details>

Done.

---

*[vagrant/README, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbI7Yo33kbRHNY9U7d:-Kqc5ahSNfL1KiFOBIF3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L26)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`you will be ready` instead of `you are ready`
</blockquote></details>

Done.

---

*[vagrant/README, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbID4QBy9aGrehQ11d:-Kqc5eDH1D_Nx4yooY-N:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L38)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

The word `you` should start with lower-case.
</blockquote></details>

Done.

---

*[vagrant/README, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIOy-7entuA4rBWcq:-Kqc5iafMmkOGo3LEgob:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L45)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

drop `in`
</blockquote></details>

Done.

---

*[vagrant/README, line 62 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIXWZFhgniuguRPpf:-Kqc5ndE4YcLjKEe_Rsi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/README#L62)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`using` instead of `via`
</blockquote></details>

Done.

---

*[vagrant/run.sh, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbIqHtjzrWTWYDiRcI:-Kqc6tyB3SglQV7fhBBg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/run.sh#L13)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please be consistent with using white-spaces throughout the file. Either tabs or spaces. I would prefer spaces. Right now it is a mixture of both. 
</blockquote></details>

Done.

---

*[vagrant/Vagrantfile, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-KqbJkSGlyWh3XfZKNsB:-Kqc6SCiQ8nZC_-wBZTh:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0ec5a85ab21d92f79ab58c4bb25bea079804a5fc/vagrant/Vagrantfile#L6)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please use spaces. Also, looking at the main scion code-base, the Vagrant files seems to be indented by 2 spaces (not 4). Would be good to be consistent with that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35)*

**Comment by ercanucan** [comment]
:lgtm: please squash the commits.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35#-:-KrVaHA6P0lc-m4Sit53:bvaixaz)*

**Comment by ercanucan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/35)*

**Comment by jonghoonkwon** [comment]
@ercanucan: Initial work for the vagrant configuration is merged now. Further changes would appear in different PRs.

**Pull request merged**
