### PR TITLE
Bugfix: Panic when calling `getUpdatesForAP` with non-existent IA

### PR DESCRIPTION
**Pull request by mlegner**
This PR addresses issue #168.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/169)

### CODE REVIEW

**Comment by hausheer** [comment]
Thanks Markus, I tested this. Now, when providing a AS that doesn't exist I get the following message:

Error looking up connections for AS 1-11: <QuerySeter> no row found
http: multiple response.WriteHeader calls

Is this the expected?

**Comment by mlegner** [comment]
I fixed the "no row" error. The "multiple response.WriteHeader" error is already fixed by PR #167.

**Comment by hausheer** [comment]
This works for me now, but I haven't been able to look through the code in detail. Perhaps @FR4NK-W or @chaehni can quickly take a look?

**Comment by juagargi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/169#-:-L6Wjd23YL883w8XaUOu:bnfp4nl)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/169)*

**Pull request merged**
