### PR TITLE
Upgrade mechanism

### PR DESCRIPTION
**Pull request by xabarass**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/166)

### CODE REVIEW

**Comment by juagargi** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[scion_upgrade_script.sh, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-L5sf8UjOzcFCBAsDd-s:-L5sf8UjOzcFCBAsDd-t:byd3wlf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/51a8b2afedf9360622af388c649da7186cfbc170/scion_upgrade_script.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

When is scion_upgrade_script.sh called? and what is it for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166)*

**Comment by juagargi** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166)*

**Comment by juagargi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-:-L5slWqTHq8WNOekGuWd:bnfp4nl)*

**Comment by xabarass** [comment]
This upgrade is based on #162 
It is still necessary to update URLs for scion upgrade and install script when this gets merged with master branch.

**Comment by xabarass** [comment]
Review status: 3 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[scion_upgrade_script.sh, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-L5sf8UjOzcFCBAsDd-s:-L5udZtR4YAFSKX50hpi:b-4rhq0m) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/51a8b2afedf9360622af388c649da7186cfbc170/scion_upgrade_script.sh#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

When is scion_upgrade_script.sh called? and what is it for?
</blockquote></details>

This script is going to be downloaded and executed by `vagrant/scionupgrade.sh` Temporarily that script contains url to my gist so we can test the system. That will be changed as soon as we merge this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166)*

**Comment by xabarass** [comment]
Update is organized in two levels, `vagrant/scionupgrade.sh` is being run as part of systemd service on every boot, and every 24h after that. Only purpose of that script is to download the newest version of `scion_upgrade_script.sh` from this repository and execute it. 
`scion_upgrade_script.sh` is responsible for doing the actual update, (it is not implemented in this PR). This two level update procedure will allow us 2 things.
- More flexibility when doing update. We can fix bugs and add features to update script after systems are deployed. We don't need to commit to a fixed update mechanism.
- Speed up current release as we don't have to implement and test complete update functionality as it will be implemented later.

This PR extends gen directory content by 3 new files `account_id`, `account_secret` and `ia`. These files are needed to authenticate device with scion-coord.

**Comment by juagargi** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166)*

**Comment by juagargi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-:-L5xhfhcDJI9ztAg3UA-:bnfp4nl)*

**Comment by mlegner** [comment]
:lgtm: I just had a quick look and fixed some minor formatting issues. From my point of view, this can be merged.
Just one question: When do you intend to change the link in `vagrant/scionupgrade.sh` and to what?

---

Reviewed 1 of 5 files at r1, 1 of 15 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scion_upgrade_script.sh, line 8 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-L5yXhtVGWSGe-vdSh7b:-L5yXhtVGWSGe-vdSh7c:b-snylac) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b9db556522d5fec79a612ec683f378ff1d5c1704/scion_upgrade_script.sh#L8)):*
> ```Shell
> 
> echo "Invoking update script with $ACCOUNT_ID $ACCOUNT_SECRET $IA"
> echo "TODO, Implement me!"
> ```

Trailing linebreak missing.

---

*[vagrant/scionupgrade.service, line 17 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-L5yXm4sOgaZGUmkzXzt:-L5yXm4sOgaZGUmkzXzu:b-snylac) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b9db556522d5fec79a612ec683f378ff1d5c1704/vagrant/scionupgrade.service#L17)):*
> ```
> 
> [Install]
> WantedBy=multi-user.target
> ```

Trailing linebreak missing.

---

*[vagrant/scionupgrade.timer, line 8 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-L5yXmrzU5itZc5za-GH:-L5yXmrzU5itZc5za-GI:b-snylac) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b9db556522d5fec79a612ec683f378ff1d5c1704/vagrant/scionupgrade.timer#L8)):*
> ```
> 
> [Install]
> WantedBy=multi-user.target
> ```

Trailing linebreak missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-:-L5ybWmP8KbpdW4i6-Bb:bcqqytr)*

**Comment by xabarass** [comment]
Idea is to change mentioned URL when this PR gets merged to `https://raw.githubusercontent.com/netsec-ethz/scion-coord/master/scion_upgrade_script.sh` Complete upgrade process will be implemented in that file (now its just a placeholder)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-:-L5ywM5JYOJufbT_FASW:by8gw40)*

**Comment by mlegner** [comment]
OK, i just changed that line, it can be merged.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/166#-:-L60vuicoiqbwMcnb1Eg:b-of7xr7)*

**Pull request merged**
