### PR TITLE
Improvements to user interface

### PR DESCRIPTION
**Pull request by mlegner**
Dynamic configuration of buttons including tooltips for disabled ones.
Button that allows to (re-)download VM configuration.
Dismissible alert boxes.
Added SCION favicon.
VM instructions added to the VM README for users of non-Ubuntu distributions.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/69)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[controllers/api/login.go, line 57 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVVEchT6WzhxLXcgXB:-KtVVEchT6WzhxLXcgXC:b-8rcdju) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L57)):*
> ```Go
> }
> 
> type buttonConfiguration struct {
> ```

It seems pretty self explanatory already but still would be nice to have brief comments about the struct (and possibly some fields inside, if necessary).

---

*[controllers/api/login.go, line 65 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVWAbpRXb59w_7tBMf:-KtVWAbqtVCUNiRLBold:b-g28zxb) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L65)):*
> ```Go
> 	UpdateText      string
> 	RemoveTooltip   string
> 	DownloadTooltip string
> ```

I do not have strong feelings about this but how about having a more generic `buttonConfiguration` or `buttonStatus` struct? Then you instantiate one for each of the buttons and set their remove, download, tooltip etc. With your current implementation, whenever we add a new button to the panel, you will need to add three new fields to this struct. It can very quickly become difficult to maintain.

---

*[controllers/api/login.go, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVVTobSHsCyQLG2Tvq:-KtVVTobSHsCyQLG2Tvr:b-x196zk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L74)):*
> ```Go
> }
> 
> func populateVMStatusButtons(userEmail string) (vmInfo, buttonConfiguration, error) {
> ```

similar about the functions re: comments.

---

*[controllers/api/scion_lab.go, line 158 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVX1xOtwvdonqvyaF7:-KtVX1xP5FDw_UuDRuRP:bqyk7ht) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/46e304874626c6edca5256fb348161f622358d86/controllers/api/scion_lab.go#L158)):*
> ```Go
> 		return
> 	}
> 	log.Printf(string(b))
> ```

Did you remove the log statement on purpose?

---

*[public/js/controllers/user.js, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVZJcucrbq03TZnjld:-KtVZJcucrbq03TZnjle:bxhh70i) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L28)):*
> ```JavaScript
> 
>                 userService.generateSCIONLabVM(user).then(
>                     function (data) {
> ```

I see additional white-spaces. Were these on purpose? If this is the coding-style, I am fine with keeping them and adapting the rest of the code accordingly (maybe in another PR).

---

*[public/js/controllers/user.js, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVYkkHU90Z7a_BWWXf:-KtVYkkIQVHLss8h8H4i:bi515u2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L43)):*
> ```JavaScript
>                 $scope.message = "";
> 
>                 window.location.assign('/api/as/downloads?filename=' + user["Email"] + '.tar.gz');
> ```

This line is almost a duplicate to what we have in `generateSCIONLabVM`. The disadvantage is that if one day in the future we change the API to downloads, then we will need to adapt it in two places. Making a small helper function which takes the file name as a parameter may be a cleaner solution.

---

*[public/js/controllers/user.js, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVXknOdj32JhQdeoYD:-KtVXknOdj32JhQdeoYE:bl1ae2x) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L74)):*
> ```JavaScript
>                 },
>                 function (value) {
>                     $scope.isSmall = $window.innerWidth < 992;
> ```

Minor: Why this value (992)? It seems like a magic number at the moment. Might be good to make this a parameter. 

---

*[public/js/controllers/user.js, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVZjKZZeYGOo9TIloP:-KtVZjKZZeYGOo9TIloQ:b61be4u) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L85)):*
> ```JavaScript
>             $scope.me();
>         }
>     ]);
> ```

missing new line at the end of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Comment by ercanucan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[controllers/api/login.go, line 157 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVaEPsjYr8M1BFsX8b:-KtVaEPtynl8HeKzmjhO:b-4gnc0i) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L157)):*
> ```Go
> 	}
> 	vmInfo, buttonConfig, err := populateVMStatusButtons(userSession.Email)
> 	if err != nil {
> ```

Logging the error would be useful. Either in the caller or the callee. At the moment, it seems like this error would never be logged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Comment by ercanucan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 10 unresolved discussions.

---

*[controllers/api/login.go, line 50 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVchqUvzqI_yL7Qqir:-KtVchqVqcKbfp9WzBIC:b-sdjpr4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L50)):*
> ```Go
> }
> 
> type vmInfo struct {
> ```

Actually, thinking about this further, the structs such as `vmInfo, buttonConfiguration, meData` etc. are all related to UI functionality right? If we keep adding more of these classes, we can move all that logic to a separate file or a library (possibly in a future PR). Then we would have a clear distinction between UI elements and the actual login API code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Comment by mlegner** [comment]
Review status: 0 of 11 files reviewed at latest revision, 10 unresolved discussions.

---

*[controllers/api/login.go, line 50 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVchqUvzqI_yL7Qqir:-KtW7DYt7c2ekDuwo2Kg:b-4fljeu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L50)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Actually, thinking about this further, the structs such as `vmInfo, buttonConfiguration, meData` etc. are all related to UI functionality right? If we keep adding more of these classes, we can move all that logic to a separate file or a library (possibly in a future PR). Then we would have a clear distinction between UI elements and the actual login API code.
</blockquote></details>

Good point. For now, I moved this part to a new `user.go`, as all of this is only related to the user page but not the login.

---

*[controllers/api/login.go, line 57 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVVEchT6WzhxLXcgXB:-KtW7LwQiR4JMZcpWdao:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L57)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

It seems pretty self explanatory already but still would be nice to have brief comments about the struct (and possibly some fields inside, if necessary).
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 65 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVWAbpRXb59w_7tBMf:-KtW7OhT_PB41CkP5ZHs:b6k6d8s) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L65)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I do not have strong feelings about this but how about having a more generic `buttonConfiguration` or `buttonStatus` struct? Then you instantiate one for each of the buttons and set their remove, download, tooltip etc. With your current implementation, whenever we add a new button to the panel, you will need to add three new fields to this struct. It can very quickly become difficult to maintain.
</blockquote></details>

Done. Also changed the HTML to make use of `ng-repeat` which makes it easier to add/change buttons.

---

*[controllers/api/login.go, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVVTobSHsCyQLG2Tvq:-KtW7r57764UNks87mqF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L74)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

similar about the functions re: comments.
</blockquote></details>

Done.

---

*[controllers/api/login.go, line 157 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVaEPsjYr8M1BFsX8b:-KtW88WKKMMODysMG8I4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/controllers/api/login.go#L157)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Logging the error would be useful. Either in the caller or the callee. At the moment, it seems like this error would never be logged.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 158 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVX1xOtwvdonqvyaF7:-KtW8ndJqzzxL2DlfEFD:b-7qlc9y) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/46e304874626c6edca5256fb348161f622358d86/controllers/api/scion_lab.go#L158)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Did you remove the log statement on purpose?
</blockquote></details>

I accidentally added this in a previous PR and removed it again now.

---

*[public/js/controllers/user.js, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVZJcucrbq03TZnjld:-KtW8trFQzvYfZ4dBaVc:b-whrskm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L28)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I see additional white-spaces. Were these on purpose? If this is the coding-style, I am fine with keeping them and adapting the rest of the code accordingly (maybe in another PR).
</blockquote></details>

Aparently this is the "official" coding style: Have whitespace after anonymous functions, but none after named functions: http://javascript.crockford.com/code.html#variable%20declarations
I have changed the other js files accordingly.

---

*[public/js/controllers/user.js, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVYkkHU90Z7a_BWWXf:-KtWD0gMXeI1gB6Dzu8y:b-77dted) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L43)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

This line is almost a duplicate to what we have in `generateSCIONLabVM`. The disadvantage is that if one day in the future we change the API to downloads, then we will need to adapt it in two places. Making a small helper function which takes the file name as a parameter may be a cleaner solution.
</blockquote></details>

Good point. I added a helper function and also changed the go function `GenerateSCIONLabVM` which actually does not need to return the filename.

---

*[public/js/controllers/user.js, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVXknOdj32JhQdeoYD:-KtWDTOvmo-uOM8lpUZc:bf0sjfq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L74)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Minor: Why this value (992)? It seems like a magic number at the moment. Might be good to make this a parameter. 
</blockquote></details>

This is the standard bootstrap breakpoint for medium-sized screens. I wanted the buttons to change at the same point where the bootstrap grid adjusts.

---

*[public/js/controllers/user.js, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KtVZjKZZeYGOo9TIloP:-KtWENMfOdcfAL7IK6Y1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b8df83d32ede40a0a1893d77ccf9f906ab9f4dd/public/js/controllers/user.js#L85)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

missing new line at the end of the file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Comment by ercanucan** [comment]
Review status: 0 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/user.go, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ92U21gpqwpQV8GU3:-KuJ92U3TT-V2nI2SsA0:b-580kd9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/controllers/api/user.go#L1)):*
> ```Go
> package api
> ```

Missing license header.

---

*[controllers/api/user.go, line 40 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ9qYREYg-JttuIKSh:-KuJ9p08vUVyqbHG-U2u:bap9a0u) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/controllers/api/user.go#L40)):*
> ```Go
> }
> 
> // generates the structs containing information about the user's VM and the configuration of UI buttons
> ```

Please keep the line length less than 101 chars.

---

*[public/css/style.css, line 6 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ8yrdCkmMpAu6442J:-KuJ8yrevnFYJ5yXNILZ:b-moyziq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/css/style.css#L6)):*
> ```CSS
> .error{
>   color: red;
> }
> ```

missing new-line.

---

*[public/js/app.js, line 71 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJA5QV42MdOOHfpnoW:-KuJA5QV42MdOOHfpnoX:bjw17k0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/js/app.js#L71)):*
> ```JavaScript
>             };
>         }]);
> })();
> ```

missing new-line

---

*[public/js/controllers/user.js, line 24 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJAMzIqIkFf2yzN4LG:-KuJAMzIqIkFf2yzN4LH:b12a3q1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/js/controllers/user.js#L24)):*
> ```JavaScript
>                     });
>             };
>             
> ```

Please remove the trailing white-spaces here.

---

*[vagrant/run.sh, line 66 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJB8R0m8ccnR3Xe9U9:-KuJB8R0m8ccnR3Xe9UA:bgv2haw) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/vagrant/run.sh#L66)):*
> ```Shell
>         run_vagrant
>     else
>     	echo "Currently, SCIONLabVM does not support your linux distribution."
> ```

Please avoid using tabs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Comment by ercanucan** [comment]
@mlegner made a pass.

---

Review status: 0 of 21 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-:-KuJBJ4awd4dLLitdwj_:b-ejxc7g)*

**Comment by mlegner** [comment]
@ercanucan fixed all issues.

---

Review status: 0 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/user.go, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ92U21gpqwpQV8GU3:-KuJCJ4s9D_pPl5ahZT0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/controllers/api/user.go#L1)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Missing license header.
</blockquote></details>

Done.

---

*[controllers/api/user.go, line 40 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ9qYREYg-JttuIKSh:-KuJCOPBWUgu748hpDTB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/controllers/api/user.go#L40)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please keep the line length less than 101 chars.
</blockquote></details>

Done.

---

*[public/css/style.css, line 6 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJ8yrdCkmMpAu6442J:-KuJCSYZLUOxzJWqZYTY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/css/style.css#L6)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

missing new-line.
</blockquote></details>

Done.

---

*[public/js/app.js, line 71 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJA5QV42MdOOHfpnoW:-KuJCWo7PmBTBh0HWxX5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/js/app.js#L71)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

missing new-line
</blockquote></details>

Done.

---

*[public/js/controllers/user.js, line 24 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJAMzIqIkFf2yzN4LG:-KuJCqesX9qtQarj4c-x:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/public/js/controllers/user.js#L24)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please remove the trailing white-spaces here.
</blockquote></details>

Done.

---

*[vagrant/run.sh, line 66 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-KuJB8R0m8ccnR3Xe9U9:-KuJCxUoN5diYO6IgjDa:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/754059f194a7e14e19e5c53e222cb0cf27c3d613/vagrant/run.sh#L66)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please avoid using tabs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-:-KuJDDe6f_brhHg7WEN_:b50ewh8)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69#-:-KuJLicYoFTgAl_AxQl9:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 5 of 11 files at r1, 11 of 15 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/69)*

**Pull request merged**
