### PR TITLE
Document the API with OpenAPI 3.0.

### PR DESCRIPTION
**Pull request by Meldanor**
This replaces the different types of documentations (googledoc, github
wiki) with one standard documentation for RESTful APIs. Another
advantage is the automatic generation of clients and servers stubs which
implement the API. This accelerates the development of other clients.

You can view it in the swagger editor with this link: https://editor.swagger.io/?url=https://raw.githubusercontent.com/meldanor/scion-coord/openApi/openapi.yml

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/139)

### CODE REVIEW

**Comment by mlegner** [comment]
I like the idea of having a standardized and user-friendly documentation of our API.

Did you have to create this by hand or is there some way to automatize the creation of the yml file?
Unfortunately, quite a number of APIs are currently being changed (in PRs #133 and #136) or added (in PR #131), so there are a lot of modifications coming up for this file.

Another question: Do we want to include all the API calls in this documentation, even if they are not interesting for "external" clients?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/139#-:-L0Jzg7PLjf9tmbakfZM:b-q2g6s2)*

**Comment by Meldanor** [comment]
> Did you have to create this by hand or is there some way to automatize the creation of the yml file?
> Unfortunately, quite a number of APIs are currently being changed (in PRs #133 and #136) or added (in PR #131), so there are a lot of modifications coming up for this file.
Yes, I manually created the YML file. There is also support for JSON(import/export), but I think it is harder to maintain. There is a possibility to generate the documentation from the code, but there is a requirement: You do need to have OpenAPI annotations at each method in the code. I tried this once with Java Code and it was a unreadable code, because you had so many annotations only for the documentation it was hard to seperate it from the actual method name / parameter.

So yes, we have to modify the openapi.yml after each API change. But there is one big plus to have this "problem": You can do it the other way around: Modify the openapi.yml, think about all necessary datastructures and parameter and add them to the openapi.yml. If you think, this is a nice API, you start to implement it. I think this procedure is called "documentation / document driven development". The result of this is a well designed API.

> Another question: Do we want to include all the API calls in this documentation, even if they are not interesting for "external" clients?

I think, it is necessary to document all "APIs". Some of them are only used for the front-end (adminPageData with the button html data), but when I want to learn about the project it is easier to look at the API documentation then to look at the code. We can use tags to divide the API in "website" and "general API", which I did as a first start "website","scionLab","virualCurrency".

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/139#-:-L0KwDKd5yZUrRBlTRVX:btpzj0j)*

**Comment by chaehni** [comment]
I also like the idea. Thanks doing this. 
One minor comment: Not all API calls respond with a status '200' on success.

**Comment by Meldanor** [comment]
@chaehni : Which API calls are they? I looked at the Go code without trying them all and maybe got them wrong in the documention. I will fix this, just need to know which ones are wrong.

**Comment by chaehni** [comment]
@Meldanor : I looed at the APIs and the only one I could find was the 'resendLink', which responds with a status '204' on success. I think all the others are correct.

**Comment by Meldanor** [comment]
Fixed the respond status code for "resendLink"

**Comment by mlegner** [comment]
This PR addresses issue #18.

**Comment by mlegner** [comment]
This PR has been dormant for a while now. Will somebody (e.g., @Meldanor or @lryll) update it for the changes of the past few months? Otherwise, I suggest to close it.

**Comment by lryll** [comment]
With my current schedule, unfortunately, I won't be able to work on this in the near future. Sorry. 
I'll further discuss this with Prof. Hausheer tomorrow.

- Would the Open API documentation still be beneficial for many developers?
- Also, is the effort for keeping it up to date acceptable?

**Comment by matzf** [comment]
`scion-coord` will be discontinued; development of a the new scionlab-coordinator webpage with a reduced scope will continue in [netsec-ethz/scionlab](https://github.com/netsec-ethz/scionlab/).

**Pull request closed without merging**
