### PR TITLE
Finish database cleanup and support different ports of VPN servers

### PR DESCRIPTION
**Pull request by mlegner**
This PR finishes the job of #156 by fixing all remaining database column names.
In addition, it makes it possible to specify the port used for openVPN servers and allows APs to not offer VPN connection at all.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/161)

### CODE REVIEW

**Comment by juagargi** [comment]
Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[public/partials/user.html, line 72 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-L5nWJ-nZ6-SnU3iSKUA:-L5nWJ-nZ6-SnU3iSKUB:btj2wq6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/2692387265f48d54193c32a9c4f6d0487790101f/public/partials/user.html#L72)):*
> ```HTML
>       <label>Attachment point to connect to</label>
>         <select name="AP" class="form-control dropdown-toggle" ng-model="asInfo.AP"
>                 ng-options="i as x.Label group by x.ISD for (i, x) in aps | toArray | orderBy: ['ISD', 'Label']"
> ```

There seems to be a problem here: we are using the index of an array instead of the key from the map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161)*

**Comment by hausheer** [comment]
@chaehni Could you maybe help us with a review of this PR?

**Comment by chaehni** [comment]
Made a pass. Looks good to me.

---

Reviewed 6 of 12 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[public/partials/user.html, line 98 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-L5tMwr2eb1DWmexy6jS:-L5tMwr2eb1DWmexy6jT:bk43m5d) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/2692387265f48d54193c32a9c4f6d0487790101f/public/partials/user.html#L98)):*
> ```HTML
>         <label>
>           <input type="checkbox" ng-model="asInfo.IsVPN" name="IsVPN"
>                  ng-disabled="asInfo.Type == 0">
> ```

How are the different types enumerated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-:-L5tN5xKGfHm_ZdocYLk:b-9yt2jk)*

**Comment by mlegner** [comment]
@juagargi, @chaehni Addressed your comments. Could you have another look?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[public/partials/user.html, line 72 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-L5nWJ-nZ6-SnU3iSKUA:-L5wQUdalGbSs-bJIsh3:b-oebhvr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/2692387265f48d54193c32a9c4f6d0487790101f/public/partials/user.html#L72)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

There seems to be a problem here: we are using the index of an array instead of the key from the map.
</blockquote></details>

Indeed, thank you. I needed the `toArray` to sort the list, but that messes up the rest. I removed the `toArray` and `orderBy` for now.

---

*[public/partials/user.html, line 98 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-L5tMwr2eb1DWmexy6jS:-L5wQkTT7gN1XtslLC_v:beasaer) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/2692387265f48d54193c32a9c4f6d0487790101f/public/partials/user.html#L98)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

How are the different types enumerated?
</blockquote></details>

The types are specified in `models/define.go` but I added a comment specifying it to the html file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-:-L5wROiWWfluyr0inJbG:bl1o6qm)*

**Comment by juagargi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-:-L5xK4WMBEjH7Q_6hWcO:bnfp4nl)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/161#-:-L5yVkUCcKYPu2isP1a_:bnfp4nl)*

**Comment by juagargi** [comment]
@mlegner  good to rebase and merge :)

**Pull request merged**
