### PR TITLE
Remove unused code from JavaScript files

### PR DESCRIPTION
**Pull request by ercanucan**
This PR removes some unused legacy code from JavaScript files and fixes
the comments where necessary.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/47)

### CODE REVIEW

**Comment by ercanucan** [comment]
@chaehni please have a look

**Comment by chaehni** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[public/js/services/admin.js, line 4 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47#-Ks2zEZT2k1Zg7Cl0fkZ:-Ks2zEZT2k1Zg7Cl0fk_:by81l80) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6207be4ce1ead8fe4a9453d85f34f7723c31e687/public/js/services/admin.js#L4)):*
> ```JavaScript
>     .factory('adminService', ["$http", "$q", function($http, $q) {
>     var adminService = {
>         // Go to the user's home page
> ```

This could maybe be rephrased to "Load the user's data" or similar as this API call loads the user's information from the backend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47)*

**Comment by chaehni** [comment]
@ercanucan only a minor improvement proposal regarding a comment.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47#-:-Ks2zumIRULSzu5ux4mh:b-p78d9u)*

**Comment by ercanucan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[public/js/services/admin.js, line 4 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47#-Ks2zEZT2k1Zg7Cl0fkZ:-Ks36zE33XPbmyYEvIT-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6207be4ce1ead8fe4a9453d85f34f7723c31e687/public/js/services/admin.js#L4)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

This could maybe be rephrased to "Load the user's data" or similar as this API call loads the user's information from the backend.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47#-:-Ks373OjGK1DCprs5NwF:bnfp4nl)*

**Comment by ercanucan** [comment]
@chaehni thanks, please resolve the "open discussions" on Reviweable by "acknowledge", mark it as "reviewed" and then we will merge it.

**Comment by chaehni** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/47)*

**Pull request merged**
