### PR TITLE
Admin role and page

### PR DESCRIPTION
**Pull request by mlegner**
This PR adds an admin role to users, who can then access the newly created admin page.
Refactored middleware and authorization handlers, added new admin handler.
Moved footer to bottom of page.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/79)

### CODE REVIEW

**Comment by ercanucan** [comment]
@mlegner Looks good in general. Only a couple of minor comments.

---

Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[controllers/api/admin.go, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KvlUiumo6PhtMcqP2VR:-KvlUiunDvJbR7VNZW3N:b-ve2qcu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ee11effb88df9a827cf502c29dee6627e727ad7c/controllers/api/admin.go#L43)):*
> ```Go
> 	FirstName        string
> 	LastName         string
> 	InvitorFirstName string
> ```

`Inviter`

---

*[controllers/api/admin.go, line 46 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KvlUynDyJUcmT0cEeIn:-KvlUynE4Kwbye7Th8ZI:bptzu5z) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ee11effb88df9a827cf502c29dee6627e727ad7c/controllers/api/admin.go#L46)):*
> ```Go
> 	InvitorLastName  string
> 	HostAddress      string
> 	UUID             string
> ```

Would make sense to give a little more verbose name. Something like `InvitationUUID` maybe? Also, I could not see where the uuid is being used. Is that going to come in a next PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-:-KvlVm_6EuRLXOnym9nN:b3hb32g)*

**Comment by mlegner** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[controllers/api/admin.go, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KvlUiumo6PhtMcqP2VR:-KwEi76p5j9UnFwH1oZp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ee11effb88df9a827cf502c29dee6627e727ad7c/controllers/api/admin.go#L43)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

`Inviter`
</blockquote></details>

Done.

---

*[controllers/api/admin.go, line 46 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KvlUynDyJUcmT0cEeIn:-KwEi7evkV47O_xnoi6e:b-nzrxbw) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ee11effb88df9a827cf502c29dee6627e727ad7c/controllers/api/admin.go#L46)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Would make sense to give a little more verbose name. Something like `InvitationUUID` maybe? Also, I could not see where the uuid is being used. Is that going to come in a next PR?
</blockquote></details>

This actually belongs to the email-invitations PR, I now moved it there. I wanted to reuse the UUID field that already exists in the database instead of adding yet another field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79)*

**Comment by ercanucan** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/middleware/authorization.go, line 59 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KwihgXAohX2GGLqf_He:-KwihgXBRQ8BZNkwuRgA:b-vdee5a) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/843e74942bb09389e826088e51354b88b0376235/controllers/middleware/authorization.go#L59)):*
> ```Go
> 
> func checkLogin(r *http.Request) bool {
> 	_, userSession, _ := GetUserSession(r)
> ```

Would it make sense to check for error here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79)*

**Comment by ercanucan** [comment]
Reviewed 20 of 21 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79)*

**Comment by mlegner** [comment]
Addressed last review comment and checke for error in middleware.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/middleware/authorization.go, line 59 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-KwihgXAohX2GGLqf_He:-KwnQ1-krNWh5RFIkP1a:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/843e74942bb09389e826088e51354b88b0376235/controllers/middleware/authorization.go#L59)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Would it make sense to check for error here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-:-KwnQ2-FhhWPOFGglNcq:bm45id5)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 20 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79#-:-KxHfY_0wsi4Hj3UIUrk:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/79)*

**Comment by mlegner** [comment]
Merged #79.

**Pull request merged**
