### PR TITLE
Fixed nil pointer panic that can occur on login

### PR DESCRIPTION
**Pull request by chaehni**
This solves the problem described in issue #30

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/32)

### CODE REVIEW

**Comment by chaehni** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/login.go, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-KnIpMjvUOpgkD0-lPjC:-KnIpMjvUOpgkD0-lPjD:bwowbl4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b074cef6617fd74caddcff25740d646a85880c8d/controllers/api/login.go#L147)):*
> ```Go
> 		// make sure they are not empty
> 		if email == "" || password == "" {
> 			c.Forbidden(err, w, r)
> ```

At this point, err is always nil. So the 'Forbidden' function crashes when processing err.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32)*

**Comment by ercanucan** [comment]
@chaehni looks good to me. Only a minor comment.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/api/login.go, line 140 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-Knhr1sWEJYkcT1Bdf4_:-Knhr1sXWO7DWYeUvTrT:b8dzsiw) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be1a932a28186827beb2df14388541f13678e6fd/controllers/api/login.go#L140)):*
> ```Go
> 		// check if the parsing succeeded
> 		if err := decoder.Decode(&user); err != nil {
> 			c.Forbidden(fmt.Errorf("%v: Decoding JSON failed", err), w, r)
> ```

In order to be consistent with the rest of the code, put the error at the end of the string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-:-KnhrFhZPFol_ycV2QaW:b-1r2158)*

**Comment by chaehni** [comment]
Addressed the feedback.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/api/login.go, line 140 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-Knhr1sWEJYkcT1Bdf4_:-Ko7Lgh8WXWe3ian8BMQ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be1a932a28186827beb2df14388541f13678e6fd/controllers/api/login.go#L140)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

In order to be consistent with the rest of the code, put the error at the end of the string
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-:-Ko7NEdYGL1dIWM88Ivq:b-rlf6m0)*

**Comment by ercanucan** [comment]
:lgtm: please do an interactive rebase (`git rebase -i`) in which you squash the commits into one and push. We can then merge it.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-:-Ko7PfjlJ90b02L9seav:b-u2mmw2)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32)*

**Comment by chaehni** [comment]
I've squashed the commits. It should be ready to merge now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-:-KoC4fPRd6-rXz7G0lP9:b-rcrckk)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-:-KoH6HcGeG7XoJ2HXzxX:bnfp4nl)*

**Comment by chaehni** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/login.go, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-KnIpMjvUOpgkD0-lPjC:-KoH7423Bze2qPaL3e4v:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b074cef6617fd74caddcff25740d646a85880c8d/controllers/api/login.go#L147)):*
<details><summary><i>Previously, chaehni wrote…</i></summary><blockquote>

At this point, err is always nil. So the 'Forbidden' function crashes when processing err.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32)*

**Comment by ercanucan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/login.go, line 147 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32#-KnIpMjvUOpgkD0-lPjC:-KoH7qN38GZjd4WS8nQY:b32w0x) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/b074cef6617fd74caddcff25740d646a85880c8d/controllers/api/login.go#L147)):*
<details><summary><i>Previously, chaehni wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/32)*

**Pull request merged**
