### PR TITLE
Add link to tutorials in the header

### PR DESCRIPTION
**Pull request by juagargi**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/226)

### CODE REVIEW

**Comment by juagargi** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/netsec-ethz/scion-coord/226#-LDI-Gam2mKlRC78dfsT:-LDI-Gan0LZCAqORWxlh:b5idmqd) (no related file):*
Actually, I'd like to have the link loaded from the configuration file, as we do for the Grafana one. I tried to do a similar thing but failed miserably. To anybody that could help me here I would owe them a coffee.

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/226)*

**Comment by chaehni** [comment]
I think I can help with that.

**Comment by juagargi** [comment]
Help very much appreciated. You can either fix this PR or make a new one and we'll close this one. Thanks @chaehni !

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/226#-:-LDLXPHA9M5KGJ7GuPb5:b-m7z4ps)*

**Comment by chaehni** [comment]
I updated the PR. It now takes the URL from the configs.
Also, I made a very small change to the Grafana link. (according to <https://docs.angularjs.org/api/ng/directive/ngHref>)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/226#-:-LDLeKxQElGnCtCYFVm-:bix6sjx)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/226)*

**Pull request merged**
