### PR TITLE
Run deps when upgrading

### PR DESCRIPTION
**Pull request by juagargi**
(Chained from PR #210 )

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/211)

### CODE REVIEW

**Comment by juagargi** [comment]
Reviewed 17 of 18 files at r1.
Review status: 17 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by mlegner** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[scion_upgrade_script.sh, line 91 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9pJQJ2DrzLKbBIdN8I:-L9pJQJ2DrzLKbBIdN8J:bz0jq4b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0c4a6226707e6eca435c00f44d86d786926ef0a3/scion_upgrade_script.sh#L91)):*
> ```Shell
>     echo "Starting SCION again..."
>     ./scion.sh clean || true
>     ./env/deps || echo "ERROR: Dependencies failed. Starting SCION might fail!"
> ```

We already call `env/deps` four lines above. Maybe extend that line and move the clean up.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scion_upgrade_script.sh, line 91 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9pJQJ2DrzLKbBIdN8I:-L9smwuhE8_pWWCSNFtd:b-ikq10t) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0c4a6226707e6eca435c00f44d86d786926ef0a3/scion_upgrade_script.sh#L91)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We already call `env/deps` four lines above. Maybe extend that line and move the clean up.
</blockquote></details>

Definitely! I will remove this call and move the clean before calling deps.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-:-L9uUFGG-V2gb7Rtczyw:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scion_upgrade_script.sh, line 19 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ucuiK7GB2X69wzDpu:-L9ucpdl3KW6z6I1K6E-:b-b9djdj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L19)):*
> ```
> VERS=$(grep "^# SCION upgrade version" "$f" | sed -n 's/^# SCION upgrade version \([0-9\.]*\).*$/\1/p')
> ```

What do you think about changing that to something like `grep "SCION_upgrade_version" "$f"  | awk '{split($0,a,"="); print a[2]}'`
Since what we want is some key,value version information, right?

---

*[scion_upgrade_script.sh, line 41 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9udv6d1Q5l8sJNUXT1:-L9udv6d1Q5l8sJNUXT2:b-1sv2fp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L41)):*
> ```Shell
> shopt -s nullglob
> 
> export LC_ALL=C
> ```

Can we reset that value after the script has finished running? The user might not expect to get global environment variable to be changed just like that
The reason you are setting it, is because it causes issues when it is unset, right?

---

*[scion_upgrade_script.sh, line 64 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ueetC0qAqVPRyjpt6:-L9ueetC0qAqVPRyjpt7:b8j76yo) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L64)):*
> ```
> $SC
> ```
Most of us have $SC set as a convenience, but is it set somewhere during the 'official' install guide or install script?

---

*[scion_upgrade_script.sh, line 70 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ufhyUB6JgzO9klVs3:-L9ufhyUB6JgzO9klVs4:b-bt1r28) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L70)):*
> ```Shell
> then
>     echo "GIT user credentials not set, configuring defaults"
>     git config --global user.name "Scion User" 
> ```

Do you need to make these settings global? I think it should also work if those are only set for the current git repo.

---

*[scion_upgrade_script.sh, line 95 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ufzu28sx_d5acK6dB:-L9ufzu28sx_d5acK6dC:b-4hbwfg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L95)):*
> ```Shell
> 
> RESULT=$(curl -X POST "${SCION_COORD_URL}/api/as/confirmUpdate/${ACCOUNT_ID}/${ACCOUNT_SECRET}?IA=${IA}")
> echo "Done, got response from server: ${RESULT}"
> ```

You seem to have a strange end of file / end of line character here ^

---

*[vagrant/scionupgrade.service, line 1 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9udL4QCtwhSlYpWKcN:-L9udL4QCtwhSlYpWKcO:b-w8uv34) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/vagrant/scionupgrade.service#L1)):*
> ```
> SCION upgrade version 0.2
> ```
With the suggestion from above we would change that as well to `# SCION_upgrade_version=0.2`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[vagrant/scionupgrade.service, line 1 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9udL4QCtwhSlYpWKcN:-L9zSoX65xLN-3cKMuGC:b-vmj0bx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/vagrant/scionupgrade.service#L1)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> SCION upgrade version 0.2
> ```
With the suggestion from above we would change that as well to `# SCION_upgrade_version=0.2`
</blockquote></details>

I like these suggestions, I'm going to create issue(s) about them.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Reviewed 1 of 18 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[scion_upgrade_script.sh, line 91 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9pJQJ2DrzLKbBIdN8I:-L9zTfcy-ijssyR-s_aT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0c4a6226707e6eca435c00f44d86d786926ef0a3/scion_upgrade_script.sh#L91)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Definitely! I will remove this call and move the clean before calling deps.
</blockquote></details>

Done.

---

*[scion_upgrade_script.sh, line 19 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ucuiK7GB2X69wzDpu:-L9zTZ-Q0bG1znQvRZ4-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L19)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> VERS=$(grep "^# SCION upgrade version" "$f" | sed -n 's/^# SCION upgrade version \([0-9\.]*\).*$/\1/p')
> ```

What do you think about changing that to something like `grep "SCION_upgrade_version" "$f"  | awk '{split($0,a,"="); print a[2]}'`
Since what we want is some key,value version information, right?
</blockquote></details>

Done.

---

*[scion_upgrade_script.sh, line 41 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9udv6d1Q5l8sJNUXT1:-L9zT_vOCQF-8hPIyS5n:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L41)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Can we reset that value after the script has finished running? The user might not expect to get global environment variable to be changed just like that
The reason you are setting it, is because it causes issues when it is unset, right?
</blockquote></details>

Done.

---

*[scion_upgrade_script.sh, line 64 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ueetC0qAqVPRyjpt6:-L9zTckU98Rj3WPwBgDu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L64)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> $SC
> ```
Most of us have $SC set as a convenience, but is it set somewhere during the 'official' install guide or install script?
</blockquote></details>

Done.

---

*[scion_upgrade_script.sh, line 70 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ufhyUB6JgzO9klVs3:-L9zTe7KEnZA7bzjzF7J:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L70)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Do you need to make these settings global? I think it should also work if those are only set for the current git repo.
</blockquote></details>

Done.

---

*[scion_upgrade_script.sh, line 95 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-L9ufzu28sx_d5acK6dB:-L9zTgd81GHzAnDwI1vY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/5f36a216b60f438ea17d2eed0f5b449afd6f4f86/scion_upgrade_script.sh#L95)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

You seem to have a strange end of file / end of line character here ^
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Reviewed 6 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r6.
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by juagargi** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211)*

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/211#-:-LACBcu1Bq58x1o8V3Y_:bnfp4nl)*

**Pull request merged**
