### PR TITLE
systemd for automatic start,respawn

### PR DESCRIPTION
**Pull request by juagargi**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/170)

### CODE REVIEW

**Comment by xabarass** [comment]
Maybe we can extend this service to send emails when `scion-coord` gets restarted? It should be pretty straight forward according to [this](http://northernlightlabs.se/systemd.status.mail.on.unit.failure)?

**Comment by hausheer** [comment]
I am not sure the vagrant directory is the right location for this. In my view there should be a scion-coord install script that takes care of installing scion-coord as a service

**Comment by mlegner** [comment]
Thanks for creating the systemd service. I agree with @xabarass and @hausheer about the emails and the location.
In general, we should maybe rethink our directory structure a little bit now that we have so many scripts for different purposes.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vagrant/scion-coord.service, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L613ILubdgxts05IpXL:-L613ILvQLZhA8sB4mRz:bbz23dx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4e621be6089227b16adfe64a55688e1d304e81ac/vagrant/scion-coord.service#L14)):*
> ```
> StandardOutput=syslog
> StandardError=syslog
> SyslogIndentifier=scion-coord
> ```

I see an error "Unknown lvalue 'SyslogIndentifier' in section 'Service'" in `journalctl`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L613P2frTjtzOvwRCPw:b2pxt53)*

**Comment by juagargi** [comment]
The installer script and service files are now in scripts/
In the next commit I will address the emailing.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/scion-coord.service, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L613ILubdgxts05IpXL:-L61t6Tdk3-MTDjT3vPb:b-k9syek) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4e621be6089227b16adfe64a55688e1d304e81ac/scripts/scion-coord.service#L14)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I see an error "Unknown lvalue 'SyslogIndentifier' in section 'Service'" in `journalctl`.
</blockquote></details>

That's because I don't know how to type. Fix in the next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L61qSV2KEeapL2QJwqV:b1kg15k)*

**Comment by juagargi** [comment]
The email on failure scheme is quite generic. I'm implementing it, although we are just going to use it for the coordinator.

We have to configure sendmail to be able to send emails. That, I don't know how to do, but I can do it if everybody else is as lost as I am.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L61twVTqOen0y2lgrr-:bzf3sri)*

**Comment by xabarass** [comment]
Well I can take a look at `sendmail` Its not a problem :) If it doesn't work I can always configure [my script](https://github.com/xabarass/emailer) for sending emails.

**Comment by juagargi** [comment]
Thanks @xabarass ! It would be nice to have it configured safely, because I remember that (at least back in the days) sendmail could be a source of security problems.

**Comment by mlegner** [comment]
@juagargi Made another pass, only one comment below.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/install-scion-coord.sh, line 36 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L78oRvYDXWW_eGWfhOn:-L78oRvYDXWW_eGWfhOo:b-ssph6d) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/636ba62089ef4c0b0d6486e78823ce0f1be7823d/scripts/install-scion-coord.sh#L36)):*
> ```Shell
> fi
> 
> if ! dpkg-query -s sendmail &> /dev/null ; then
> ```

This line and the following ones only work for Debian-based systems. Do we want to restrict this? We might instead check for the distribution (e.g., if dpkg-query and apt-get exist) and otherwise simply tell the user to install sendmail manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L78ovIIuR6KqHIcV7xo:b-o9540)*

**Comment by juagargi** [comment]
Thanks! Milan is going to add some commits to this branch setting up the mailing system. We'll write a comment once it's done. For now I'm not touching anything and will let Milan do his magic.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/install-scion-coord.sh, line 36 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L78oRvYDXWW_eGWfhOn:-L79PufRWZwACQfyIYVT:b-r184nv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/636ba62089ef4c0b0d6486e78823ce0f1be7823d/scripts/install-scion-coord.sh#L36)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This line and the following ones only work for Debian-based systems. Do we want to restrict this? We might instead check for the distribution (e.g., if dpkg-query and apt-get exist) and otherwise simply tell the user to install sendmail manually.
</blockquote></details>

This all is going out as Milan is not going to use sendmail, I think :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L79Q3hTkkGvXhSV2I75:ble44b2)*

**Comment by mlegner** [comment]
@xabarass Thanks for the nice feature. I made a pass and left some comments below.

---

Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scripts/install-scion-coord.sh, line 48 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O5MMrmATAiFe3ZMBF:-L7O5MMrmATAiFe3ZMBG:b-yt29km) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/install-scion-coord.sh#L48)):*
> ```Shell
> sudo cp "$basedir/scripts/files/unit-status-mail@.service" .
> popd >/dev/null
> sudo cp "$basedir/scripts/files/emailer.py" "/usr/bin/emailer"
> ```

Is it necessary to copy `emailer.py` to `/usr/bin`?

---

*[scripts/files/README.md, line 11 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O4yiBnJzctBJJsybQ:-L7O4yiBnJzctBJJsybR:b-s8x139) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L11)):*
> ```Markdown
> ### Configuring email credentials
> 
> By default `unit-status-mail@.service` is looking at `/home/scion/email.conf` for email configuration. It is necessary to create this file (or change file location in `unit-status-mail@.service` to different file) to be able to send emails. File has following structure:
> ```

Maybe we should create a subdirectory with all scion-coord-related configuration files? Also, the script could create a default version of this file automatically.

---

*[scripts/files/README.md, line 24 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O537P2Y6iVxX4et8B:-L7O537P2Y6iVxX4et8C:b-q64pkt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L24)):*
> ```Markdown
> ### Configuring recipients
> 
> By default `unit-status-mail@.service` uses `/home/scion/recipients.txt` as a file that contains email addresses that will receive email on failure. This file has to be created or appropriate argument in `unit-status-mail@.service` must be changed to point to different file.
> ```

See above.

---

*[scripts/files/unit-status-mail@.service, line 7 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O4rOdXqwAO4ptZTYD:-L7O4rOdXqwAO4ptZTYE:b-klvase) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/unit-status-mail@.service#L7)):*
> ```
> [Service]
> Type=simple
> User=scion
> ```

The user should ideally be configurable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L7O5Uypt3sEzetA7aQg:bpdiflp)*

**Comment by juagargi** [comment]
I will address these changes, since I believe Milan is busy and won't be able to make the changes.

---

Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-:-L7YuKkXfTMnK3ncf4an:b-6j8b4h)*

**Comment by juagargi** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/install-scion-coord.sh, line 48 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O5MMrmATAiFe3ZMBF:-L7dLWdbFxaZM4W29336:b-w1fkb4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/install-scion-coord.sh#L48)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Is it necessary to copy `emailer.py` to `/usr/bin`?
</blockquote></details>

I would copy it to /usr/local/bin or /usr/bin because it's going to act as a system-wide script.
For now I'm changing it to /usr/local/bin (as it's not part of the standard distribution). We can always change it to ~/.local/bin to "hide" it from the rest of the system.

---

*[scripts/files/README.md, line 11 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O4yiBnJzctBJJsybQ:-L7dqPtqCot8SborgUor:bksoip8) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L11)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Maybe we should create a subdirectory with all scion-coord-related configuration files? Also, the script could create a default version of this file automatically.
</blockquote></details>

I've submitted changes to this, but the credentials have to be created in-place (we don't want to expose passwords, etc in a repository).

---

*[scripts/files/unit-status-mail@.service, line 7 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O4rOdXqwAO4ptZTYD:-L7dNaBPeoknElPFXoF5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/unit-status-mail@.service#L7)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

The user should ideally be configurable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170)*

**Comment by juagargi** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/files/README.md, line 24 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170#-L7O537P2Y6iVxX4et8B:-L7dr1KBl0m-ZkB135Zg:bz121ob) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L24)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done. (Reviewable hates me and forces me to write on each unanswered comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/170)*

**Comment by xabarass** [comment]
:lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170#-:-L9Um658ChjAc2SXVSOW:bnfp4nl)*

**Comment by juagargi** [comment]
Reviewed 1 of 6 files at r2, 1 of 5 files at r3, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170)*

**Comment by jonghoonkwon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/install-scion-coord.sh, line 48 at r3](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170#-L7O5MMrmATAiFe3ZMBF:-L9k5nmBB-4EMuhg4BRI:bg7igkv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/install-scion-coord.sh#L48)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I would copy it to /usr/local/bin or /usr/bin because it's going to act as a system-wide script.
For now I'm changing it to /usr/local/bin (as it's not part of the standard distribution). We can always change it to ~/.local/bin to "hide" it from the rest of the system.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170)*

**Comment by jonghoonkwon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/files/README.md, line 11 at r3](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170#-L7O4yiBnJzctBJJsybQ:-L9k61Ks9d9zTj3ldPQw:bg7igkv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L11)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I've submitted changes to this, but the credentials have to be created in-place (we don't want to expose passwords, etc in a repository).
</blockquote></details>

:lgtm: 

---

*[scripts/files/README.md, line 24 at r3](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170#-L7O537P2Y6iVxX4et8B:-L9k6CRY9IK5MVe9BWqG:bg7igkv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/README.md#L24)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Done. (Reviewable hates me and forces me to write on each unanswered comment)
</blockquote></details>

:lgtm: 

---

*[scripts/files/unit-status-mail@.service, line 7 at r3](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170#-L7O4rOdXqwAO4ptZTYD:-L9k6EUe8li83PIiTKIM:bg7igkv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0e6f50a89673b74be0664f4268b2ad954e5cec95/scripts/files/unit-status-mail@.service#L7)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170)*

**Comment by jonghoonkwon** [comment]
Reviewed 1 of 6 files at r2, 1 of 5 files at r3, 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/170)*

**Pull request merged**
