### PR TITLE
Reregister ap

### PR DESCRIPTION
**Pull request by juagargi**
Merge after PR #180 
This PR solves the update gen script removing the connections from the topology when an AS detached from this AP and attached to another one.
- Create a new connection with info for the new attachment 
- Mark the old connection as to be deleted.
- Modify getUpdates and confirmUpdates to deal with the mutated AS IA

Warning: no UT added. No integration tests either, but update_gen.py hasn't changed, and the API contract should still remain valid.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/186)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 416 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78ec-vKej9BjuoR0hq:-L78ec-wyBD0rpEIMD6E:b-sqv4ku) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab.go#L416)):*
> ```Go
> 		// flag the old connections for deletion:
> 		if asInfo.OldAP != "" {
> 			cns, err := asInfo.LocalAS.GetJoinConnectionInfo()
> ```

This returns all connections where LocalAS is the joining AS. I don't think we want to remove all existing connection requests for this AS just because it changed one of its APs.
I think we need some test here to make sure that this works as intended and remains working as intended when we make changes here.

---

*[controllers/api/scion_lab.go, line 439 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78fZqlSiJJbBV9Dm_R:-L78fZqlSiJJbBV9Dm_S:b-p3y3k0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/controllers/api/scion_lab.go#L439)):*
> ```Go
> 		// remove the previous connection if it exists
> 		if asInfo.OldAP != "" {
> 			asInfo.LocalAS.DeleteConnectionToAP(asInfo.OldAP)
> ```

Why not fix the DeleteConnectionToAP functions instead of inlining the AP connection removal?

---

*[controllers/api/scion_lab_ap.go, line 231 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78ga33zSquxFcpxkCF:-L78ga34l4l90WSwg0ZE:b-6qm7ji) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab_ap.go#L231)):*
> ```Go
> 		// find the connection to the SCIONLabAS. e.g. ia=1-1001
> 		IA, err := addr.IAFromString(ia)
> 		if err != nil {
> ```

You probably also want to continue when unable to convert the ia.
I expect IA then to be nil and you get a panic on IA.I

---

*[models/scion_lab.go, line 94 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78hNu1g-Re3gSb0gXd:-L78hNu1g-Re3gSb0gXe:bu3d3qv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L94)):*
> ```Go
> 	IsVPN          bool
> 	Status         uint8
> 	OldConnection  bool   // true if this WAS a connection, but it needs to be deleted in the AP
> ```

Can't this be handled by updating the Status? What is the rational for introducing a new state?

---

*[models/scion_lab.go, line 535 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78i2dKWnMrDUgMN2To:-L78i2dLcbChL8tfwfNo:bpae4bn) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L535)):*
> FindSCIONLabASByASID
This assumes that AS ids are SCION global and are not only unique inside an ISD.
Please discuss on scionproto #dev (see discussion from 8.3.2018)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186)*

**Comment by mlegner** [comment]
@juagargi Made a pass. See some comments below.
I also replied to some of your comments, @fr4nk-w.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 416 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78ec-vKej9BjuoR0hq:-L792lPcVwil0AOfAfLT:bv5rgz1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab.go#L416)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

This returns all connections where LocalAS is the joining AS. I don't think we want to remove all existing connection requests for this AS just because it changed one of its APs.
I think we need some test here to make sure that this works as intended and remains working as intended when we make changes here.
</blockquote></details>

Currently, every (user-owned) AS only has one AP so at least at the moment, we should not run into trouble.

---

*[controllers/api/scion_lab.go, line 426 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L793da0URa9ifkrklc2:-L793da1GNK415DOOGMm:b918vi4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab.go#L426)):*
> ```Go
> 				err = asInfo.LocalAS.UpdateDBConnection(&cn)
> 				if err != nil {
> 					return fmt.Errorf("Error updating previous connection ID %v: %v", cn.ID, err)
> ```

I feel that we are more and more running into problems of potentially inconsistent database states because we are not using database transactions. What if some updates here work but others do not?
At least we should add a TODO in order to remember that we need to improve this at some point.

---

*[controllers/api/scion_lab.go, line 439 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78fZqlSiJJbBV9Dm_R:-L793MMCm9uA3tC4IP2q:b32v57) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/controllers/api/scion_lab.go#L439)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Why not fix the DeleteConnectionToAP functions instead of inlining the AP connection removal?
</blockquote></details>

+1

---

*[controllers/api/scion_lab_ap.go, line 238 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L794dcSFcTMUkC3jxHT:-L794dcTKuRZy3S7RtDQ:bey1gaq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab_ap.go#L238)):*
> ```Go
> 		if err != nil {
> 			// special case: are we removing an old connection to an AP?
> 			if err == orm.ErrNoRows {
> ```

I would find it cleaner, if we would keep all database-related errors, etc. in the `models/scion_lab.go`.

---

*[models/scion_lab.go, line 94 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78hNu1g-Re3gSb0gXd:-L7955g2ZhA0MD99SWEH:b-9fsz3f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L94)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Can't this be handled by updating the Status? What is the rational for introducing a new state?
</blockquote></details>

The point is to distinguish updates that also affect the AS status and those that should not. Here, an old connection has to be removed, but after that, the AS' status should not be changed (as this is only a "cleanup" action).
However, I agree that the naming is maybe not ideal. We could call it, e.g., "ModifyASStatusOnUpdate".

---

*[models/scion_lab.go, line 535 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-L78i2dKWnMrDUgMN2To:-L796MpqXINoK76wAxzg:bugoxgi) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L535)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> FindSCIONLabASByASID
This assumes that AS ids are SCION global and are not only unique inside an ISD.
Please discuss on scionproto #dev (see discussion from 8.3.2018)
</blockquote></details>

This is indeed something, we have to discuss. So far, we always used global ASIDs and I assumed (apparently incorrectly) that this corresponds to the SCION design.
As long as we stay consistent within SCIONLab, we should be fine for now. Still, we should come to a joint solution with the development team and follow those conventions in the long run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-:-L7973Rybigo8vKtiRGu:b-bs2v55)*

**Comment by juagargi** [comment]
Silly as I am, I forgot to commit the fix. Now it's committed and pushed. Review needed again! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-:-L79NqblB4q0Y5mAgfps:bpsjbpy)*

**Comment by mlegner** [comment]
I assume this applies to #188.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-:-L79X74f0sQkv5k1el2m:b-ogdhdz)*

**Comment by juagargi** [comment]
Indeed. This PR had the commit I intended when I opened it.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 416 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L78ec-vKej9BjuoR0hq:-L79mb8F6oN7ISWleXxU:b1xihqf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab.go#L416)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Currently, every (user-owned) AS only has one AP so at least at the moment, we should not run into trouble.
</blockquote></details>

It is a very reasonable question. The fact that we can assert is that if we have IsNewConnection==true AND OldAP!="" is that we have changed the AP for one of the connections, and not all of them.
For now it works because there's one, and the n connection entries that we have at that point in the DB have to represent old connections. I'm adding a check so we don't run into problems when we fully support more APs

---

*[controllers/api/scion_lab.go, line 426 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L793da0URa9ifkrklc2:-L79qQqG73W8BTGiC_XG:b-jrc06n) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab.go#L426)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I feel that we are more and more running into problems of potentially inconsistent database states because we are not using database transactions. What if some updates here work but others do not?
At least we should add a TODO in order to remember that we need to improve this at some point.
</blockquote></details>

Loving it. Issue #189 recording this request.

---

*[controllers/api/scion_lab.go, line 439 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L78fZqlSiJJbBV9Dm_R:-L7AZZ3J5nZdqhHgQDgL:bb6un1j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6da7c11b526f6681760bcbd4a7e864294ad74840/controllers/api/scion_lab.go#L439)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done

---

*[controllers/api/scion_lab_ap.go, line 231 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L78ga33zSquxFcpxkCF:-L79s0NwA8BKLKrIKYrW:b-530q1o) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab_ap.go#L231)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

You probably also want to continue when unable to convert the ia.
I expect IA then to be nil and you get a panic on IA.I
</blockquote></details>

continue forgotten

---

*[controllers/api/scion_lab_ap.go, line 238 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L794dcSFcTMUkC3jxHT:-L7AZaxPA-h-H3BOK5GX:b-i1ye8c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/controllers/api/scion_lab_ap.go#L238)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I would find it cleaner, if we would keep all database-related errors, etc. in the `models/scion_lab.go`.
</blockquote></details>

Yes. Actually, there's no need to look for the AS twice.

---

*[models/scion_lab.go, line 94 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L78hNu1g-Re3gSb0gXd:-L79si0OEriuv56-gqqr:b-4jo6s5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L94)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

The point is to distinguish updates that also affect the AS status and those that should not. Here, an old connection has to be removed, but after that, the AS' status should not be changed (as this is only a "cleanup" action).
However, I agree that the naming is maybe not ideal. We could call it, e.g., "ModifyASStatusOnUpdate".
</blockquote></details>

The way the code is done right now, we don't get a connection object from the DB, but a ConnectionInfo, that holds the information from/to one AS and the neighbor, depending if this ConnectionInfo was obtained with a call of getJoinConnection or getResponseConnection family.
The connection entry in the DB represents it needs cleanup with the two status fields to REMOVE, but we can't see that in the ConnectionInfo type, as I tried to explain. Thus I need to mark it in this type somehow, or make a new call to the opposite family get{Join/Response}Connection and check the status there, which is also (more?) undesirable.
I'm changing the name to KeepASStatusOnUpdate.

---

*[models/scion_lab.go, line 535 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-L78i2dKWnMrDUgMN2To:-L79vnp387WnotqOa8a2:b-6o1czk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ff964d9902ca8a673d205080bf397cd11a0ac381/models/scion_lab.go#L535)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This is indeed something, we have to discuss. So far, we always used global ASIDs and I assumed (apparently incorrectly) that this corresponds to the SCION design.
As long as we stay consistent within SCIONLab, we should be fine for now. Still, we should come to a joint solution with the development team and follow those conventions in the long run.
</blockquote></details>

True. I just asked Jonghoon because we should only deal with IDs created in ScionLab.
If we break this assumption, we'll have to find another solution to communicate the updates back and forth, as the ID we use now to identify an AS is mutable. That is, when you send it as an update to remove the connection to an AP it probably has a different name than in the DB or in the other AP (e.g. 1-1003 against 2-1003 when reassigning the AP for 1003)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/186#-:-L79lgZa8qnHedS6BAdK:b32evlk)*

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186#-:-L7OqFL134aMRaqxip2k:bnfp4nl)*

**Comment by juagargi** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/186)*

**Pull request merged**
