### PR TITLE
Captcha implementation for user registration form

### PR DESCRIPTION
**Pull request by chaehni**
This PR adds a Google ReCaptcha to the registration form which needs to be solved in order to sign up an account.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/50)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[public/js/controllers/register.js, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4Y2U2s-LT3A8nd62Y:-Ks4Y2U2s-LT3A8nd62Z:b1wgja5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L8)):*
> ```JavaScript
>             $scope.message = "";
>             $scope.user = {};
>             $scope.pubkey = "----Public-Site-Key-Here----";
> ```

Would it be possible also to load this from the config file? It can be cumbersome to deploy scion-coord if each time we need to edit this file.

---

*[public/js/controllers/register.js, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4YKvWiHf8tkiyUP2l:-Ks4YKvWiHf8tkiyUP2m:b-ytnxb0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L14)):*
> ```JavaScript
>                 if (!$scope.user.captcha){
>                     $scope.error = "Please resolve the captcha before submitting."
>                     $scope.message = "";
> ```

Do we need this assignment to the`message`? It seems to be already assigned above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[public/js/controllers/register.js, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4Y2U2s-LT3A8nd62Y:-Ks4Z5eVQTgdRcH15O0C:b-nnrb9b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L8)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Would it be possible also to load this from the config file? It can be cumbersome to deploy scion-coord if each time we need to edit this file.
</blockquote></details>

I thought about that as well. I don't know yet how to inject a variable into a JavaScript file. I'll look into this.

---

*[public/js/controllers/register.js, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4YKvWiHf8tkiyUP2l:-Ks4b31iiJjUk7FhSQaa:bhetw11) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L14)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Do we need this assignment to the`message`? It seems to be already assigned above. 
</blockquote></details>

This is needed when signing up multiple users. This does delete the success message (from a first registration) when the user fails to solve the captcha for a subsequent registration. However, I think the assignments in line 5, 6 and 7 can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[public/js/controllers/register.js, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4Y2U2s-LT3A8nd62Y:-KsIsQjZxUsudP5bDOdo:b8ufo33) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L8)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I thought about that as well. I don't know yet how to inject a variable into a JavaScript file. I'll look into this.
</blockquote></details>

I went with the solution that loads the key from the front end once the user goes to the registration page. This way we don't introduce duplicate files that might cause confusion.

---

*[public/js/controllers/register.js, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-Ks4YKvWiHf8tkiyUP2l:-KsIsoXwJlu64ASV1R06:bzhxdvb) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/11affae3d9cd2804bf183e48c0f2435f1bad5614/public/js/controllers/register.js#L14)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

This is needed when signing up multiple users. This does delete the success message (from a first registration) when the user fails to solve the captcha for a subsequent registration. However, I think the assignments in line 5, 6 and 7 can be removed.
</blockquote></details>

I removed redundant assignments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by ercanucan** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[conf/development.conf, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsNZtkigUB3iefgqeBM:-KsNZtkjsUfeGocYIJ5o:bz1y2xe) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/conf/development.conf#L34)):*
> ```
> # Captcha configs
> captcha.secret_key = ""
> captcha.site_key = ""
> ```

minor: I would swap the order of these two.

---

*[controllers/controller.go, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsN_-Kia1BN8WnJYzc-:-KsN_-Kia1BN8WnJYzc0:b-u3inue) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/controllers/controller.go#L78)):*
> ```Go
> 	// write the content to socket
> 	if _, err := w.Write([]byte(data)); err != nil {
> 		c.Error500(err, w, r)
> ```

Please log the error here.

---

*[public/js/controllers/register.js, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsNajZ1D4m8D4I4p3LK:-KsNajZ2JSB7yB5_nrIR:b-nxuilc) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/public/js/controllers/register.js#L7)):*
> ```JavaScript
>             $scope.user = {};
> 
>            registerService.getSiteKey().then(
> ```

the indentation here looks a little bit off here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
addressed feedback

---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[conf/development.conf, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsNZtkigUB3iefgqeBM:-KsNtWKcUSW6TEnuLso2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/conf/development.conf#L34)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: I would swap the order of these two.
</blockquote></details>

Done.

---

*[controllers/controller.go, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsN_-Kia1BN8WnJYzc-:-KsNufAU-0XiZ2NcLPE2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/controllers/controller.go#L78)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please log the error here.
</blockquote></details>

Done.

---

*[public/js/controllers/register.js, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsNajZ1D4m8D4I4p3LK:-KsNvPqjb3Qnebhsa4ih:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/be137f1ad463c7ff438fed34dc9b1162d3ed1606/public/js/controllers/register.js#L7)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

the indentation here looks a little bit off here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-:-KsNvRBwtZ81S417N5wf:by3ggmv)*

**Comment by mlegner** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[conf/development.conf, line 32 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsmNyWconOUI37tXZMV:-KsmNyWconOUI37tXZMW:bq4wfeo) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d334783abfb8df26ee139dec33b75ff668517120/conf/development.conf#L32)):*
> ```
> email.pm_account_token = ""
> 
> # Captcha configs
> ```

We could add some information about the Captcha configs into README.md. At the same time we could do the same for the PostMark configs. Everything else looks good to me and works locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[conf/development.conf, line 32 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsmNyWconOUI37tXZMV:-Ksr8fobNEG7N5sXapKQ:bnh9hfb) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d334783abfb8df26ee139dec33b75ff668517120/conf/development.conf#L32)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We could add some information about the Captcha configs into README.md. At the same time we could do the same for the PostMark configs. Everything else looks good to me and works locally.
</blockquote></details>

Thanks for the input. I updated the README.md file. Please let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by mlegner** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[conf/development.conf, line 32 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsmNyWconOUI37tXZMV:-Ksr9es4MSKp-yZ8cO0M:b-1mkaxx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d334783abfb8df26ee139dec33b75ff668517120/conf/development.conf#L32)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Thanks for the input. I updated the README.md file. Please let me know what you think.
</blockquote></details>

LGTM. I think this simplifies the configuration in the beginning significantly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by ercanucan** [comment]
@chaehni I gave one minor comment. Please squash the commits and rebase after addressing that. 
Also, please fix your commit entry. Currently it reads: `Author: Unknown <chaehni@student.ethz.ch>`

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[public/partials/register.html, line 55 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KssnlftbQsZbfCX6Nde:-KssnlfuO0Iw2DbYBxOu:b-hus14u) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/1a13b7d1623f487b613b6f6fe2f8ff34106908c8/public/partials/register.html#L55)):*
> ```HTML
>       </div>
>       <br>
>       <div vc-recaptcha ng-model="user.captcha" key="pubkey"></div>
> ```

I would place the Captcha above the Register button. Otherwise, it is somewhat counter-intuitive for the user. He should be able fill out the form with the relevant info, confirm the Captcha and finally click on the Register button at the bottom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-:-KssiO6uJJ9OQaTrs6-Q:b-wzkibr)*

**Comment by ercanucan** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[public/js/controllers/register.js, line 9 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsstonBe1OylLecGNPI:-KsstonBe1OylLecGNPJ:b9byzeg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/1a13b7d1623f487b613b6f6fe2f8ff34106908c8/public/js/controllers/register.js#L9)):*
> ```JavaScript
>             registerService.getSiteKey().then(
>                 function (response) {
>                     $scope.pubkey = response.data;
> ```

To be consistent with the rest of the code, we should probably name this variable `siteKey` or `captchaSiteKey` instead of `pubkey`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by ercanucan** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[public/partials/register.html, line 55 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KssnlftbQsZbfCX6Nde:-Kst3djxPgjyyHreLdFm:b-u9muoa) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/1a13b7d1623f487b613b6f6fe2f8ff34106908c8/public/partials/register.html#L55)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would place the Captcha above the Register button. Otherwise, it is somewhat counter-intuitive for the user. He should be able fill out the form with the relevant info, confirm the Captcha and finally click on the Register button at the bottom.
</blockquote></details>

Testing it closely, we observe that the browser will show an error message because the page is loaded before the key is pulled from the back-end. Some of the methods here may be useful for waiting until the scope variable is loaded: https://stackoverflow.com/questions/16617259/wait-until-scope-variable-is-loaded-before-using-it-in-the-view-in-angular-js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
Thanks for the feedback and the help with debugging. This was really useful. I addressed the issues.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[public/js/controllers/register.js, line 9 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsstonBe1OylLecGNPI:-KswX1sT6cYL0iDky3ye:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/1a13b7d1623f487b613b6f6fe2f8ff34106908c8/public/js/controllers/register.js#L9)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

To be consistent with the rest of the code, we should probably name this variable `siteKey` or `captchaSiteKey` instead of `pubkey`.
</blockquote></details>

Done.

---

*[public/partials/register.html, line 55 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KssnlftbQsZbfCX6Nde:-KswX4Hs622vgsj0ctDV:bfvac2f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/1a13b7d1623f487b613b6f6fe2f8ff34106908c8/public/partials/register.html#L55)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Testing it closely, we observe that the browser will show an error message because the page is loaded before the key is pulled from the back-end. Some of the methods here may be useful for waiting until the scope variable is loaded: https://stackoverflow.com/questions/16617259/wait-until-scope-variable-is-loaded-before-using-it-in-the-view-in-angular-js
</blockquote></details>

Placed the captcha above submit button. 
I was now able to replicate the behaviour in Chrome. After debugging I came to the same conclusion. The key is now loaded before the route handler loads the registration  page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-:-KswXbUw4oyunoJ6zpZt:buhmnub)*

**Comment by mlegner** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[public/js/controllers/register.js, line 2 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsxE3nZtsibUJJ8HNBV:-KsxE3nZtsibUJJ8HNBW:b9axelh) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4894b9bf57dc8546cd65ac7f1a06878d9d566c2d/public/js/controllers/register.js#L2)):*
> ```JavaScript
> angular.module('scionApp')
>     .controller('registerCtrl', ['$scope', 'ResolveSiteKey', '$interval', '$location', 'vcRecaptchaService',
> ```

I think, we still need the registerService as an argument, as this is used below. Otherwise I get an error during the register process. Otherwise, everything works fine, the previous error does not occur any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by chaehni** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[public/js/controllers/register.js, line 2 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-KsxE3nZtsibUJJ8HNBV:-KsxJiCx_MykR1NQH6Rl:b-xg98pk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4894b9bf57dc8546cd65ac7f1a06878d9d566c2d/public/js/controllers/register.js#L2)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I think, we still need the registerService as an argument, as this is used below. Otherwise I get an error during the register process. Otherwise, everything works fine, the previous error does not occur any more.
</blockquote></details>

You're right of course. My bad. Re-added registerService as dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by ercanucan** [comment]
:lgtm: I have tested and can also confirm that it works locally.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50#-:-KsxMmMiRFhaH7NQJuoW:bo09g43)*

**Comment by ercanucan** [comment]
Reviewed 2 of 9 files at r1, 2 of 8 files at r2, 2 of 5 files at r3, 4 of 5 files at r4, 3 of 3 files at r5.
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Comment by ercanucan** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/50)*

**Pull request merged**
