### PR TITLE
Manual user activation

### PR DESCRIPTION
**Pull request by chaehni**
This is the first draft of the user activation feature with wich an admin can activate users to grant access to the SCION Coordination Service. It builds on top of the email verification system.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/33)

### CODE REVIEW

**Comment by mlegner** [comment]
This PR has been lying around for a long time now. I think, we should either rebase it and adapt it to changes in the codebase (which I would prefer) or alternatively close it (would be a shame).
What do you think, @chaehni @hausheer @ercanucan?

**Comment by hausheer** [comment]
The idea of this feature is that invited users can be per-activated and then don't need to go through the regular activation anymore. In my point of view it is still a feature that we will use when we invite users to use SCIONLab, so it would be great if it could be merged eventually.

**Comment by ercanucan** [comment]
I agree with @hausheer. The only concern with this feature was that in the early phases of SCIONLab, we wanted to have as little barriers as possible for the new users to join. It would probably require some additional work but we could make this feature based on an on-off flag. In case we see that we have too many registrations coming up, we could switch to this mode. What do you think @mlegner? Something like this could also be useful for SCIONBox registrations.

**Comment by chaehni** [comment]
I can update the PR to make it work with the current codebase. 
The administrator panel it introduces could be integrated into the one we now already have.
I think the flag to turn the feature on and off is a good idea and it can be added.

**Comment by mlegner** [comment]
Yes, I agree. Integrating it into the existing admin panel and adding an on/off flag to the configuration (similar to the one in the credit system) would be optimal in my opinion.

**Comment by chaehni** [comment]
I updated the PR to reflect changes made to SCIONLab since this PR was first opened.
It now also contains a flag in the config which allows to turn the feature off completely.
Because many files are touched, I split the changes into two separate PRs. This one contains all the server-side changes. The user interface changes are contained in this PR: https://github.com/netsec-ethz/scion-coord/pull/145

**Comment by matzf** [comment]
`scion-coord` will be discontinued; development of a the new scionlab-coordinator webpage with a reduced scope will continue in [netsec-ethz/scionlab](https://github.com/netsec-ethz/scionlab/).

**Pull request closed without merging**
