### PR TITLE
Allow users to create multiple VMs connected to different ASes

### PR DESCRIPTION
**Pull request by mlegner**
This PR addresses issues #46 and #70 in the following way:
It extends the SCIONLab Coordination Service such that it can handle multiple SCIONLab ASes
and allows each user to connect once to each one of them
UI, backend, and configuration are changed to handle these functionalities.
In addition, some refactoring is done as well as changes to the api requests in javascript.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/95)

### CODE REVIEW

**Comment by mlegner** [comment]
This is a first proposal, I am very happy about any feedback and suggestions.
Note: I rebased it on top of the admin_page PR (#79) to avoid lots of additional rebasing when that one is merged.

**Comment by ercanucan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[main.go, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOBB6KXDZBLL_-f8MP:-KxOBB6Lb6svBmaT7eIq:b-pjx4a) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/main.go#L38)):*
> ```Go
> // make sure that data about SCIONLab ASes in database is correct
> // TODO (mlegner): remove deprecated servers?
> // TODO (mlegner): replace this by an init script and a admin interface at some point.
> ```

an admin interface.

---

*[README.md, line 72 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOBo_EJcun1PcfYSkf:-KxOBo_Fuq5dJcA0A3Fp:b-u6jlw5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/README.md#L72)):*
> ```Markdown
> #### Credentials
> 
> In order for the configurations to be generated, credentials for all ISDs (%) with SCIONLab ASes
> ```

As discussed, the `%` here is comes misleading. Cert and key are for ASes (ISD-AS), TRC is per ISD. 

---

*[controllers/api/user.go, line 143 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOEPK647sB9zD0XxKV:-KxOEPK647sB9zD0XxKW:b-e2w0w0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/controllers/api/user.go#L143)):*
> ```Go
> 
> 	for _, vm := range vmsInfo {
> 		if vm.VMStatus == 1 {
> ```

you could use `ACTIVE` here instead of 1.

---

*[models/scion_lab.go, line 129 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHaFtHl7SOHXV0iDQ:-KxOHaFuiHVvZ4yPaYwn:bufnymr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/models/scion_lab.go#L129)):*
> ```Go
> 			sls.LastAssignedPort = serverConfig.ServerStartPort
> 		}
> 		if sls.VPNLastAssignedIP == "" || utility.IPToInt(sls.VPNLastAssignedIP) < utility.IPToInt(serverConfig.ServerVPNStartIP) {
> ```

this line may be too long.

---

*[public/js/services/user.js, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHk6TPMOab1hs9e9I:-KxOHk6TPMOab1hs9e9J:b-ogofg5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/public/js/services/user.js#L23)):*
> ```JavaScript
>                 serverIA: serverIA(user)
>             };
>             console.log(request);
> ```

is this a remainder debug log or intended?

---

*[python/local_gen.py, line 64 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHwlh4fbj6cn5W3R1:-KxOHwlh4fbj6cn5W3R2:b8t9bzt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/python/local_gen.py#L64)):*
> ```Python
> SCION_COORD_PATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
> DEFAULT_PACKAGE_PATH = os.path.expanduser("~/scionLabConfigs")
> DEFAULT_CORE_CERT_FILE = os.path.join(SCION_COORD_PATH, "credentials", "ISD1.crt")
> ```

Here it might sense to keep in the filename or the folder name the AS to which the cert belongs.

---

*[python/local_gen.py, line 65 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOI8qN4DMSyJnrPJej:-KxOI8qN4DMSyJnrPJek:b-2mpj0b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/python/local_gen.py#L65)):*
> ```Python
> DEFAULT_PACKAGE_PATH = os.path.expanduser("~/scionLabConfigs")
> DEFAULT_CORE_CERT_FILE = os.path.join(SCION_COORD_PATH, "credentials", "ISD1.crt")
> DEFAULT_CORE_SIG_KEY = os.path.join(SCION_COORD_PATH, "credentials", "ISD1.key")
> ```

similar as above.

---

*[utility/utility.go, line 84 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOID3ffwGJ8B9UzLVh:-KxOID3ffwGJ8B9UzLVi:beg1da9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L84)):*
> ```Go
> func ISDFromIA(ia string) int {
> 	i, _ := strconv.ParseInt(strings.Split(ia, "-")[0], 10, 64)
> 	return int(i)
> ```

is this still needed?

---

*[utility/utility.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOIGfKAiGZhooRwCAH:-KxOIGfKAiGZhooRwCAI:b-mzq9b4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L93)):*
> ```Go
> 	t, err := template.ParseFiles(templatePath)
> 	if err != nil {
> 		return fmt.Errorf("Error parsing template %v: %v", templatePath,
> ```

would probably fit in a single line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95)*

**Comment by ercanucan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[utility/utility.go, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOIxhDqtFH2YJ_8j21:-KxOIxhDqtFH2YJ_8j22:bfaxrpi) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L103)):*
> ```Go
> 		return fmt.Errorf("Error executing template file %v: %v", templatePath, err)
> 	}
> 	f.Close()
> ```

would it make sense to close the file if you are returning with an error in the above line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95)*

**Comment by mlegner** [comment]
Review status: 0 of 17 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[main.go, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOBB6KXDZBLL_-f8MP:-KxOJoLnvNccnGlUHwep:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/main.go#L38)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

an admin interface.
</blockquote></details>

Done.

---

*[README.md, line 72 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOBo_EJcun1PcfYSkf:-KxOKMd9TWDFGDS9vwnv:bbl676d) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/README.md#L72)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

As discussed, the `%` here is comes misleading. Cert and key are for ASes (ISD-AS), TRC is per ISD. 
</blockquote></details>

I reformulated this paragraph, I hope this makes it clearer.

---

*[controllers/api/user.go, line 143 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOEPK647sB9zD0XxKV:-KxOKYAJ7LLDIyWvsIsu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/controllers/api/user.go#L143)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

you could use `ACTIVE` here instead of 1.
</blockquote></details>

Done.

---

*[models/scion_lab.go, line 129 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHaFtHl7SOHXV0iDQ:-KxOKirKU_bPCqO7Wnh4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/models/scion_lab.go#L129)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

this line may be too long.
</blockquote></details>

Done.

---

*[public/js/services/user.js, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHk6TPMOab1hs9e9I:-KxOKsV3_f4NhU1zoV4Q:b-damf30) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/public/js/services/user.js#L23)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

is this a remainder debug log or intended?
</blockquote></details>

This is a remainder from debugging; i removed it as well as some comments in other js files that are not really useful.

---

*[python/local_gen.py, line 64 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOHwlh4fbj6cn5W3R1:-KxOLxt1GEIO5YtDea1m:b-j5j3ah) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/python/local_gen.py#L64)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Here it might sense to keep in the filename or the folder name the AS to which the cert belongs.
</blockquote></details>

I agree; however, that makes it more difficult to select the correct file. 
We would either have to specify the signing AS for each ISD or explicitly set the credential files for each ISD. 
What do you think?

---

*[python/local_gen.py, line 65 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOI8qN4DMSyJnrPJej:-KxOMFhluTeIkNf7SZoC:bj8bld6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/python/local_gen.py#L65)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

similar as above.
</blockquote></details>

same as above.

---

*[utility/utility.go, line 84 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOID3ffwGJ8B9UzLVh:-KxON0el6YxVHcTVimtH:bsdeequ) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L84)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

is this still needed?
</blockquote></details>

No, I replaced this with the respective function from the main SCION codebase.

---

*[utility/utility.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOIGfKAiGZhooRwCAH:-KxON6WW6tMIbiJS27ZX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L93)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

would probably fit in a single line.
</blockquote></details>

Done.

---

*[utility/utility.go, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95#-KxOIxhDqtFH2YJ_8j21:-KxONNoGfOFusG_P-2mq:b-ncv0vh) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/637b3bb3fcf39052d3f3885599494ddd6227873f/utility/utility.go#L103)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

would it make sense to close the file if you are returning with an error in the above line?
</blockquote></details>

I reordered the lines such that the file is closed irrespective of whether the Execute succeeds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/95)*

**Comment by mlegner** [comment]
Superceeded by #136.

**Pull request closed without merging**
