### PR TITLE
Use govendor in CircleCI

### PR DESCRIPTION
**Pull request by FR4NK-W**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/94)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Since #93 fails because of some unrelated change in a dependency

**Comment by chaehni** [comment]
Looks good. Added minor comments.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 20 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-KxEX3bdLdaQvf2zoC8r:-KxEX3be98jlz1Y2qvlX:bfa88ba) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/19138a6df9c64d9729846441a5855c64201f6074/.circleci/config.yml#L20)):*
> ```YAML
>          command: dockerize -wait tcp://localhost:3306 -timeout 1m
>       - run: "go get github.com/kardianos/govendor"
>       - run: "govendor sync -v"
> ```

I think the `-v` flag is not necessary since `sync` only downloads the dependencies specified in `vendor.json` anyway.

---

*[.circleci/config.yml, line 21 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-KxEXhw0za2NAED4PwXf:-KxEXhw19gqn6XZzPh_N:b-55uhfu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/19138a6df9c64d9729846441a5855c64201f6074/.circleci/config.yml#L21)):*
> ```YAML
>       - run: "go get github.com/kardianos/govendor"
>       - run: "govendor sync -v"
>       - run: "govendor install ./vendor/..."
> ```

Is this step required? I'm not completely sure but I think installed packages are not preserved between runs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-:-KxEc5Hnhxj4b7oSptxT:bxmp34f)*

**Comment by FR4NK-W** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 20 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-KxEX3bdLdaQvf2zoC8r:-KxNKSxF3Uo-BmWDtZNn:br76jls) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/19138a6df9c64d9729846441a5855c64201f6074/.circleci/config.yml#L20)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I think the `-v` flag is not necessary since `sync` only downloads the dependencies specified in `vendor.json` anyway.
</blockquote></details>

It's probably not necessary, but I think there is no draw back on being verbose here, since in CircleCI commands get collapsed and having a reminder what all the dependencies are without having to dig through to the vendor file does not harm.

---

*[.circleci/config.yml, line 21 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-KxEXhw0za2NAED4PwXf:-KxNL3r6A8zKxoR_cQ3E:bqj4xwt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/19138a6df9c64d9729846441a5855c64201f6074/.circleci/config.yml#L21)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Is this step required? I'm not completely sure but I think installed packages are not preserved between runs.
</blockquote></details>

You are right, this is not required. In the future we could use a caching step similar to how it is done in the main scion repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94)*

**Comment by FR4NK-W** [comment]
@chaehni Thanks for your feedback.|
@mlegner Updated the PR

**Comment by mlegner** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-:-KxNLyAx7w8edAGOLxR7:bg7igkv)*

**Comment by mlegner** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94)*

**Comment by FR4NK-W** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94)*

**Comment by mlegner** [comment]
@chaehni: Could you have a look at and acknowledge the changes? Then we can merge this PR.

**Comment by chaehni** [comment]
Thanks for the work! :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.circleci/config.yml, line 20 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-KxEX3bdLdaQvf2zoC8r:-KxNOlZZlct4HY0FkAbd:b1hov8e) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/19138a6df9c64d9729846441a5855c64201f6074/.circleci/config.yml#L20)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

It's probably not necessary, but I think there is no draw back on being verbose here, since in CircleCI commands get collapsed and having a reminder what all the dependencies are without having to dig through to the vendor file does not harm.
</blockquote></details>

You are right. This seems useful to have.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/94#-:-KxNOuQAXh5hamZFlmkq:bvw559a)*

**Pull request merged**
