### PR TITLE
Extended README.md

### PR DESCRIPTION
**Pull request by mlegner**
This commit adds additional details and setup instructions to the README.md.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/67)

### CODE REVIEW

**Comment by chaehni** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtHOimmIujUyBBFUinL:-KtHOimmIujUyBBFUinM:byqol0s) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/471c4f88b435a7ff314e8064474b0924ad793fee/README.md#L25)):*
> ```Markdown
> `go get github.com/kardianos/govendor`
> 
> After this step, you can go to the `scion-coor` directory (`$GOPATH/src/github.com/netsec-ethz/scion-coord`) and populate the dependencies in the `vendor` folder using:
> ```

small typo: scion-coor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Comment by mlegner** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtHOimmIujUyBBFUinL:-KtKqBrCkofgXkYNFnbN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/471c4f88b435a7ff314e8064474b0924ad793fee/README.md#L25)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

small typo: scion-coor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Comment by chaehni** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Comment by ercanucan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[README.md, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtLyva3EVvrfN5vaPyg:-KtLyva3EVvrfN5vaPyh:b-asudlq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d6800fd0303ab94315f7dbbd0c8c2d1670a5b955/README.md#L16)):*
> ```Markdown
> Download this repository as well as `netsec-ethz/scion`:
> ```
> go get github.com/netsec-ethz/scion
> ```

Here we can refer to the README in the main scion repo.

---

*[README.md, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtLzT2czVrLqeq2mTzo:-KtLzT2dRT284UFuP9aI:bfw8sg1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d6800fd0303ab94315f7dbbd0c8c2d1670a5b955/README.md#L94)):*
> ```Markdown
> ##### Populate database
> 
> At the first run, the program will create the necessary database tables. In order to work properly, you will have to manually add one tuple by connecting to MySQL as described above and then issue `INSERT INTO scion_coord_test.s_c_i_o_n_lab_server VALUES (1, "1-7", "1.1.1.1", "50000");`
> ```

As discussed offline, we can make these part of the config file the user provides.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Comment by mlegner** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtLyva3EVvrfN5vaPyg:-KtMXY4C9cJ_b_Av_fCt:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d6800fd0303ab94315f7dbbd0c8c2d1670a5b955/README.md#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Here we can refer to the README in the main scion repo.
</blockquote></details>

Done.

---

*[README.md, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-KtLzT2czVrLqeq2mTzo:-KtMXZojeggxQbWZIK_1:bmtwe09) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/d6800fd0303ab94315f7dbbd0c8c2d1670a5b955/README.md#L94)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

As discussed offline, we can make these part of the config file the user provides.
</blockquote></details>

Done. Removed this, as it will be made obsolete anyway in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67#-:-KtQzZgjJd5l5UvoKTeU:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/67)*

**Pull request merged**
