### PR TITLE
Public priv imagebuilder

### PR DESCRIPTION
**Pull request by juagargi**
This PR adds a public and private addresses for the image builder, as the coordinator is unable to see the image builder with the public address, but it must report the public one to the user web page (e.g. to get the download link)

This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221)

### CODE REVIEW

**Comment by chaehni** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[controllers/api/image_build.go, line 62 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LC-C3Wu5P9e_tha8zxa:-LC-C3Wu5P9e_tha8zxb:b6j3xrs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L62)):*
> ```Go
> }
> 
> func (c *customImage) MarshalJSON() ([]byte, error) {
> ```

I can't see where this is used.

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221)*

**Comment by juagargi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/api/image_build.go, line 62 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LC-C3Wu5P9e_tha8zxa:-LCEdM50-8jZZVLYn_lX:bgl4x16) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L62)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I can't see where this is used.
</blockquote></details>

It was not part of the changes of this PR, but I'm going to guess that whenever we serialize customImage to JSON, we'll automatically call the method. E.g. at the end of `GetUserImages`

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221)*

**Comment by chaehni** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[controllers/api/image_build.go, line 62 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LC-C3Wu5P9e_tha8zxa:-LCTuLZ1Ei6CVowsUHgf:b-o9d4pv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L62)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

It was not part of the changes of this PR, but I'm going to guess that whenever we serialize customImage to JSON, we'll automatically call the method. E.g. at the end of `GetUserImages`
</blockquote></details>

You're right. I was confused why here we use the public address for the service.

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221)*

**Comment by mlegner** [comment]
Made a pass and added some comments below. To me it is not fully clear what the different addresses are used for.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[conf/development.conf.default, line 97 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHKju0d3TlR0dZoy9:-LEEHKjv-6TgElf9bwQC:b1x1i8z) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/conf/development.conf.default#L97)):*
> ```
> ases_per_admin = 10
> 
> # For image service
> ```

It would be great to have some info here about what the different parameters are used for.

---

*[controllers/api/image_build.go, line 66 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEGCyF6m2UGVrMu3ET:-LEEGCyF6m2UGVrMu3EU:bejystr) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L66)):*
> ```Go
> 	m["image"] = c.Device
> 	m["id"] = c.JobId
> 	m["download_link"] = config.IMG_BUILD_ADDRESS_PUBLIC + "/download/" + c.JobId
> ```

Although we only use the download link here, it would be a little cleaner to have a function that builds the url such that we can more easily reuse and change it.

---

*[controllers/api/image_build.go, line 160 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHTH6COoiK3TledW9:-LEEHTH6COoiK3TledWA:bdjt5ig) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L160)):*
> ```Go
> 
> func (s *SCIONImgBuildController) GetAvailableDevices(w http.ResponseWriter, r *http.Request) {
> 	resp, err := http.Get(config.IMG_BUILD_ADDRESS_INTERNAL + "/get-images")
> ```

Separate function (or here simple constant) that constructs the URL?

---

*[controllers/api/image_build.go, line 252 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHYJlBkLlNc_fqs-Q:-LEEHYJlBkLlNc_fqs-R:b-3kbcjq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L252)):*
> ```Go
> 	writer.Close()
> 
> 	url := config.IMG_BUILD_ADDRESS_INTERNAL + "/create/" + bRequest.ImageName
> ```

Separate function that constructs the URL?

---

*[controllers/api/image_build.go, line 331 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHiXe3CC7Cyfa9IqW:-LEEHiXe3CC7Cyfa9IqX:b-3kbcjq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L331)):*
> ```Go
> func getJobStatus(id string) (bool, bool, error) {
> 	status := &jobStatus{}
> 	err := getJson(config.IMG_BUILD_ADDRESS_INTERNAL+"/status/"+id, status)
> ```

Separate function that constructs the URL?

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-:-LEEHkJoBk0wRz5FRQNZ:b-xy991m)*

**Comment by mlegner** [comment]
Another general comment: PR descriptions are much appreciated. :smile:

**Comment by juagargi** [comment]
Holy cow, I hadn't left even one comment. Now I added a small explanation of what the PR is doing.

---

Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LERGIdp9dWqwK0MIkBw:-LERGIdp9dWqwK0MIkBx:bn8gvop) (no related file):*
After the changes and solving the conflicts from this PR and master, it needs another test. One of the reviewers should run again this branch and test the communication with the image builder.

---

*[conf/development.conf.default, line 97 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHKju0d3TlR0dZoy9:-LERFtzJEloRJ5BARntl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/conf/development.conf.default#L97)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

It would be great to have some info here about what the different parameters are used for.
</blockquote></details>

Done.

---

*[controllers/api/image_build.go, line 66 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEGCyF6m2UGVrMu3ET:-LERI4YEDeMUL9bx6CKy:b-26ky19) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L66)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Although we only use the download link here, it would be a little cleaner to have a function that builds the url such that we can more easily reuse and change it.
</blockquote></details>

I thought about it, and now I think it seems simpler to leave it like this, until we have a second use for it.

---

*[controllers/api/image_build.go, line 160 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHTH6COoiK3TledW9:-LERIcGrDCwjxPwsoshJ:b-2zaooi) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L160)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Separate function (or here simple constant) that constructs the URL?
</blockquote></details>

I think it looks simpler just doing it in plain sight. If we have other uses we can refactor the code.

---

*[controllers/api/image_build.go, line 252 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHYJlBkLlNc_fqs-Q:-LERIlTwEx5uQF6QYId9:b-mxa5ec) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L252)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Separate function that constructs the URL?
</blockquote></details>

Same as above, if we have more uses we could refactor the code. For now it seems more understandable just to append the trailing part here, without the need to understand what another function is doing.

---

*[controllers/api/image_build.go, line 331 at r1](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-LEEHiXe3CC7Cyfa9IqW:-LERIwge-qTLMz3TyVUP:b2nregs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/600f8936a41c5a5db3d35fdb1a322e421e13771b/controllers/api/image_build.go#L331)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Separate function that constructs the URL?
</blockquote></details>

Same as above 

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-:-LERFL5m3OHwzsbKfMCN:b-o8sx4g)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/221#-:-LETm7dD5_wgZ5pgnUv6:bnfp4nl)*

**Pull request merged**
