### PR TITLE
Improvements to user interface and emails

### PR DESCRIPTION
**Pull request by mlegner**
This PR addresses issue #125 and improves other aspects of the UI and emails.
Improved information on user page, moved AccountID and Secret to admin page.
Show email message on admin page.
Show correct HTTP protocol in email links.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/132)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-L-jvem6OEJ4IZsnDuvB:-L-jvem7zNRWuMobkJi3:bbq5c0k) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54030ca924868ec55c198231a0266db32ab0863b/public/partials/user.html#L75)):*
> ```HTML
>     {{message}}
>   </div>
> </form>
> ```

Is this a typo? I cannot see which form this tag closes, the scionLabVMForm form is already closed on line 68.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-:-L-jvwVLMuNRp71znde0:bnfp4nl)*

**Comment by mlegner** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[public/partials/user.html, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-L-jvem6OEJ4IZsnDuvB:-L-jzbUGE89dls1gv7DU:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/54030ca924868ec55c198231a0266db32ab0863b/public/partials/user.html#L75)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Is this a typo? I cannot see which form this tag closes, the scionLabVMForm form is already closed on line 68.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132)*

**Comment by mlegner** [comment]
@fr4nk-w I fixed the error and rebased the PR. Could you resolve the open discussion?

---

Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-:-L-k9j-NORZt7Pg7LByU:b-f7f30a)*

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: 6 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-:-L-ozIrM4sYr1X7Ls9sa:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/132#-:-L-p1xaRJME2_AXS--uk:bnfp4nl)*

**Pull request merged**
