### PR TITLE
New as credential ctor, bugfix

### PR DESCRIPTION
**Pull request by juagargi**
This builds on top of some Markus' changes.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/174)

### CODE REVIEW

**Comment by hausheer** [comment]
I tested the new ASCredential constructor commit and it worked perfectly for me

**Comment by hausheer** [comment]
Could you provide quick instructions how the 78ccef0 commit can be tested?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/174#-:-L6Wxk80zcEpQfAX0Lo9:b-v4ux63)*

**Comment by juagargi** [comment]
To test the change in GetFreeID / GetAvailableID , you can create two ASes using VPN and both will have the same BR id and same IP before the fix, and different ones after the fix.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/174#-:-L6XDZDdZ99X7-ZBYDqB:bretllv)*

**Comment by mlegner** [comment]
:lgtm: Thank you for the ID bugfix and tests!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/174#-:-L6b4dIe4vD6u18C5HQd:bc6mxan)*

**Comment by mlegner** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/174)*

**Pull request merged**
