### PR TITLE
Password reset option

### PR DESCRIPTION
**Pull request by mlegner**
Allow users who forgot their password to reset it.
This uses the password set page implemented for the pre-approved registration and also makes use
of the tollbooth function used for the resending of the verification link.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/123)

### CODE REVIEW

**Comment by mlegner** [comment]
This is not a very important PR; I had implemented the code some time ago and decided to rebase it now before it gets completely out of date.
One idea would be to implement the verification-link resending in the same way in order to stay consistent.
What do you think, @chaehni ?

**Comment by chaehni** [comment]
Thank you for this very useful feature. I made a pass and have some comments:

There is a bug in login.go Login() function at line 126: If a user has reset his password and then tries to log in, there is a nil pointer dereference because the error passed to c.Forbidden() is nil. The error verbosity PR addresses these issues but we might still want to pass a non-nil error such that this case gets handled on the web interface.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[main.go, line 168 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HOglhRezSF6EQo9L8:-L-HOglhRezSF6EQo9L9:bqa9288) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/main.go#L168)):*
> ```Go
> 
> 	// Reset user password
> 	router.Handle("/api/resetPassword", tollbooth.LimitHandler(resendLimit, loggingChain.ThenFunc(
> ```

Did you choose the same limiter here on purpose? Like this, a  user having resent his verification link can't request a new password without waiting. However, this is probably not a big issue.

---

*[public/js/controllers/login.js, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HRJaMnWpqq7RGF4C9:-L-HRJaMnWpqq7RGF4CA:b-n8jcvk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/controllers/login.js#L26)):*
> ```JavaScript
>                                 break;
>                             default:
>                                 err = "Failed to log you in: Make sure your email address and password are correct and your email address is verified.";
> ```

We should handle the case where the password is empty. (Probably same case as 'Password Invalid'). See my comment at the top.
Also, we could clear the message box in that case.

---

*[public/js/controllers/login.js, line 41 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HAJ4qiiCeX2Z-nvCl:-L-HAJ4qiiCeX2Z-nvCm:b1die87) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/controllers/login.js#L41)):*
> ```JavaScript
>                     function (response) {
>                         console.log(response);
>                         $scope.error = "An error occurred during the password reset procedure.";
> ```

Here we could tell the user what the error was.  For example that one needs to wait 10 minutes to send another email.  This would enable users to resolve the problem themselves.

---

*[public/js/services/login.js, line 18 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HQ79q86A507938-iD:-L-HQ79r7ge1G3_TBQi0:b-2yyylm) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/services/login.js#L18)):*
> ```JavaScript
>             },
>             resetPassword: function (email) {
>                 return $http.post('/api/resetPassword?userEmail=' + email).then(function (response) {
> ```

Wouldn't the 'application/x-www-form-urlencoded' be more appropriate here?

---

*[public/partials/login.html, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HTSYAbfDL3MZCkNxI:-L-HTSYAbfDL3MZCkNxJ:b-umgj90) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/partials/login.html#L8)):*
> ```HTML
>     <p class="login-box-msg">Sign in to start your session</p>
> 
>     <div ng-show="error" class="alert alert-danger alert-dismissible fade in">
> ```

Could you make the alerts on the other views dismissible as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-:-L-HG6cC_f-1M0ChfVpl:bak0krz)*

**Comment by mlegner** [comment]
@chaehni Thank you for the valuable feedback. I have updated the PR accordingly.
I changed the code with the nil pointer dereference and added an explicit error that is also then used by the frontend.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[main.go, line 168 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HOglhRezSF6EQo9L8:-L-VRqRiKDmJ1zvlpVhM:b-g1br5c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/main.go#L168)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Did you choose the same limiter here on purpose? Like this, a  user having resent his verification link can't request a new password without waiting. However, this is probably not a big issue.
</blockquote></details>

I thought that both essentially have the same kind of functionality (sending an email to the user) and could therefore use the same limiter. If you prefer, I can add an additional limiter.

---

*[public/js/controllers/login.js, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HRJaMnWpqq7RGF4C9:-L-Vb73KagAKD5SoopQL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/controllers/login.js#L26)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

We should handle the case where the password is empty. (Probably same case as 'Password Invalid'). See my comment at the top.
Also, we could clear the message box in that case.
</blockquote></details>

Done.

---

*[public/js/controllers/login.js, line 41 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HAJ4qiiCeX2Z-nvCl:-L-VUKOudaI2WRQZ3BHi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/controllers/login.js#L41)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Here we could tell the user what the error was.  For example that one needs to wait 10 minutes to send another email.  This would enable users to resolve the problem themselves.
</blockquote></details>

Done.

---

*[public/js/services/login.js, line 18 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HQ79q86A507938-iD:-L-VUv8hLLWt_JCT1Sey:b-8p1cru) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/services/login.js#L18)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Wouldn't the 'application/x-www-form-urlencoded' be more appropriate here?
</blockquote></details>

Currently, we are using a number of different ways to create post requests.
I guess it would make sense to use a consistent method for all of those requests and I guess 'application/x-www-form-urlencoded' would make the most sense. Maybe we could do this in a separate refactoring PR?

---

*[public/partials/login.html, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HTSYAbfDL3MZCkNxI:-L-V_2VPX6pw2OnHRn6h:bz9x3i4) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/partials/login.html#L8)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Could you make the alerts on the other views dismissible as well?
</blockquote></details>

Done. There is now some code duplication, maybe we can find a way to reduce this a little in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-:-L-VbA98XaYs0f4zs7VD:b-z2i0ht)*

**Comment by mlegner** [comment]
@chaehni I have rebased the PR onto the current master including your error-verbosity-PR.
Could you have a look again?

**Comment by chaehni** [comment]
Made a pass. One comment left.

---

Review status: 7 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 168 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HOglhRezSF6EQo9L8:-L-krdQJF_qTioW45wFw:bwb9w0j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/main.go#L168)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I thought that both essentially have the same kind of functionality (sending an email to the user) and could therefore use the same limiter. If you prefer, I can add an additional limiter.
</blockquote></details>

Makes sense. We can leave it as it is.

---

*[controllers/api/login.go, line 124 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-ktmpLdHbyx8m_P5xa:-L-ktmpLdHbyx8m_P5xb:b-hp7kdq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/66bca2e42942be63b07ac38191939ddf22834932/controllers/api/login.go#L124)):*
> ```Go
> 	if dbUser.PasswordInvalid {
> 		log.Printf("Password is not set for user %v.", dbUser.Email)
> 		c.Forbidden(w, err, "902 Password is not set for user %v", dbUser.Email)
> ```

The 'err' variable in this call to Forbidden() is still nil, right? We could explicitly pass nil here to prevent confusion.

---

*[public/js/services/login.js, line 18 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-HQ79q86A507938-iD:-L-ksCduFcC_uLD0Cs7l:b8samkf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/0b720a74d82212251111bdcb52530e608cdcb4a8/public/js/services/login.js#L18)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Currently, we are using a number of different ways to create post requests.
I guess it would make sense to use a consistent method for all of those requests and I guess 'application/x-www-form-urlencoded' would make the most sense. Maybe we could do this in a separate refactoring PR?
</blockquote></details>

I agree. We can do this in a new PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-:-L-kuUW29Qyoj1E6alQD:bp5ikf8)*

**Comment by mlegner** [comment]
@chaehni Thanks, I fixed the last issue.

---

Review status: 7 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/login.go, line 124 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-L-ktmpLdHbyx8m_P5xa:-L-kvDABtBl220wD68hW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/66bca2e42942be63b07ac38191939ddf22834932/controllers/api/login.go#L124)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

The 'err' variable in this call to Forbidden() is still nil, right? We could explicitly pass nil here to prevent confusion.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-:-L-kvO0gg6vbD2Qi2555:b-f2x5w1)*

**Comment by chaehni** [comment]
:lgtm:

---

Review status: 7 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123#-:-L-kwu0XVAfZdlSLT5sz:bnfp4nl)*

**Comment by chaehni** [comment]
Reviewed 1 of 11 files at r1, 12 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/123)*

**Pull request merged**
