### PR TITLE
Activation-Link resending

### PR DESCRIPTION
**Pull request by chaehni**
This PR adds functionality to resend the user activation link in case of loss.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/51)

### CODE REVIEW

**Comment by mlegner** [comment]
Thanks for this nice feature. I tested it locally and everything works very well for me.
I only have one comment/question: We might run into trouble if someone (maliciously or accidentally) keeps requesting emails. Maybe it would be nice to have some kind of counter or timeout, which prevents this. What do you think?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KswYq-jPehTJ0cWbq8K:bcljcyk)*

**Comment by chaehni** [comment]
This is an issue I wanted to discuss. Emails can only be to an email address that is in the database and not yet verified. Therefore it can hardly be used to spam someone else. However, a user could spam his own inbox which might still be a problem for us. With some overhead it's possible to rate limit the sending but because users are normally not patient enough to wait for minutes and Postmark has this "immediate delivery" guarantee I wanted to discuss that first.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KswgGLF6eAb6sJ6n2fp:b6pdajr)*

**Comment by chaehni** [comment]
Link resending is now rate limited  based on IP addresses as discussed in todays meeting. It might need adjustments based on proxy setup. (nginx?)
I also moved the file existence check in the main() function to a dedicated init() function.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KtHxao6qW7l_Y5VuSuS:b-fftf2b)*

**Comment by mlegner** [comment]
The rate limiting is a really cool feature that worked well for me after some small issues with the govendor-installed packages (see below).
Also, I added a comment concerning the init function.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtKlldCQrDGhAIcXAdL:-KtKlldCQrDGhAIcXAdM:brd41jc) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/71c18e78c4a434e0deb0cf7e01f056f8a455a5b8/main.go#L33)):*
> ```Go
> )
> 
> func init() {
> ```

The problem with the init function is that it does not abort the program after an error. This was my original reason why to put these checks into the main function.

---

*[vendor/vendor.json, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtKkfHpO23H8rXhIZpZ:-KtKkfHrCauy28R4NpjL:b-1wp7sv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/71c18e78c4a434e0deb0cf7e01f056f8a455a5b8/vendor/vendor.json#L25)):*
> ```JSON
> 		{
> 			"checksumSHA1": "QlXKfAzQy+s0+dSHaSs/ASvu+Ik=",
> 			"path": "github.com/didip/tollbooth/limiter",
> ```

I had to install additional packages: "github.com/didip/tollbooth", "github.com/patrickmn/go-cache", "golang.org/x/time/rate". Maybe you had some of them installed globally?
Also, there is now a new version of tollbooth, where some function names are changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KtKp50HAMYufvmx7JMR:b-8wfbzy)*

**Comment by chaehni** [comment]
I updated the rate limiting to work with the newest tollbooth version. I also added token bucket expiration such that memory is not occupied forever.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtKlldCQrDGhAIcXAdL:-KtLChCC-iJr10gB3LDp:b-rcny2r) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/71c18e78c4a434e0deb0cf7e01f056f8a455a5b8/main.go#L33)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

The problem with the init function is that it does not abort the program after an error. This was my original reason why to put these checks into the main function.
</blockquote></details>

I see. Added a check to the main function. 

---

*[vendor/vendor.json, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtKkfHpO23H8rXhIZpZ:-KtLCwaaegoGqv7v7L5t:burwmq0) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/71c18e78c4a434e0deb0cf7e01f056f8a455a5b8/vendor/vendor.json#L25)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I had to install additional packages: "github.com/didip/tollbooth", "github.com/patrickmn/go-cache", "golang.org/x/time/rate". Maybe you had some of them installed globally?
Also, there is now a new version of tollbooth, where some function names are changed.
</blockquote></details>

Thanks for the hint. My govendor setup was not correct. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KtLD7scL6sNMt2MnPoO:b-htlmta)*

**Comment by ercanucan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[main.go, line 65 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWAwrHBU31oWesG7S:-KtQVuDp16COnLIR4SWZ:b-cghmy3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L65)):*
> ```Go
> 
> 	// rate limitation
> 	resendLimit := tollbooth.NewLimiter(1, time.Minute*10, &limiter.ExpirableOptions{DefaultExpirationTTL: time.Hour})
> ```

Please don't have lines that are longer than 100 chars.

---

*[main.go, line 66 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWJ1mIQ7eUEegtooK:-KtQWJ1mIQ7eUEegtooL:b-5h08c7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L66)):*
> ```Go
> 	// rate limitation
> 	resendLimit := tollbooth.NewLimiter(1, time.Minute*10, &limiter.ExpirableOptions{DefaultExpirationTTL: time.Hour})
> 	resendLimit.SetRejectFunc(func() { log.Printf("A request to '/api/resendLink' was blocked due to rate limitation") })
> ```

same here.

---

*[main.go, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWObPKO0ST23_p8KL:-KtQWObPKO0ST23_p8KM:b-5h08c7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L94)):*
> ```Go
> 	router.Handle("/api/captchaSiteKey", loggingChain.ThenFunc(registrationController.LoadCaptchaSiteKey))
> 	// Resend verification email
> 	router.Handle("/api/resendLink", tollbooth.LimitHandler(resendLimit, loggingChain.ThenFunc(registrationController.ResendActivationLink))).Methods("POST")
> ```

same here.

---

*[controllers/api/register.go, line 172 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWzr-LFU6ChK73I2Z:-KtQWzr0SNZ9o9qzIVFj:bjlz3r5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/controllers/api/register.go#L172)):*
> ```Go
> 	user, err := models.FindUserByEmail(r.PostFormValue("email"))
> 	if err != nil {
> 		c.Error500(err, w, r)
> ```

Here I would return a better error that user can understand. Similar to the one below in `user.Verified` block.

---

*[public/js/controllers/login.js, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQXSa9KWt62cP0aQSi:-KtQXSa9KWt62cP0aQSj:bxn7qc7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/js/controllers/login.js#L25)):*
> ```JavaScript
> 
>                     loginService.resendEmail(email).then(function (response){
>                         $scope.message = "Verification email resent";
> ```

We should specify to which address the email was sent.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KtQYcnsqhPqLyPstKDg:b351ik6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
> ```HTML
>     
>     <br>
>     <div><a href="" class="text-center" ng-click="resendEmail(user.email)">Resend verification email</a></div>
> ```

After trying this out a little bit more, I think that placing the link here in the main registration page is not a good idea. It pollutes the page unnecessarily. As discussed with @mlegner what we should do is the following: When a user tries to login to his account and his account is not yet verified, then we would show a message (or a page), saying that this account is not yet activated; and at the same page show the link to re-send the verification email.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by chaehni** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KtQfMbOsZhxeeaElaUY:b-kmdttd) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

After trying this out a little bit more, I think that placing the link here in the main registration page is not a good idea. It pollutes the page unnecessarily. As discussed with @mlegner what we should do is the following: When a user tries to login to his account and his account is not yet verified, then we would show a message (or a page), saying that this account is not yet activated; and at the same page show the link to re-send the verification email.
</blockquote></details>

I agree that overall this is the cleaner solution. However, my concern with a separate page was, that the feature becomes a lot less discoverable since it is hidden behind the login mask. Users might try to sign up a second time to get the email instead. We should have this separate page but I still think there should be a prominently placed link to it. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by ercanucan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KtQyfIPU57ASLi9WMIB:buzdq3n) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I agree that overall this is the cleaner solution. However, my concern with a separate page was, that the feature becomes a lot less discoverable since it is hidden behind the login mask. Users might try to sign up a second time to get the email instead. We should have this separate page but I still think there should be a prominently placed link to it. What do you think?
</blockquote></details>

OK, I see that point. We discussed offline with @mlegner. We can keep it this way but at least, what we should do is to put the link to the right side of the page (not on top of the "Register a new account"). The link should say something like "Resend account activation email" so that it's very clear for the users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by chaehni** [comment]
Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[main.go, line 65 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWAwrHBU31oWesG7S:-Ktk2a9gk-aA6CXuehpU:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L65)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Please don't have lines that are longer than 100 chars.
</blockquote></details>

Done.

---

*[main.go, line 66 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWJ1mIQ7eUEegtooK:-Ktk2bQJXw3N6-PJPNs5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L66)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.

---

*[main.go, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWObPKO0ST23_p8KL:-Ktk3TCpWPqKPczon95b:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/main.go#L94)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.

---

*[controllers/api/register.go, line 172 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQWzr-LFU6ChK73I2Z:-KtkIbsNE9rJLmBbPI4h:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/controllers/api/register.go#L172)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Here I would return a better error that user can understand. Similar to the one below in `user.Verified` block.
</blockquote></details>

Done.

---

*[public/js/controllers/login.js, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQXSa9KWt62cP0aQSi:-Ktv_4z1-2_y2TTdvD5A:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/js/controllers/login.js#L25)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

We should specify to which address the email was sent.
</blockquote></details>

Done.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KuStTPyOYQ_cZOpqddO:bfk20gy) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

OK, I see that point. We discussed offline with @mlegner. We can keep it this way but at least, what we should do is to put the link to the right side of the page (not on top of the "Register a new account"). The link should say something like "Resend account activation email" so that it's very clear for the users.
</blockquote></details>

I implemented the new page as you described it. However, I'm really not sure where to put the resend link such that it not pollutes the page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by ercanucan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KuZ24LXm5u85Um6RHHf:b-i8scfg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I implemented the new page as you described it. However, I'm really not sure where to put the resend link such that it not pollutes the page.
</blockquote></details>

I would place this link to right bottom of the page. It should be okay as long as it's not very close to the register new account link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by ercanucan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[vendor/vendor.json, line 25 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KuZFB5c2NShquJY_kS6:-KuZFB5eaaJw_OLrbqb6:b-7fvzo5) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/828109adb14cd7f7d2ae100055995ce2acbf385b/vendor/vendor.json#L25)):*
> ```JSON
> 		{
> 			"checksumSHA1": "LWSc/x0uRpsG/Q5yi6X6tkx1QQA=",
> 			"path": "github.com/didip/tollbooth",
> ```

@chaehni : With the updated tollbooth repo, we have observing some build issues locally. Have you observed this before? Both @mlegner and I can reproduce this:
```# github.com/netsec-ethz/scion-coord/vendor/github.com/didip/tollbooth
vendor/github.com/didip/tollbooth/tollbooth.go:40: lmt.GetForwardedForIndexFromBehind undefined (type *limiter.Limiter has no field or method GetForwardedForIndexFromBehind)
vendor/github.com/didip/tollbooth/tollbooth.go:40: too many arguments in call to libstring.RemoteIP
	have ([]string, <T>, *http.Request)
	want ([]string, *http.Request)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by chaehni** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[public/partials/login.html, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KtQYcnrWMwV18koa-Cg:-KuZo0tVJt5XBzeCxJj9:b5nt5bt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/c55d738497220e6a0d144308808c3f18d46ec60b/public/partials/login.html#L44)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would place this link to right bottom of the page. It should be okay as long as it's not very close to the register new account link.
</blockquote></details>

I placed the link at the bottom right. Similar to the footer.

---

*[vendor/vendor.json, line 25 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KuZFB5c2NShquJY_kS6:-KuZoHaynVKxatwITyyF:b1owdr2) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/828109adb14cd7f7d2ae100055995ce2acbf385b/vendor/vendor.json#L25)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

@chaehni : With the updated tollbooth repo, we have observing some build issues locally. Have you observed this before? Both @mlegner and I can reproduce this:
```# github.com/netsec-ethz/scion-coord/vendor/github.com/didip/tollbooth
vendor/github.com/didip/tollbooth/tollbooth.go:40: lmt.GetForwardedForIndexFromBehind undefined (type *limiter.Limiter has no field or method GetForwardedForIndexFromBehind)
vendor/github.com/didip/tollbooth/tollbooth.go:40: too many arguments in call to libstring.RemoteIP
	have ([]string, <T>, *http.Request)
	want ([]string, *http.Request)
```
</blockquote></details>

I sorted out the dependency problem.  The code for tollbooth was changed once again.  The code should now work with the revisions specified in vendor.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by mlegner** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[vendor/vendor.json, line 25 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-KuZFB5c2NShquJY_kS6:-Ku_07Rfiv1yTVdPEAYS:b-7eg291) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/828109adb14cd7f7d2ae100055995ce2acbf385b/vendor/vendor.json#L25)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

I sorted out the dependency problem.  The code for tollbooth was changed once again.  The code should now work with the revisions specified in vendor.json
</blockquote></details>

It works for me now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by ercanucan** [comment]
:lgtm: (please squash your commits)

---

Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51#-:-KudrmS6Ty9aG0i2g_k-:b-dl203u)*

**Comment by ercanucan** [comment]
Reviewed 7 of 12 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/51)*

**Comment by ercanucan** [comment]
@chaehni @mlegner please resolve the "open discussions" in this PR

**Pull request merged**
