### PR TITLE
Dedicated boxes readme

### PR DESCRIPTION
**Pull request by juagargi**
The label for dedicated systems now reads
Install on a dedicated SCION system (for experts)

Also we deploy now a README.md file with the gen folder.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/210)

### CODE REVIEW

**Comment by mlegner** [comment]
Good idea to add some documentation to the dedicated systems. I also like the new utility function.
Please have a look at the two comments below.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[files/dedicated_box/README.md, line 1 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-L9p9a2l4UGTo4ExWMtn:-L9p9a2l4UGTo4ExWMto:b-io6c8j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b823585a1e170236c0da11a8fc8c948f6ab8a0e/files/dedicated_box/README.md#L1)):*
> ```Markdown
> # SCIONLab Dedicated
> ```

I'm not completely convinced about the directory structure. Could we maybe combine the new `files` directory with the `scripts`?

---

*[utility/utility.go, line 54 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-L9pAcArEDAr5ssW42dr:-L9pAcArEDAr5ssW42ds:bse7n6c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b823585a1e170236c0da11a8fc8c948f6ab8a0e/utility/utility.go#L54)):*
> ```Go
> // CopyPath copies the src path to dst. Example: CopyPath("/tmp/a", "/tmp/b") will copy /tmp/a/* to /tmp/b/
> // replacing contents if files or dirs existed in b with the same names as a/*
> func CopyPath(src, dst string) error {
> ```

I guess we could use this function in some other places as well. Maybe we have to modify some directory structures.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-:-L9pAkSd5FHXpPdhI2dw:bsodgsx)*

**Comment by juagargi** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[files/dedicated_box/README.md, line 1 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-L9p9a2l4UGTo4ExWMtn:-L9pSLHS5dwgeJ3V_Gg-:b-okr6tt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b823585a1e170236c0da11a8fc8c948f6ab8a0e/files/dedicated_box/README.md#L1)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I'm not completely convinced about the directory structure. Could we maybe combine the new `files` directory with the `scripts`?
</blockquote></details>

We have now the installation files also under ./files/

---

*[utility/utility.go, line 54 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-L9pAcArEDAr5ssW42dr:-L9pSSgLAo-GMOzq3iXz:b-sdzkx6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b823585a1e170236c0da11a8fc8c948f6ab8a0e/utility/utility.go#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I guess we could use this function in some other places as well. Maybe we have to modify some directory structures.
</blockquote></details>

yes. The idea would be to start using the function as soon as we have something to add. The current structure only has install-coordinator and dedicated_box, and we could extend it with a VM directory, that would contain what ./vagrant/ contains now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210)*

**Comment by mlegner** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utility/utility.go, line 54 at r1](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210#-L9pAcArEDAr5ssW42dr:-L9uTp6NCjQrK2iFk-KP:b-iiu93d) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4b823585a1e170236c0da11a8fc8c948f6ab8a0e/utility/utility.go#L54)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

yes. The idea would be to start using the function as soon as we have something to add. The current structure only has install-coordinator and dedicated_box, and we could extend it with a VM directory, that would contain what ./vagrant/ contains now.
</blockquote></details>

OK, sounds good. Let's keep this in mind.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210)*

**Comment by juagargi** [comment]
Reviewed 4 of 18 files at r1, 9 of 9 files at r2, 1 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/210)*

**Pull request merged**
