### PR TITLE
Added unified installation script, updated Vagrant file

### PR DESCRIPTION
**Pull request by xabarass**
Issue discussed in #114

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/130)

### CODE REVIEW

**Comment by mlegner** [comment]
@xabarass Thank you for this elegant solution to install and set up SCION; it looks good to me in general.
I have made a pass and added some minor comments below.
An additional suggestion: Do you think you could include some mechanism to keep the installation up to date (see issue #83) as well? Or should we do this in a separate PR?

---

Review status: 0 of 2 files reviewed at latest revision, 19 unresolved discussions.

---

*[scion_install_script.sh, line 5 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-ViQ4sv79RqEzjSKDR:-L-ViQ4sv79RqEzjSKDS:b-fb6ort) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L5)):*
> ```Shell
> shopt -s nullglob
> 
> usage="$(basename "$0") [-p PATCH_DIR] [-g GEN_DIR] [-v VPN_CONF_PATH] [-s SCION_SERVICE] [-z SCION_VI_SERVICE]
> ```

Line is too long.

---

*[scion_install_script.sh, line 12 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vido1PDVwvHcqZNbg:-L-Vido1PDVwvHcqZNbh:bx9528z) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L12)):*
> ```Shell
>     -v VPN_CONF_PATH    path to OpenVPN configuration file
>     -s SCION_SERVICE    path to SCION service file
>     -z SCION_VI_SERVICE path to SCION viz service file"
> ```

*SCION_VIZ_SERVICE*
In my opinion we should hyphenate SCION-viz, but that's maybe a matter of taste.

---

*[scion_install_script.sh, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vj4xtAvcbZoFsTP48:-L-Vj4xtAvcbZoFsTP49:b-9za73t) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L51)):*
> ```Shell
> echo "Starting SCION installation..."
> 
> sudo apt-get -y update
> ```

We should probably check somewhere that this is indeed a Ubuntu or Ubuntu-like system and print an error message otherwise.

---

*[scion_install_script.sh, line 81 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VkGbUhsA7WjCaQn2p:-L-VkGbUhsA7WjCaQn2q:be3w68f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L81)):*
> git config user.names
On my system it is `user.name`

---

*[scion_install_script.sh, line 91 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VjtBlzVdbRY96GTQq:-L-VjtBlzVdbRY96GTQr:bt924qq) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L91)):*
> ```Shell
>     fi
> 
>     git commit -am "Modified to compile on ARM systems"
> ```

Are the patches only used for ARM systems? Maybe we could use a more general message here.

---

*[scion_install_script.sh, line 102 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VkaqGgOv_RyZy0L1k:-L-VkaqGgOv_RyZy0L1l:bevx2pg) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L102)):*
> ```Shell
> # Check if gen directory exists
> if  [[ ( ! -z ${gen_dir+x} ) && -d ${gen_dir} ]]
> then  
> ```

Remove trailing spaces.

---

*[scion_install_script.sh, line 104 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VkcRd3eTe3i4Wa8ub:-L-VkcRd3eTe3i4Wa8uc:bu6zy3s) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L104)):*
> ```Shell
> then  
>     echo "Gen directory is specified! Using content from there!"
>     
> ```

Maybe remove empty line.

---

*[scion_install_script.sh, line 108 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VkemqT5visM9yKBrI:-L-VkemqT5visM9yKBrJ:bu6zy3s) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L108)):*
> ```Shell
> else
>     echo "Gen directory is NOT specified! Generating local (Tiny) topology!"
>     
> ```

Maybe remove empty line.

---

*[scion_install_script.sh, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VjTThFCgnuN37sEbf:-L-VjTTiCgLxaPVqmp0y:b-mwztmp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L118)):*
> ```Shell
> python3 ./manage.py migrate
> 
> echo "alias cdscion='cd $SC'" >> ~/.bash_aliases
> ```

We could make these aliases conditional on a option. Maybe not everybody wants them set up or they don't actually use the `.bash_aliases` file.

---

*[scion_install_script.sh, line 135 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VkppwbJ9X2zlRCfs8:-L-VkppwbJ9X2zlRCfs9:bqr0e1c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L135)):*
> ```Shell
> if  [[ ( ! -z ${scion_service_path+x} ) && -r ${scion_service_path} ]]
> then
>     echo "Registring SCION as startup service"
> ```

*Registering*

---

*[scion_install_script.sh, line 138 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vl3xUuFBawaMMFUmN:-L-Vl3xUuFBawaMMFUmO:brm79bv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L138)):*
> ```Shell
> 
>     cp "$scion_service_path" tmp.service
>     # We need to replace ubuntu user with current username
> ```

We could change the service files so that they have a placeholder there, that would maybe be a cleaner solution.

---

*[scion_install_script.sh, line 152 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vkue1KsJyi8XN101H:-L-Vkue1KsJyi8XN101I:bqr0e1c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L152)):*
> ```Shell
> if  [[ ( ! -z ${scion_viz_service+x} ) && -r ${scion_viz_service} ]]
> then
>     echo "Registring SCION viz as startup service"
> ```

*Registering*

---

*[scion_install_script.sh, line 155 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VlGnwVvuJ4O442MnU:-L-VlGnwVvuJ4O442MnV:b2nreh6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L155)):*
> ```Shell
> 
>     cp "$scion_viz_service" tmp.service
>     # We need to replace ubuntu user with current username
> ```

Same as above.

---

*[scion_install_script.sh, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vi4IootxHUPYsPs3L:-L-Vi4IootxHUPYsPs3M:b-c5yjo8) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L162)):*
> ```Shell
>     sudo systemctl start scion-viz.service
> else
>     echo "SCION viz systemd service file not specified! SCION won't run automatically on startup."
> ```

*SCION viz* won't run [...]

---

*[scion_install_script.sh, line 163 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VgusqZN3pkG3w0K76:-L-VgusrPvrjLP3STMCG:b9ogp69) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L163)):*
> ```Shell
> else
>     echo "SCION viz systemd service file not specified! SCION won't run automatically on startup."
> fi
> ```

Newline missing.

---

*[vagrant/Vagrantfile, line 10 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VhDBLw1NMSGkK9rz2:-L-VhDBLw1NMSGkK9rz3:baud90b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/vagrant/Vagrantfile#L10)):*
> ```Ruby
>     wget https://raw.githubusercontent.com/netsec-ethz/scion-coord/master/scion_install_script.sh
>     chmod +x scion_install_script.sh
>     echo "Install script downloaded, running it"
> ```

Maybe add "..." to be consistent with above.

---

*[vagrant/Vagrantfile, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VhHlvr1pHikvYPAuL:-L-VhHlwVhcBTxEuCYsd:b-lxrt39) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/vagrant/Vagrantfile#L11)):*
> ```Ruby
>     chmod +x scion_install_script.sh
>     echo "Install script downloaded, running it"
> ```

Remove unnecessary newline.

---

*[vagrant/Vagrantfile, line 12 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vh6aTXEMKWK7epxjJ:-L-Vh6aTXEMKWK7epxjK:b-hkpu1j) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/vagrant/Vagrantfile#L12)):*
> ```Ruby
>     echo "Install script downloaded, running it"
> 
>     ./scion_install_script.sh -g /vagrant/gen/ -v /vagrant/client.conf -s /vagrant/scion.service -z /vagrant/scion-viz.service
> ```

Please keep lines to a maximum of 100 characters

---

*[vagrant/Vagrantfile, line 44 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-VlVke5_oeSebgZk6E:-L-VlVke5_oeSebgZk6F:b48ivbs) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/ad61a9220df700a8f3b7c186679cd64b271ad678/vagrant/Vagrantfile#L44)):*
> ```Ruby
>   $setup_systemd_service = <<-SCRIPT
>     cp /vagrant/scion.service /vagrant/scion-viz.service /etc/systemd/system/
>     echo "RemoveIPC=no" >> /etc/systemd/logind.conf
> ```

This is important in some cases (in particular for VMs) as otherwise user-created sockets are removed on logout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-:-L-VhY3H7ybWCcv49Mtq:b-e9hll6)*

**Comment by xabarass** [comment]
Everything should be fixed

**Comment by mlegner** [comment]
Thanks for the update, I resolved most of my comments.
I also tested it to set up a VM today and it worked fine except for one issue, see below.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[scion_install_script.sh, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vj4xtAvcbZoFsTP48:-L-bIvbN1XR5A2BBAGKP:bldyx5x) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L51)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We should probably check somewhere that this is indeed a Ubuntu or Ubuntu-like system and print an error message otherwise.
</blockquote></details>

Does this check also work in the Raspberry Pi distributions?

---

*[scion_install_script.sh, line 89 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-bOXJ2Xve2EoykPk3v:-L-bOXJ3DWfs9afVPpFE:bkgo5ri) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4cef5de863147e25a71ef344d921242725288a54/scion_install_script.sh#L89)):*
> ```Shell
> 
> git config --global url.https://github.com/.insteadOf git@github.com:
> git clone --recursive -b scionlab git@github.com:netsec-ethz/scion
> ```

The repository was moved today, so we need to replace this line by 
`git clone --recursive -b scionlab git@github.com:netsec-ethz/netsec-scion scion`

---

*[scion_install_script.sh, line 193 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-bJhXRYC8YR2DOXF0S:-L-bJhXRYC8YR2DOXF0T:b-mkc7w3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/4cef5de863147e25a71ef344d921242725288a54/scion_install_script.sh#L193)):*
> ```Shell
>     rm tmp.service
> else
>     echo "SCION viz systemd service file not specified! SCION-viz won't run automatically on startup."
> ```

SCION-viz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-:-L-bMScRir6ZQ6kDi4y7:b8jxd0m)*

**Comment by xabarass** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[scion_install_script.sh, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vj4xtAvcbZoFsTP48:-L-cW7rdUAaq9I1hYNYo:bfozctd) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L51)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Does this check also work in the Raspberry Pi distributions?
</blockquote></details>

It runs on Ubuntu distributions for Raspberry PI (Ubuntu MATE for example) which is also a recommended distro on scion-tutorials. There was an issue with building it for Raspbian, but i didn't spend much time debugging it. So for now i would leave it like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130)*

**Comment by mlegner** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scion_install_script.sh, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-L-Vj4xtAvcbZoFsTP48:-L-eZX670_0xnlLqZmlX:bhnv5q1) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/f9f593136e32011f8d0157faa4d3f3c59b72c49d/scion_install_script.sh#L51)):*
<details><summary><i>Previously, xabarass (Milan Pandurov) wrote…</i></summary><blockquote>

It runs on Ubuntu distributions for Raspberry PI (Ubuntu MATE for example) which is also a recommended distro on scion-tutorials. There was an issue with building it for Raspbian, but i didn't spend much time debugging it. So for now i would leave it like this.
</blockquote></details>

OK, sounds good to me. We should keep this in mind though in case we want to support other distributions as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-:-L-eZiYUYf1GxU-sf9zr:bnfp4nl)*

**Comment by mlegner** [comment]
@xabarass Could you squash all commits into one, then we can merge the PR.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/130#-:-L-eZws_59KDL40DGBB1:b-a3wowq)*

**Pull request merged**
