### PR TITLE
Add option to use OpenVPN-based connection to SCIONLab AS

### PR DESCRIPTION
**Pull request by mlegner**
This PR addresses issue  #57 by extending the SCIONLab Coordination Service by an additional connection option via openVPN.
It builds onto PR #69 and extends both the backend and UI with openVPN functionality.
Necessary files such as an openVPN configuration file are added and additional dependencies are documented in the `README.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/72)

### CODE REVIEW

**Comment by ercanucan** [comment]
Review status: 0 of 16 files reviewed at latest revision, 12 unresolved discussions.

---

*[main.go, line 51 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPIYHE9ANwANYiK4Jx:-KuPIYHFSdSOVcTdIQuA:b-c5nq8z) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/main.go#L51)):*
> ```Go
> 			}
> 		} else {
> 			fmt.Printf("ERROR: Cannot get SCIONLab AS configuration from database: %v", err)
> ```

Does it make sense to continue and start the application if something went wrong during `init()`? Logging is good but maybe we should also exit or panic.

---

*[README.md, line 82 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPJqzRx66nSud_X0ZQ:-KuPJqzRx66nSud_X0ZR:becq0n7) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/README.md#L82)):*
> ```Markdown
> #### Certificate authority setup
> 
> In order to use openVPN inside the generated SCIONLab VMs, it is necessary to set up a certificate 
> ```

minor: OpenVPN instead of openVPN.

---

*[conf/development.conf.default, line 60 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPKMPh97-kwwkEPLqQ:-KuPKMPicU4DQ9O9bY9e:b-rg3zm9) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/conf/development.conf.default#L60)):*
> ```
> server.vpn.ip = "10.0.8.1"
> server.vpn.start_ip = "10.0.8.2"
> server.vpn.end_ip = "10.0.8.254"
> ```

Why 254 and not 255?

---

*[conf/easy-rsa_vars.default, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPKpplnR3v6Ddqu2AD:-KuPKpplnR3v6Ddqu2AE:b-vc9542) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/conf/easy-rsa_vars.default#L68)):*
> ```
> export KEY_ORG="ETH"
> export KEY_EMAIL="scion@lists.inf.ethz.ch"
> export KEY_OU="Netsec"
> ```

Better NetSec or netsec.

---

*[controllers/api/scion_lab.go, line 97 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPMYvIB2vrsd85boks:-KuPMYvJBLHUn5ipiXlE:b9cdnkf) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L97)):*
> ```Go
> 	RemoteIP   string             // the IP address of the SCIONLab AS it connects to
> 	RemotePort int                // port number of the remote SCIONLab AS being connected to
> 	VPNIP      string             // IP of the VPN server
> ```

I would keep this field below the `IsVPN` field, so that we have the related information together.

---

*[controllers/api/scion_lab.go, line 125 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPN3n78ZhVKKy05k1Q:-KuPN3n78ZhVKKy05k1R:buao9un) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L125)):*
> ```Go
> 		return
> 	}
> 	// Target SCIONLab ISD and AS to connect to is determined by config file
> ```

Comment slightly inaccurate now. ISD is still decided in the line below :) 

---

*[controllers/api/scion_lab.go, line 132 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPNDhsI_CEh4EOhOIq:-KuPNDhsI_CEh4EOhOIr:b-jqr0di) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L132)):*
> ```Go
> 		return
> 	}
> 	// Remove all existing files from UserPackagePath TODO: May want to archive somewhere?
> ```

Better to place TODO items in a separate line. Also please add your GitHub ID in, such as TODO (mlegner).....

---

*[controllers/api/scion_lab.go, line 249 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPLMbyj1ZGrL5BOin1:-KuPLMbyj1ZGrL5BOin2:bb5cpjp) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L249)):*
> ```Go
> 		scionLabServer.VPNLastAssignedIP = ip
> 		remoteIP = scionLabServer.VPNIP
> 		log.Printf("new VPN IP to be assigned = %v", ip)
> ```

Did you place these logs only for debugging purposes? If so, we could remove them. If not, then the logging statement should log a bit more information such as user details.

---

*[controllers/api/scion_lab.go, line 254 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPLeNJ7V124pvF7JqS:-KuPLeNJ7V124pvF7JqT:brhumzt) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L254)):*
> ```Go
> 		if newUser {
> 			remotePort = scionLabServer.VPNLastAssignedPort + 1
> 			log.Printf("newPort to be assigned = %v", remotePort)
> ```

Same here.

---

*[controllers/api/scion_lab.go, line 428 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPONOTjAxhOW4-x1Jb:-KuPONOUHIpkNKulIAQA:b-653wht) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L428)):*
> ```Go
> }
> 
> func (s *SCIONLabVMController) generateVPNConfig(svmInfo *SCIONLabVMInfo) error {
> ```

I would add a brief comment about this function as well. Also, maybe it makes sense to place these functions into a file such as `scion_lab_vpn.go`? This file is already fairly large. Plus, it would be good to have the VPN related logic in one place.

---

*[public/js/controllers/user.js, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPPhYcMpQdJkjDPpT1:-KuPPhYcMpQdJkjDPpT2:b-kbh46f) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/public/js/controllers/user.js#L16)):*
> ```JavaScript
>                         $scope.vmInfo = data["VMInfo"];
>                         $scope.buttonConfig = data["UIButtons"];
>                         $scope.user.isNotVPN = false;
> ```

Why a field named `isNotVPN` whereas in the back-end code we have `isVPN`. It may be more intuitive to read if you named both the fields `isVPN`.

---

*[utility/utility.go, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPQGPsVkNFTIuuknyi:-KuPQGPtaJKgwTJslXfT:b-kyerpj) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/utility/utility.go#L61)):*
> ```Go
> 
> // returns -1, if ip1 < ip2, 0, if ip1 == ip2, +1, if ip1 > ip2
> func IPCompare(ip1, ip2 string) int8 {
> ```

A couple of unit tests for these functions would be very nice to have. And I think they would be easy to write.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72)*

**Comment by ercanucan** [comment]
@mlegner Made a pass.

---

Review status: 0 of 16 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-:-KuPQTCWgUzyZMXaJwK7:b-bu3dv0)*

**Comment by mlegner** [comment]
Review status: 0 of 16 files reviewed at latest revision, 12 unresolved discussions.

---

*[main.go, line 51 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPIYHE9ANwANYiK4Jx:-KuYlpN3Fo7n2sHyZ7uE:bdc92e8) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/main.go#L51)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Does it make sense to continue and start the application if something went wrong during `init()`? Logging is good but maybe we should also exit or panic.
</blockquote></details>

Done. I moved this initialization into a different function that returns an error.

---

*[README.md, line 82 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPJqzRx66nSud_X0ZQ:-KuYmDpORRvsJFmaPgci:bq4sm40) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/README.md#L82)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: OpenVPN instead of openVPN.
</blockquote></details>

Done. Changed all occurrences.

---

*[conf/development.conf.default, line 60 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPKMPh97-kwwkEPLqQ:-KuYmFHcn9ShbKx-NNIh:bkpb54) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/conf/development.conf.default#L60)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Why 254 and not 255?
</blockquote></details>

I thought it would be better not to interfere with the broadcast address.

---

*[conf/easy-rsa_vars.default, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPKpplnR3v6Ddqu2AD:-KuYmuehzY5--X8H3QLG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/conf/easy-rsa_vars.default#L68)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Better NetSec or netsec.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 97 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPMYvIB2vrsd85boks:-KuYn8ZgvTTIJXgOHtCY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L97)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would keep this field below the `IsVPN` field, so that we have the related information together.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 125 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPN3n78ZhVKKy05k1Q:-KuYnw9C0_LeFUVNNPob:bncii2b) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L125)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Comment slightly inaccurate now. ISD is still decided in the line below :) 
</blockquote></details>

Done. Added utility function which extracts the ISD.

---

*[controllers/api/scion_lab.go, line 132 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPNDhsI_CEh4EOhOIq:-KuYo3oyGySOTPESnH9l:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L132)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Better to place TODO items in a separate line. Also please add your GitHub ID in, such as TODO (mlegner).....
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 249 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPLMbyj1ZGrL5BOin1:-KuYoKm8szBbq58V_J51:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L249)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Did you place these logs only for debugging purposes? If so, we could remove them. If not, then the logging statement should log a bit more information such as user details.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 254 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPLeNJ7V124pvF7JqS:-KuYoLSjYkPNjq5B19v9:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L254)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 428 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPONOTjAxhOW4-x1Jb:-KuYoybO4tC-u6fKbCzA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L428)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I would add a brief comment about this function as well. Also, maybe it makes sense to place these functions into a file such as `scion_lab_vpn.go`? This file is already fairly large. Plus, it would be good to have the VPN related logic in one place.
</blockquote></details>

Done.

---

*[public/js/controllers/user.js, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPPhYcMpQdJkjDPpT1:-KuYp-a0XpyzTMyrNVRr:b-jzqs8l) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/public/js/controllers/user.js#L16)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Why a field named `isNotVPN` whereas in the back-end code we have `isVPN`. It may be more intuitive to read if you named both the fields `isVPN`.
</blockquote></details>

The reason is that this variable is set by the checkbox choosing a "normal" setup. It is the easiest way to get this information with Angular.

---

*[utility/utility.go, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPQGPsVkNFTIuuknyi:-KuYw0pO98XCUPingb_g:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/utility/utility.go#L61)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

A couple of unit tests for these functions would be very nice to have. And I think they would be easy to write.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72)*

**Comment by ercanucan** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 125 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPN3n78ZhVKKy05k1Q:-KuZTsSfivX5oSyIrjQw:b-e04d1e) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L125)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Done. Added utility function which extracts the ISD.
</blockquote></details>

Nice, but we actually do have a library in the main repo to represent ISD-AS. Would probably be better to use that one instead:
https://github.com/netsec-ethz/scion/blob/master/go/lib/addr/isdas.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72)*

**Comment by mlegner** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/scion_lab.go, line 125 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-KuPN3n78ZhVKKy05k1Q:-KuZXxxCF3EWqIkLy_W-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/9235a9195277c97faa587f6dcf2b4e3a9c800c55/controllers/api/scion_lab.go#L125)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Nice, but we actually do have a library in the main repo to represent ISD-AS. Would probably be better to use that one instead:
https://github.com/netsec-ethz/scion/blob/master/go/lib/addr/isdas.go
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72)*

**Comment by mlegner** [comment]
Squashed and rebased PR.

---

Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-:-Kv6f0RPYw6nfc6k-60O:b-rxx2pm)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72#-:-Kv6hR7d6YB8pHNiPu3S:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 3 of 30 files at r1, 8 of 14 files at r2, 8 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/72)*

**Pull request merged**
