### PR TITLE
Initial SCIONLabVM Support

### PR DESCRIPTION
**Pull request by ercanucan**
Combination of ercanucan and jonghoonkwon's work

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/36)

### CODE REVIEW

**Comment by jonghoonkwon** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMnhdZi9Trsa5_0QSM:-KqMnhdZi9Trsa5_0QSN:b93tdy6) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L126)):*
> ```Go
> 
> func (s *SCIONLabVMController) ReturnTarball(w http.ResponseWriter, r *http.Request) {
> 	log.Printf("Inside ReturnTarball = %v", r.URL.Query())
> ```

I think we don't need this debugging code anymore.

---

*[controllers/api/scion_lab.go, line 143 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMvI4k3Sde6skEl1Jy:-KqMvI4k3Sde6skEl1Jz:bxvgjgx) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L143)):*
> ```Go
> // Generates a SCIONLab VM
> // TODO (ercanucan): Refactor this function into smaller pieces!!!
> func (s *SCIONLabVMController) GenerateSCIONLabVM(w http.ResponseWriter, r *http.Request) {
> ```

My suggestion for the function name is 'HandleGenerateSCIONLabVMRequest'.
And, I think we can separate this function into smaller pieces, for example:

HandleGenerateSCIONLabVMRequest {
     GetUserInfo()
     SetUserInfo()
     GenerateSCIONLabVM() {
          generateTopologyFile()
          generateLocalGen()
          packageSCIONLabVM()
     }
     UpdateUserInfo()
}    

---

*[controllers/api/scion_lab.go, line 295 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMyzfPUp9H2kui4sUX:-KqMyzfPUp9H2kui4sUY:b-r8km3v) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L295)):*
> ```Go
> 		"REMOTE_PORT":  remotePort,
> 	}
> 	err = t.Execute(f, config)
> ```

We can reduce a line via:
if err = t.Execute(f, config); err != nil {

---

*[controllers/api/scion_lab.go, line 314 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-1H_Tr8knZgzqmIS:-KqN-1H_Tr8knZgzqmIT:b-2guby3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L314)):*
> ```Go
> 	cmdErr, _ := cmd.StderrPipe()
> 	startErr := cmd.Start()
> 	if startErr != nil {
> ```

same here

---

*[controllers/api/scion_lab.go, line 336 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-2i-PW1T0Phy8Yqb:-KqN-2i-PW1T0Phy8Yqc:b-2guby3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L336)):*
> ```Go
> 		if !obj.IsDir() {
> 			err = CopyFile(src, dst)
> 			if err != nil {
> ```

same here

---

*[controllers/api/scion_lab.go, line 344 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-4TZkNMVLsqgbO7a:-KqN-4TZkNMVLsqgbO7b:b-2guby3) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L344)):*
> ```Go
> 	cmd.Dir = package_path
> 	startErr := cmd.Start()
> 	if startErr != nil {
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36)*

**Comment by ercanucan** [comment]
Review status: 14 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMnhdZi9Trsa5_0QSM:-KqOMCq9bZIxCTCdh1e6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L126)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

I think we don't need this debugging code anymore.
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 143 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMvI4k3Sde6skEl1Jy:-KqONukj31DMBqPKG0hW:b-hqwt2l) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L143)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

My suggestion for the function name is 'HandleGenerateSCIONLabVMRequest'.
And, I think we can separate this function into smaller pieces, for example:

HandleGenerateSCIONLabVMRequest {
     GetUserInfo()
     SetUserInfo()
     GenerateSCIONLabVM() {
          generateTopologyFile()
          generateLocalGen()
          packageSCIONLabVM()
     }
     UpdateUserInfo()
}    

</blockquote></details>

Yes, agree. It was in one of my immediate TODO items as noted at the top of this function :-)  I have done an initial refactoring of it. Also introduced a new struct called `SCIONLabVMInfo` to keep the information together. This way we do not have to pass long list of parameters to functions such as `generateTopologyFile`, `updateDB` etc. Have a look and let me know what you think of the direction. We still have a fair amount of error handling and reporting related TODOs which I will work on next.

---

*[controllers/api/scion_lab.go, line 295 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqMyzfPUp9H2kui4sUX:-KqOMMIG8mykRyUIHB1X:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L295)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

We can reduce a line via:
if err = t.Execute(f, config); err != nil {
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 314 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-1H_Tr8knZgzqmIS:-KqOMVlM2uxMSy2KZptc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L314)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 336 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-2i-PW1T0Phy8Yqb:-KqON1VxpfERHsWdb9rA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L336)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[controllers/api/scion_lab.go, line 344 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqN-4TZkNMVLsqgbO7a:-KqON1rHgtBF1nRc99GA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/86695e50aa839d819ad10a4c4f1bcb916d747955/controllers/api/scion_lab.go#L344)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36)*

**Comment by ercanucan** [comment]
@jonghoonkwon re-worked some of the error handling. It would be great if you could have a detailed look.

**Comment by ercanucan** [comment]
@chaehni it would be good if you can also have a look at this PR when you get a chance.

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[controllers/api/scion_lab.go, line 269 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqbH0DcyzUpLf4Z9aJB:-KqbH0DcyzUpLf4Z9aJC:b-bj9cpl) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f99f8635eb00f935b670fc721f1aca16d9ed77/controllers/api/scion_lab.go#L269)):*
> ```Go
> 		"--joining_ia="+isdID+"-"+asID)
> 	env := os.Environ()
> 	env = append(env, "PYTHONPATH="+python_path+":"+scion_path)
> ```

In order to import SCION-WEB lib, it also needs to add scion_web_path into the env value. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-:-KqbJMrVr4dZPCiaQbyL:bnfp4nl)*

**Comment by ercanucan** [comment]
@jonghoonkwon added the simplified local_gen.py provided by you and the small tweaks we did to adapt it to scion-coord code-base

**Comment by ercanucan** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/api/scion_lab.go, line 269 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-KqbH0DcyzUpLf4Z9aJB:-KqcWA5oAr_PmHbycYKw:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/70f99f8635eb00f935b670fc721f1aca16d9ed77/controllers/api/scion_lab.go#L269)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

In order to import SCION-WEB lib, it also needs to add scion_web_path into the env value. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36)*

**Comment by jonghoonkwon** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36)*

**Comment by jonghoonkwon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/36#-:-KrVZhMEM5BCTNhC_sdW:bnfp4nl)*

**Comment by ercanucan** [comment]
@jonghoonkwon as discussed, merging this initial work. Further improvements will come as separate PRs.

**Pull request merged**
