### PR TITLE
Enable multiple ASes per user, multiple Attachment Points, and different AS types

### PR DESCRIPTION
**Pull request by mlegner**
This PR builds onto PR #133 and addresses issues #46, #70, and #45. It replaces PRs #73 and #95.
It enables users to create multiple SCIONLab ASes and connect them to multiple attachment points.
For each AS they can set up different connection options.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-coord/136)

### CODE REVIEW

**Comment by hausheer** [comment]
@mlegner it looks like the changes from @xabarass in #142 are not considered in this PR yet. Apart from that, I successfully managed to setup my own coordinator and attachment point and create a VM from it, after I figured out how to populate the database.

To this end, it would be great to extend the README file to describe how the database needs to be populated initially with the specific data related to an initial SCIONLabAS and attachment point (as well as a default admin user) or even better a bootstrapping function that would do so, including the setup of the VPN server (all this could be set in the config file and adapted if needed) such that it is possible to setup an attachment point with hardly any configuration changes, a.o.

`INSERT INTO attachment_point (v_p_n_i_p, start_v_p_n_i_p, end_v_p_n_i_p) VALUES ("10.8.0.1","10.8.0.2","10.8.0.255");`
`INSERT INTO s_c_i_o_n_lab_a_s (id, user_email, public_i_p, start_port, i_s_d, a_s_i_d, status, a_p_id, created, updated) VALUES (1, "admin@email", "public IP address", 50000, 1, 1001, 1, 1, now(), now());`
`UPDATE user SET is_admin=1 where id='1';`
etc.

A strange error is that the VM config provided by the coordinator is wrongly encoded, e.g. <<-SCRIPT was replaced with &lt;&lt;-SCRIPT in the Vagrantfile and also the inline VPN certificates and keys in client.conf have several &#43; encodings of the + sign

@philippmao and @FR4NK-W: it would be great if you could test this PR as well. We will need to figure out how to merge #131 later with this, as there are a number of conflicting changes. 

@chaehni Could you maybe do a more detailed review of the code for this PR?

**Comment by mlegner** [comment]
Thank you for the review.
Indeed, #142 is not yet part of this PR, I still have to rebase it.
Concerning the bootstrapping function, I completely agree. I will create an issue for this.

Thanks for pointing out the encoding errors: They come from the use of an incorrect template function and should be fixed now.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-:-L0smWEm4fXazgcML4y4:bewpg00)*

**Comment by FR4NK-W** [comment]
Reviewed 8 of 41 files at r1.
Review status: 8 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136)*

**Comment by hausheer** [comment]
@mlegner thanks for fixing the template issue and thanks @FR4NK-W for the review. What's the status of this PR, is it ready to be merged? It would be great if we could do so, in order to be able to move on.

**Comment by hausheer** [comment]
@mlegner thanks for fixing the template issue and thanks @FR4NK-W for the review. What's the status of this PR, is it ready to be merged? It would be great if we could do so, in order to be able to move on.

**Comment by hausheer** [comment]
@chaehni could you may take a look at this as well?

**Comment by chaehni** [comment]
I made a pass. It looks good to me. I had noted down some minor things but Reviewable seems not to work for me at the moment. I hope the comments are preserved so I can publish them as soon as possible.

**Comment by FR4NK-W** [comment]
Reviewed 1 of 41 files at r1.
Review status: 9 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[controllers/api/scion_lab_ap.go, line 196 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38PREUVZ2bgvJsMnRI:-L38PP9jMktssDpvnrwL:b4gp85w) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/scion_lab_ap.go#L196)):*
> failedConfirmations = append(failedConfirmations, ia)
I think it would make sense to bulk send the confirmation emails to the users after having updated the connections and not do it in the inner loop, i.e. sending the emails should not delay the rest of the operations.

---

*[controllers/api/user.go, line 191 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38RIsm8eKJCbmyiUaX:-L38RIsm8eKJCbmyiUaY:b-t92tuk) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/user.go#L191)):*
> ```Go
> 	}
> 
> 	aI, aps, err := populateASStatusButtons(user.Email)
> ```

asInfo? We already have ia and so on just one mistyping away

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136)*

**Comment by FR4NK-W** [comment]
Reviewed 11 of 41 files at r1.
Review status: 20 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[models/scion_lab.go, line 202 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38goC4Io0O3WI5_gOl:-L38goC4Io0O3WI5_gOm:bsih94c) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/models/scion_lab.go#L202)):*
>if as.Type == INFRASTRUCTURE {

Shouldn't it say `if as.Type != INFRASTRUCTURE` ? Since we want to have minBRID to be the lowest allowed port?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136)*

**Comment by hausheer** [comment]
@FR4NK-W @chaehni thank you for reviewing this PR. @mlegner did you have a chance to take a look? Github shows that some checks and conflicts are still open. How close are we for merging this one?

**Comment by mlegner** [comment]
I was waiting for further comments from @chaehni.
@FR4NK-W's comments are relatively easily fixed. Unfortunately, since PR #131 was merged, I have to rebase my PRs which is not completely trivial as there are significant overlaps.

**Comment by chaehni** [comment]
Reviewed 38 of 43 files at r1, 1 of 1 files at r2.
Review status: 37 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[controllers/api/scion_lab_ap.go, line 65 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/136#-L3NUDeiNRJuFEFv4a5P:-L3NUDejhJWqzWKu2M0J:b-pyjb2r) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/scion_lab_ap.go#L65)):*
> ```Go
> // }
> func (s *SCIONLabASController) GetUpdatesForAP(w http.ResponseWriter, r *http.Request) {
> 	log.Printf("Inside GetUpdatesForAP = %v", r.URL.Query())
> ```

Is this a debug statement?

---

*[controllers/middleware/authorization.go, line 32 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/136#-L3Ol7Dt4oICBpKUyRVz:-L3Ol7Duec3bySckUc_w:b-158cuu) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/middleware/authorization.go#L32)):*
> ```Go
> )
> 
> // TODO(mlegner): We need an additional authorization handler that checks if the account is an admin
> ```

Is this resolved in the mean time?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/136)*

**Comment by mlegner** [comment]
@chaehni @fr4nk-w @hausheer I rebased the PR on the current master and tried to address all your comments. I did a very quick test but nothing thorough yet. Please have another look and let me know if there are further issues or we can merge the PR.

---

Review status: 27 of 46 files reviewed at latest revision, 6 unresolved discussions.

---

*[controllers/api/scion_lab_ap.go, line 65 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L3NUDeiNRJuFEFv4a5P:-L3lSC21NzfPWHYvHkX5:b-wajqua) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/scion_lab_ap.go#L65)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Is this a debug statement?
</blockquote></details>

This has been there for some time now. I think it makes sense to have this in the log, but I changed the wording a little bit to make it sound less like a debug statement.

---

*[controllers/api/scion_lab_ap.go, line 196 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38PREUVZ2bgvJsMnRI:-L3lVBMMFw8oySkFLJDL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/scion_lab_ap.go#L196)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> failedConfirmations = append(failedConfirmations, ia)
I think it would make sense to bulk send the confirmation emails to the users after having updated the connections and not do it in the inner loop, i.e. sending the emails should not delay the rest of the operations.
</blockquote></details>

Done.

---

*[controllers/api/user.go, line 191 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38RIsm8eKJCbmyiUaX:-L3lVKi42Rv3gkdCc0LG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/api/user.go#L191)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

asInfo? We already have ia and so on just one mistyping away
</blockquote></details>

Done.

---

*[controllers/middleware/authorization.go, line 32 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L3Ol7Dt4oICBpKUyRVz:-L3lVPRuyWUAHXT5k-y9:be0ofeh) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/controllers/middleware/authorization.go#L32)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

Is this resolved in the mean time?
</blockquote></details>

No this is not resolved. However, that is not really related to this PR; I have added an issue for this.

---

*[models/scion_lab.go, line 202 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-L38goC4Io0O3WI5_gOl:-L3lW_8cBajxnMVreTek:b-kvh9fv) ([raw file](https://github.com/netsec-ethz/scion-coord/blob/6b43b9aa5e1349e20ce67de75c0578b233a771f2/models/scion_lab.go#L202)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>if as.Type == INFRASTRUCTURE {

Shouldn't it say `if as.Type != INFRASTRUCTURE` ? Since we want to have minBRID to be the lowest allowed port?
</blockquote></details>

Done. Thanks for spotting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-:-L3lRukUIRvSwrEoducf:b-3ry8rs)*

**Comment by hausheer** [comment]
Thanks @mlegner, no further comments from my side. I plan to do further tests once this is merged.

**Comment by chaehni** [comment]
I resolved my issues. :lgtm: 

---

Reviewed 1 of 41 files at r1, 8 of 18 files at r3.
Review status: 36 of 46 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-coord/136#-:-L409L2X3JAz1sr-_osj:bioeejk)*

**Comment by mlegner** [comment]
@FR4NK-W Could you have a look again and resolve your discussions?

**Comment by FR4NK-W** [comment]
:lgtm:

---

Review status: 17 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/136#-:-L4Hqilh803uxh7viU3q:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Reviewed 1 of 43 files at r1, 9 of 19 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-coord/136)*

**Pull request merged**
